### ISSUE TITLE
Array Binding Support

### ISSUE THREAD

**Issue by x0d3r** [rana/ora#100]
Is it possible to perform Array Binding?

[http://www.oracle.com/technetwork/issue-archive/2009/09-sep/o59odpnet-085168.html](http://www.oracle.com/technetwork/issue-archive/2009/09-sep/o59odpnet-085168.html)
[http://docs.oracle.com/html/B14164_01/featOraCommand.htm#i1007888](http://docs.oracle.com/html/B14164_01/featOraCommand.htm#i1007888)

**Comment by tgulacsi** [comment]
Sure. Just use ses.PrepAndExeP or stmt.ExeP.

**Comment by x0d3r** [comment]
Thanks, I'll take a look.
