### ISSUE TITLE
Create rset with autoClose

### ISSUE THREAD

**Issue by NOX73** [rana/ora#101]
I need to create `rset` with `autoClose=true` from my code. I call a procedure which returns a `rset` as a result. But in this case, the `rset` doesn't close statement.

**Comment by tgulacsi** [comment]
Every rset from PrepAndQry is with autoClose=true. BUT you have to exhaust it: call Next() till it returns false: `for rset.Next() {}` even if you use only the first row!
Otherwise, it does not know it should close...

**Comment by NOX73** [comment]
@tgulacsi no, I can't use it. I pass `rset` to a stored procedure. I create it in my code:
```golang
        stmt, err := Ses().Prep(query)
 	rst := &ora.Rset{}
 	args = append(args, rst)
	if _, err = stmt.Exe(args...); err != nil {
		return nil, err
 	}
        return rst, err
```

**Comment by tgulacsi** [comment]
Wow, I've never thought about such a use case :)

You'll have to keep that stmt (and its ses and srv and env) around till your stored procedure is using that cursor, anyway.
But as that procedure has to finish with it when returns, you can do the `for rset.Next() {}` in a defer or right after the `stmt.Exe`, can't you?

**Comment by NOX73** [comment]
Actualy, I can't call `for rset.Next() {}` in the same function I create stmt and rst, so I would like to return only `rset` and call `Next` somewhere else.

**Comment by tgulacsi** [comment]
You can, just don't (explicitly) close the stmt. Maybe return an interface, which includes io.Closer, and that Closer could close everything in order: `for rset.Next() {}; stmt.Close()`. Or make it a "cancel" like in context.
