### ISSUE TITLE
Nill types

### ISSUE THREAD

**Issue by goloveychuk** [rana/ora#105]
I have structure
```go
type A struct {
   Count *int
  Name *string
}
```
I'm using `ora` with `database/sql`.
When I'm executing and scanning (via sqlx) `select null as count, null as name from dual` I'm receiving `count=0`, `name=''`.
How to receive nils? Thanks.

**Comment by tgulacsi** [comment]
Use ora.OraInt64 and ora.OraString as the types; or set the default types
with ora.Cfg()....Rset.SetNumber(ora.OraN) ...

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. júl. 13.,
Sze, 14:59):

**Comment by goloveychuk** [comment]
@tgulacsi 
`	drvCfg.Env.StmtCfg.Rset.SetVarchar(ora.OraS)`
`sql: Scan error on column index 0: unsupported Scan, storing driver.Value type ora.String into type *string`

**Comment by tgulacsi** [comment]
Sorry for the wrong advice. What about sql.NullString?

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. júl. 13.,
Sze 16:07):

**Comment by goloveychuk** [comment]
as I understood when i'm writing 
`drvCfg.Env.StmtCfg.Rset.SetVarchar(ora.OraS)`
I'm getting isNullable there. 
https://github.com/rana/ora/blob/master/defString.go#L54

but the question is why in 57 line it returning "". Maybe it should return nil? And same for int, double, time.
If no, I'll make fork, just tell me.

**Comment by tgulacsi** [comment]
You can try with nil, if it passes the tests (works with sql, too), I'll
accept the PR!

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. júl. 13.,
Sze, 19:13):

**Comment by tgulacsi** [comment]
Sorry for these short answers, but I don't have the time to investigate this issue as thoroughly, as it'd deserve. 
To be honest, the empty string is absolutely correct for an Oracle NULL, as in Oracle, you can't distinguish an empty string from NULL: LENGTH('') is NULL (not zero), and '' IS NULL is TRUE!

Maybe returning nil for nil values works for def*.value methods, but I don't know. It has to be tested.
