### ISSUE TITLE
Get OraError

### ISSUE THREAD

**Issue by goloveychuk** [rana/ora#107]
Hello. 
How after 
```go
res, err := self.Db.Exec(text, args...)
```
Cast error (to understand if it's duplicate error, e.g.)
This code wont work because  oraError is not error  (dont have error method)
```go
if e, ok := err.(ora.ORAError); ok {
		if e.Code() == 1 {
			return 0, false
		}
	}
```

**Comment by goloveychuk** [comment]
this dont work too
```go
	if e, ok := err.(*ora.ORAError); ok {
```

**Comment by tgulacsi** [comment]
Why?

By the way, I'd turn this around, and use an interface:

    if e, ok := err.(interface{
        Code() int
    }); ok {
      if e.Code() == 1 { return 0, false }
    }

**Comment by tgulacsi** [comment]
Maybe it'd help if you'd print  the error's type: `fmt.Printf("%T %#v",
err, err)`

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. júl. 18.,
H, 13:09):

**Comment by goloveychuk** [comment]
hm, this is good idea to use `interface{    Code() int }`, it works, thanks.

btw printf outputs 
`*ora.oraErr &ora.oraErr{Caller:ora.methodInfo{Type:"DrvStmt", Method:"Exec"}, Underlying:(*ora.oraErr)(0xc82000e640), Trace:[]uint8(nil)}`

**Comment by tgulacsi** [comment]
So, it is NOT a public (exportred) type, that's why the type assert fails.
Struct embedding allows the interface assertion, and that's clear, so use
that.

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. júl. 18.,
H, 15:59):
