### ISSUE TITLE
CTRL+C signal causes program  to crash on Linux and OS X

### ISSUE THREAD

**Issue by jusongchen** [rana/ora#108]
Step to reproduce the issue:

1)build the test program (https://github.com/jusongchen/rana_ora_test)

2) run the programm , pass in the connection string as the first parameter. e.g:

rana_ora_test scott/tiger@//hostname/oracle_sid
3) Enter CTRL+C after the prompt

4) CTRL+C signal won't cause any issue before a DB operation. However, after a DB operation, it will crash the programm with message

"llegal instruction: 4" -- on Mac OS X

or "Trace/breakpoint trap" --on Ubuntu Linux.

**Comment by tgulacsi** [comment]
Cannot reproduce:

```
gthomas@tequila:/tmp$ go run oracle.go test/test@localhost:49161/xe
Waiting for SIGHUP signal, press CTRL+C to continue . . .
^C
SIGHUP received, ignore this signal and continue ...
DB query returns:+3.141593e+000 Hello
Waiting for SIGHUP signal, press CTRL+C to continue . . .
^Csignal: trace/breakpoint trap
gthomas@tequila:/tmp$ go version
go version go1.7rc5 linux/amd64
gthomas@tequila:/tmp$ uname -a
Linux tequila 4.6.0-1-amd64 #1 SMP Debian 4.6.2-2 (2016-06-25) x86_64 GNU/Linux
```

**Comment by tgulacsi** [comment]
Or don't understand, what that "trace/breakpoint trap" means...

**Comment by tgulacsi** [comment]
Even with properly canceling the signal handlers:
[oracle.go.gz](https://github.com/rana/ora/files/405568/oracle.go.gz)
it reproduces the problem.

Googling shows up only GDB, so must be something with the OCI libraries. Either they install their own signal handlers, which interfere with Go runtime's, or I don't know.

**Comment by jusongchen** [comment]
Hi Tamas,

Thank you for looking into this. The 'trace/breakpoint trap" indicates the
SIGHUP caused a crash. I do not know what the root cause is. There may be a
need to set some CGO flags when importing C code, as shown here:

cgo_flags.go
<https://github.com/cockroachdb/c-rocksdb/blob/master/cgo_flags.go>


thank you,

Jusong

**Comment by tgulacsi** [comment]
Just as I thought, it's the OCI client's fault: http://stackoverflow.com/questions/17124881/oracle-proc-oci-install-handlers-for-sigsegv-sigabrt-and-friends-why-and-how
