### ISSUE TITLE
Potential memory leak in method Ses.Prep

### ISSUE THREAD

**Issue by petri-vesanen** [rana/ora#115]
We observed increasing process memory usage after each query. It seems that Ses.Prep method allocates handles that are not released. We tried removing OCIHandleAlloc before OCIStmtPrepare2.

Pull request: https://github.com/rana/ora/pull/114

What do you think? Could this be the reason and is it safe to remove the handle allocation as it is done in the pull request? At least after applying the pull request, the process memory usage does not seem to increase.

--

Oracle documentation says: A call to OCIStmtPrepare2(), even if the session
does not have a statement cache, will also allocate the statement handle and
therefore applications using only OCIStmtPrepare2() must not call
OCIHandleAlloc() for the statement handle.

See: https://docs.oracle.com/cd/B19306_01/appdev.102/b14250/oci09adv.htm

--

Best Regards,
Petri Vesanen
Alma Talent

**Comment by tgulacsi** [comment]
Merged the pr as https://github.com/rana/ora/commit/fe140a14935c005d3535ec92236f5faa8919ce40
