### ISSUE TITLE
Error when scanning a CLOB : "unsupported Scan, storing driver.Value type ora.Lob into type *string"

### ISSUE THREAD

**Issue by bpizzi** [rana/ora#117]
Hi,

I'm getting a `panic: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type ora.Lob into type *string` when trying to retrieve a CLOB column with database/sql.

I can reproduce with:

```
CREATE TABLE t1 (C1 CLOB);
insert into t1 (C1) values ('xxxx xxxx');
insert into t1 (C1) values ('yyy yyy');
insert into t1 (C1) values ('zz zz');
commit;
```
and:

```
package main

import (
	"database/sql"
	"fmt"
	"gopkg.in/rana/ora.v3"
)

func main() {
	ora.Register(nil)
	db, err := sql.Open("ora", "TEST/TEST@ORCL")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	s := fmt.Sprintf("SELECT * FROM t1")
	fmt.Println(s)

	rows, err := db.Query(s)
	if err != nil {
		panic(err)
	}
	defer rows.Close()
	for rows.Next() {
		var c1 string
		err := rows.Scan(&c1)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%+v\n", c1)
	}

	return
}
```

If you change the column declaration for `CREATE TABLE t1 (C1 VARCHAR2(255));` then rows are scanned correctly.

I'm using the tag v3.7.1.

Thanks to whoever will have time for looking into this ;)

**Comment by tgulacsi** [comment]
Use an interface{} as destination, and convert it to an io.Reader.

Baptiste Pizzighini <notifications@github.com> ezt írta (időpont: 2016.
szept. 26., H 11:39):

**Comment by bpizzi** [comment]
Hey thanks @tgulacsi, that is working:

```
for rows.Next() {
		var c1 interface{}
		err := rows.Scan(&c1)
		if err != nil {
			panic(err)
		}
		r := c1.(io.Reader)
		scan := bufio.NewScanner(r)
		for scan.Scan() {
			fmt.Println(scan.Text())
		}
	}
```

But, just to be sure I'm not misunderstanding something, is it the expected behavior?
I'm referring to the README:
```
The Go-to-Oracle type mapping for database/sql is:
string      CHAR², NCHAR, VARCHAR, VARCHAR2, NVARCHAR2, LONG, CLOB, NCLOB
```
which was what lead me to a string typed column.

Furthermore, this way of scanning make it cumbersome for, say, using Select from https://github.com/jmoiron/sqlx.
For example, the following code is way more convenient for the end user, but it seems difficult to me to handle the empty interface dynamic typing you're suggesting without messing with the simplicity of `db.Select`:

```
package main

import (
	"fmt"
	"github.com/jmoiron/sqlx"
	"gopkg.in/rana/ora.v3"
	"bufio"
	"io"
)

type test struct {
	C1 string `db:"C1"`
}

func main() {
	ora.Register(nil)
	db, err := sqlx.Open("ora", "TEST/TEST@ORCL")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	s := fmt.Sprintf("SELECT * FROM t1")
	var rows []test
	err = db.Select(&rows, s)
	if err != nil {
	 	panic(err)
	}
	fmt.Printf("%+v\n", rows2)

	return
}
```

Thanks for your insight!

**Comment by tgulacsi** [comment]
Maybe we can make Scan into a string work, but a LOB can contain gigabytes of data - are we sure that slurping all that into memory is desired?

**Comment by tgulacsi** [comment]
3f4b321 contains an *ora.Lob with String() method - see TestLobSelectString in z_oracle_test.go.
Not perfect, as you'll need an *ora.Lob as dest, won't work with a string...

**Comment by bpizzi** [comment]
Well you're right about lob's potential size, we surely should take that into consideration.
For what it's worth, my usage of oracle's lob is mainly clob as a better varchar2 (which is caped to 4000 cars). There is hardly more than a few kilobytes in the most heavy lobs I use - but I'm not everyone.

As for *ora.Lob, as you said, this is not perfect as it requires a specific type. 
In my case I aim at using indifferently different DB with the same binary, so I need the struct's members to be as idiomatic as it can get.

Speaking of which: sqlite's TEXT can store 1gb in it's default config, and at least one driver (mattn/go-sqlite3) scan's it directly into a string. As a matter of fact, I just checked the _other_ oracle driver (mattn/go-oci8) and indeed it scans lobs into strings.

Again, I'm not sure we should adopt this behavior, but it would be easier for the end user as long as we document the edge cases.

**Comment by tgulacsi** [comment]
Ok, @rana has made the returned values configurable: 

   ora.Cfg().Env.StmtCfg.Rset.SetClob(ora.S)

will modify the default return type from lobReader to string. 
And of course you'll need the latest master, as the implementation of this mechanism has been left out for Lob... 
(See TestLobSelectString - now Scans into a string!).

**Comment by bpizzi** [comment]
Thanks to you two :+1:
