### ISSUE TITLE
Extra -l flag when building on linux

### ISSUE THREAD

**Issue by msingle** [rana/ora#121]
build fails with message:
    
    /usr/bin/ld: cannot find -lclntsh
running with `go build -x` the error contains:
    
    CGO_LDFLAGS="-g" "-O2" "-lclntsh" "-L/usr/lib/oracle/12.1/client64/lib" "-lclntsh"

If I edit env_posix.go 

and replace `// #cgo LDFLAGS: -lclntsh` with `// #cgo pkg-config: oci8`

it builds successfully.

Pull request to follow

**Comment by tgulacsi** [comment]
Thanks!
It seems that the `env_posix.go` file is obsolete since the transition to pkg-config.
