### ISSUE TITLE
can't get rana/ora.v3

### ISSUE THREAD

**Issue by IsaacVe** [rana/ora#124]
go get gopkg.in/rana/ora.v3  
WINDOWS 8.1 64bit  , go 1.7 32bit MINGW32bit 
is CGO_LDFLAGS???
![003](https://cloud.githubusercontent.com/assets/17584143/19400788/6ebcd4d6-921d-11e6-8661-7b07af196c59.png)
![image](https://cloud.githubusercontent.com/assets/17584143/19401510/4b980d14-9221-11e6-9bce-0998a2d254c3.png)

help me, pls

**Comment by tgulacsi** [comment]
`go get -u -v gopkg.in/rana/ora.v3` ?

**Comment by IsaacVe** [comment]
C:\Go\src\bitbucket.org\autodromo>go get -u -v gopkg.in/rana/ora.v3                                                                                      
Fetching https://gopkg.in/rana/ora.v3?go-get=1                                                                                                           
Parsing meta tags from https://gopkg.in/rana/ora.v3?go-get=1 (status code 200)                                                                           
get "gopkg.in/rana/ora.v3": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v3", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v3"} at https://
gopkg.in/rana/ora.v3?go-get=1                                                                                                                            
gopkg.in/rana/ora.v3 (download)                                                                                                                          
Fetching https://gopkg.in/rana/ora.v3/date?go-get=1                                                                                                      
Parsing meta tags from https://gopkg.in/rana/ora.v3/date?go-get=1 (status code 200)                                                                      
get "gopkg.in/rana/ora.v3/date": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v3", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v3"} at htt
ps://gopkg.in/rana/ora.v3/date?go-get=1                                                                                                                  
get "gopkg.in/rana/ora.v3/date": verifying non-authoritative meta tag                                                                                    
Fetching https://gopkg.in/rana/ora.v3?go-get=1                                                                                                           
Parsing meta tags from https://gopkg.in/rana/ora.v3?go-get=1 (status code 200)                                                                           
Fetching https://gopkg.in/rana/ora.v3/num?go-get=1                                                                                                       
Parsing meta tags from https://gopkg.in/rana/ora.v3/num?go-get=1 (status code 200)                                                                       
get "gopkg.in/rana/ora.v3/num": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v3", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v3"} at http
s://gopkg.in/rana/ora.v3/num?go-get=1                                                                                                                    
get "gopkg.in/rana/ora.v3/num": verifying non-authoritative meta tag                                                                                     
gopkg.in/rana/ora.v3                                                                                                                                     
# gopkg.in/rana/ora.v3                                                                                                                                   
c:/mingw/bin/../lib/gcc/mingw32/5.3.0/../../../../mingw32/bin/ld.exe: cannot find -lclntsh                                                               
collect2.exe: error: ld returned 1 exit status

**Comment by tgulacsi** [comment]
That's quite strange, as I see no "-lclntsh" in any of the ".go" files - we use pkg-config since 8bf5a5b52  
What if you remove `%GOPATH%\src\gopkg.in\rana\ora.v3`, and start over?
What does `pkg-config --libs oci8` say?

**Comment by alvaradopcesar** [comment]
There are some documentation to setup Go / Oracle / gopkg.in/rana/ora.v3 for Windows ?
Paths
Something like this in windows  
GOPATH="C:\Users\gabe\src\go_projects"
CGO_CFLAGS="-IC:\oracle\instancliente\"
CGO_LDFLAGS="-LC:\oracle\instancliente\lib"

In linux and Mac I use code below with any problems
export CGO_CFLAGS=-I/Applications/oracle12/instantclient_11_2
export CGO_LDFLAGS="-L/Applications/oracle12/instantclient_11_2/ -lclntsh"

Thanks

**Comment by tgulacsi** [comment]
https://github.com/mattn/go-oci8 says use a proper oci8.pc with %PKG_CONFIG_PATH%.
But maybe the only missing information is: `CGO_LDFLAGS="-LC:\oracle\instancliente\lib -loci"`
(We went to pkg-config 'cause on Windows the library is called oci, on Linux it is clntsh.Ö

**Comment by alvaradopcesar** [comment]
now I got this

exit status 3221225781

**Comment by tgulacsi** [comment]
See issue #60, copy the output of `go get -x gopkg.in/rana/ora.v3`.

alvaradopcesar <notifications@github.com> ezt írta (időpont: 2016. okt.
17., H 3:25):

**Comment by alvaradopcesar** [comment]
Yes I saw the issue #60 y change mi setup to 

CGO_CFLAGS=-IC:\instantclient_12_1
CGO_LDFLAGS=-LC:\instantclient_12_1\sdk\lib\msvc -loci

C:\Users\cesar>go get -x gopkg.in/rana/ora.v3
WORK=C:\Users\cesar\AppData\Local\Temp\go-build401135178

the same error.

**Comment by tgulacsi** [comment]
Sorry, I don't have a Windows machine at hand.
Please copy the output of `go get -x gopkg.in/rana/ora.v3` _verbatim_ here!
What's the contents of C:\instantclient_12_1\sdk\lib? and
C:\instantclient_12_1\sdk\lib\msvc ?

alvaradopcesar <notifications@github.com> ezt írta (időpont: 2016. okt.
17., H, 14:59):

**Comment by alvaradopcesar** [comment]
C:\Users\cesar\GoProjects\src\bitbucket.org\oracle>go get -x gopkg.in/rana/ora.v3
WORK=C:\Users\cesar\AppData\Local\Temp\go-build533975726

![image](https://cloud.githubusercontent.com/assets/6299951/19454711/d2782f3e-947f-11e6-9879-e8c99ce9582e.png)

![image](https://cloud.githubusercontent.com/assets/6299951/19454721/dd5f2240-947f-11e6-99f9-de3300039312.png)

**Comment by alvaradopcesar** [comment]
![image](https://cloud.githubusercontent.com/assets/6299951/19454732/f288417e-947f-11e6-88d7-8fef562021b9.png)

**Comment by tgulacsi** [comment]
Where is your oci.dll?
The instantclient_12_1 which I've downloaded, contains several files:
```

$ unzip -l /tmp/mozilla_tgulacsi0/instantclient-basiclite-windows.x64-12.1.0.2.0.zip
Archive:  /tmp/mozilla_tgulacsi0/instantclient-basiclite-windows.x64-12.1.0.2.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2014-09-11 09:53   instantclient_12_1/
        0  2014-09-11 09:53   instantclient_12_1/vc12/
   990208  2014-09-11 05:26   instantclient_12_1/vc12/oraocci12.dll
  3322824  2014-09-11 09:53   instantclient_12_1/vc12/oraocci12.sym
  1137664  2014-09-11 05:26   instantclient_12_1/vc12/oraocci12d.dll
  4009032  2014-09-11 09:53   instantclient_12_1/vc12/oraocci12d.sym
        0  2014-09-11 09:53   instantclient_12_1/vc11/
   986624  2014-09-11 04:54   instantclient_12_1/vc11/oraocci12.dll
  3344344  2014-09-11 09:53   instantclient_12_1/vc11/oraocci12.sym
  1150976  2014-09-11 04:54   instantclient_12_1/vc11/oraocci12d.dll
  4169352  2014-09-11 09:53   instantclient_12_1/vc11/oraocci12d.sym
        0  2014-09-11 09:53   instantclient_12_1/vc10/
  1099264  2014-09-11 08:55   instantclient_12_1/vc10/oraocci12.dll
   843632  2014-09-11 09:53   instantclient_12_1/vc10/oraocci12.sym
  1125888  2014-09-11 08:55   instantclient_12_1/vc10/oraocci12d.dll
   945200  2014-09-11 09:53   instantclient_12_1/vc10/oraocci12d.sym
   310784  2014-09-11 09:48   instantclient_12_1/orasql12.dll
    53712  2014-09-11 09:48   instantclient_12_1/orasql12.sym
 61792768  2014-09-11 09:52   instantclient_12_1/oraociicus12.dll
 11191296  2014-09-11 09:52   instantclient_12_1/oraociicus12.sym
  4694528  2014-08-01 14:46   instantclient_12_1/orannzsbb12.dll
   845880  2014-08-01 14:46   instantclient_12_1/orannzsbb12.sym
   641536  2014-09-11 09:49   instantclient_12_1/oci.dll
   473416  2014-09-11 09:49   instantclient_12_1/oci.sym
   508928  2014-09-11 09:25   instantclient_12_1/ociw32.dll
    82136  2014-09-11 09:25   instantclient_12_1/ociw32.sym
  1099264  2014-09-11 08:40   instantclient_12_1/oraocci12.dll
   843632  2014-09-11 09:52   instantclient_12_1/oraocci12.sym
  1125888  2014-09-11 08:55   instantclient_12_1/oraocci12d.dll
   945200  2014-09-11 09:53   instantclient_12_1/oraocci12d.sym
    84480  2014-09-11 09:52   instantclient_12_1/genezi.exe
    51696  2014-09-11 09:52   instantclient_12_1/genezi.sym
    40448  2014-09-11 09:52   instantclient_12_1/adrci.exe
    19672  2014-09-11 09:52   instantclient_12_1/adrci.sym
    40448  2014-09-11 09:52   instantclient_12_1/uidrvci.exe
    19672  2014-09-11 09:52   instantclient_12_1/uidrvci.sym
      591  2014-09-11 09:53   instantclient_12_1/BASIC_LITE_README
   147456  2014-09-02 23:17   instantclient_12_1/ocijdbc12.dll
    29048  2014-09-02 23:17   instantclient_12_1/ocijdbc12.sym
  3692104  2014-08-29 12:14   instantclient_12_1/ojdbc6.jar
  3698892  2014-08-29 12:14   instantclient_12_1/ojdbc7.jar
    71202  2014-09-10 04:46   instantclient_12_1/xstreams.jar
   214528  2014-08-03 20:59   instantclient_12_1/oraons.dll
```

**Comment by alvaradopcesar** [comment]
Lines below all my setup ..

**oci8.pc**
prefix=/devel/target/XXXXXXXXXXXXXXXXXXXXXXXXXX
exec_prefix=${prefix}
libdir=C:/instantclient_12_1
includedir=C:/instantclient_12_1

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Version: 12.1
Description: oci8 library
Libs: -L${libdir} -loci
Cflags: -I${includedir}

--------------------------------------------------
**PATH**
C:\instantclient_12_1;
C:\mingw64\bin;
C:\mingw64\include;

---------------------------------------------------
**Directory of C:\instantclient_12_1**

18-Oct-16  10:50 PM    <DIR>          .
18-Oct-16  10:50 PM    <DIR>          ..
18-Oct-16  03:12 PM             6,148 .DS_Store
11-Sep-14  02:52 AM            40,448 adrci.exe
11-Sep-14  02:52 AM            19,672 adrci.sym
11-Sep-14  02:53 AM               581 BASIC_README
11-Sep-14  02:52 AM            84,480 genezi.exe
11-Sep-14  02:52 AM            51,696 genezi.sym
13-Jan-06  12:36 AM               342 glogin.sql
13-Sep-12  04:33 AM            46,071 ldap.h
10-Sep-14  05:21 PM            37,260 nzerror.h
10-Sep-14  05:21 PM            77,398 nzt.h
15-Oct-02  05:19 AM             2,193 occi.h
23-Aug-13  11:56 AM            12,028 occiAQ.h
10-Apr-13  03:08 AM            36,602 occiCommon.h
14-Sep-12  02:41 AM            74,740 occiControl.h
16-Feb-10  03:50 AM            41,104 occiData.h
29-Oct-07  10:30 PM            25,688 occiObjects.h
11-Sep-14  02:49 AM           641,536 oci.dll
10-Apr-14  02:25 PM           193,157 oci.h
11-Sep-14  02:49 AM           607,302 oci.lib
11-Sep-14  02:49 AM           473,416 oci.sym
25-Sep-05  01:59 PM             7,385 oci1.h
07-Jul-05  06:39 AM            10,678 oci8dp.h
19-Nov-11  12:29 AM           445,636 ociap.h
25-Sep-05  01:58 PM             6,359 ociapr.h
25-Sep-05  02:59 PM            43,887 ocidef.h
07-Jul-05  05:38 AM             4,161 ocidem.h
12-Mar-13  04:17 AM            12,044 ocidfn.h
07-Jul-05  06:38 AM             9,235 ociextp.h
02-Sep-14  04:17 PM           147,456 ocijdbc12.dll
02-Sep-14  04:17 PM            29,048 ocijdbc12.sym
25-Sep-05  01:58 PM             6,659 ocikpr.h
11-Sep-14  02:25 AM           508,928 ociw32.dll
11-Sep-14  02:25 AM            13,826 ociw32.lib
11-Sep-14  02:25 AM            82,136 ociw32.sym
01-Aug-12  12:43 AM             7,830 ocixml.h
15-Jun-14  12:06 AM             8,068 ocixmldb.h
09-Nov-13  12:07 AM           107,285 ocixstream.h
27-May-14  02:05 PM            31,335 odci.h
29-Aug-14  05:14 AM         3,692,104 ojdbc6.jar
29-Aug-14  05:14 AM         3,698,892 ojdbc7.jar
11-Sep-14  02:14 AM            68,096 oramysql12.dll
11-Sep-14  02:14 AM            24,828 oramysql12.lib
11-Sep-14  02:14 AM            34,856 oramysql12.sym
01-Aug-14  07:46 AM         4,694,528 orannzsbb12.dll
01-Aug-14  07:46 AM           845,880 orannzsbb12.sym
11-Sep-14  01:40 AM         1,099,264 oraocci12.dll
11-Sep-14  01:39 AM         2,373,760 oraocci12.lib
11-Sep-14  02:53 AM           843,632 oraocci12.sym
11-Sep-14  01:55 AM         1,125,888 oraocci12d.dll
11-Sep-14  01:54 AM         2,379,150 oraocci12d.lib
11-Sep-14  02:53 AM           945,200 oraocci12d.sym
11-Sep-14  02:52 AM       171,764,736 oraociei12.dll
11-Sep-14  02:52 AM        11,191,216 oraociei12.sym
03-Aug-14  01:59 PM           214,528 oraons.dll
11-Sep-14  02:48 AM           310,784 orasql12.dll
11-Sep-14  02:48 AM            53,712 orasql12.sym
01-Aug-14  08:03 AM         1,561,600 Orasqlplusic12.dll
10-Sep-14  05:21 PM             7,570 oratypes.h
02-Aug-06  12:13 AM           104,870 ori.h
02-Aug-06  12:13 AM            15,456 orid.h
06-May-14  02:08 PM           161,913 orl.h
06-May-14  02:08 PM            43,761 oro.h
08-Jul-11  08:43 PM           126,497 ort.h
01-Aug-14  08:08 AM           941,056 sqlplus.exe
11-Sep-14  02:54 AM           151,608 sqlplus.sym
11-Sep-14  02:54 AM               585 SQLPLUS_README
11-Sep-14  02:52 AM            40,448 uidrvci.exe
11-Sep-14  02:52 AM            19,672 uidrvci.sym
18-Oct-16  10:50 PM             4,061 ver.txt
18-Oct-16  10:50 PM                 0 ver2.txt
05-Sep-06  10:59 PM            10,092 xa.h
09-Sep-14  09:46 PM            71,202 xstreams.jar

---------------------------------------------------------

**C:\Users\cesar\GoProjects\src\bitbucket.org\oracle>go build -x oracle.go**
WORK=C:\Users\cesar\AppData\Local\Temp\go-build684214378
mkdir -p $WORK\command-line-arguments\_obj\
mkdir -p $WORK\command-line-arguments\_obj\exe\
cd C:\Users\cesar\GoProjects\src\bitbucket.org\oracle
"C:\\Users\\cesar\\GO\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378\\command-line-arguments.a" -trimpath "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378" -p main -complete -buildid de58c538c8394f899f2face26502d4e600efe343 -D _/C_/Users/cesar/GoProjects/src/bitbucket.org/oracle -I "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378" -I "C:\\Users\\cesar\\GoProjects\\pkg\\windows_amd64" -pack "C:\\Users\\cesar\\GoProjects\\src\\bitbucket.org\\oracle\\oracle.go"
cd .
"C:\\Users\\cesar\\GO\\pkg\\tool\\windows_amd64\\link.exe" -o "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378\\command-line-arguments\\_obj\\exe\\a.out.exe" -L "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378" -L "C:\\Users\\cesar\\GoProjects\\pkg\\windows_amd64" -extld=gcc -buildmode=exe -buildid=de58c538c8394f899f2face26502d4e600efe343 "C:\\Users\\cesar\\AppData\\Local\\Temp\\go-build684214378\\command-line-arguments.a"
C:\Users\cesar\GO\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -loci
collect2.exe: **error: ld returned 1 exit status**

Thanks a lot for you help

**Comment by tgulacsi** [comment]
Just a half-blind shot, but the `C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe` path is quite strange: as if you have a 64-bit mingw, but building with 32-bit version.
What arch are you on (Windows version)?
What does `go version` print?
What does `go env` print in the same environment where you do `go get`?
Which Oracle InstantClient have you installed?

See http://stackoverflow.com/questions/19345316/ld-exe-cannot-find-lmsvcrt and  https://github.com/derekparker/delve/issues/369 .

From the `\pkg\windows_amd64`, I bet `go version` will print `windows/amd64`.

http://stackoverflow.com/questions/16304804/dual-target-mingw-w64-isnt-really-dual-target suggests that you should add `C:\mingw64\i686-w64-mingw32\lib64` to your path, and not `C:\mingw64\bin`, but I can't check this.

**Comment by alvaradopcesar** [comment]
Window 10 pro 64bits
Go version  go1.7.1 windows/amd64

I am using [https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/]

C:\Users\cesar\GoProjects\src\bitbucket.org\oracle>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\cesar\GoProjects
set GORACE=
set GOROOT=C:\Users\cesar\GO
set GOTOOLDIR=C:\Users\cesar\GO\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\cesar\AppData\Local\Temp\go-build226956906=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

**Oracle version**
instantclient-basic-windows.x64-12.1.0.2.0.zip
instantclient-sdk-windows.x64-12.1.0.2.0.zip
from [( http://www.oracle.com/technetwork/topics/winx64soft-089540.html)]
unzip y copy everything , root and subdirectories on C:\instantclient_12_1

**Comment by IsaacVe** [comment]
![image](https://cloud.githubusercontent.com/assets/17584143/19526416/056d0a48-95ea-11e6-965c-117122ab9cb9.png)

 thanks.

**Comment by alvaradopcesar** [comment]
Thanks a lot ..@tgulacsi everything work fine.!!

**Comment by tgulacsi** [comment]
Then PLEASE share with is what was the problem, and what was the solution?

**Comment by IsaacVe** [comment]
@tgulacsi 
the problem is that we try to liken the installation of the connector ora.v3 variables Mac system to windows environment. example is the following variables:
CGO_CFLAGS = "- IC: \ oracle \ instancliente \"
CGO_LDFLAGS = "- LC: \ oracle \ instancliente \ -lclntsh"
Another problem was that the more hastle, we added more variables and got lost.

Solution:
-follow the step by step according to the article  https://andrey.nering.com.br/2016/connecting-golang-to-oracle-database/.

@alvaradopcesar has the mac system but the company have windows.

**Comment by tgulacsi** [comment]
Thanks!

Isako <notifications@github.com> ezt írta (időpont: 2016. okt. 19., Sze
20:54):
