### ISSUE TITLE
Setting StmtCfg doesn't handle empty strings

### ISSUE THREAD

**Issue by lovromazgon** [rana/ora#125]
I've found out that if I set the StmtCfg the driver throws an error if I want to batch insert rows, where one column is null for all entries.

The example below will throw an _index out of range_ error:

    panic: Stmt.exe.func1 recovered: runtime error: index out of range
    goroutine 1 [running]:
    gopkg.in/rana/ora%2ev3.errR(0xc4200490d0, 0x1, 0x1, 0x0, 0x0)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/util.go:249 +0x82
    gopkg.in/rana/ora%2ev3.(*Stmt).exe.func1(0xc420049b60)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/stmt.go:186 +0x84
    panic(0x560860, 0xc42000c180)
            /usr/local/go/src/runtime/panic.go:458 +0x243
    gopkg.in/rana/ora%2ev3.(*bndStringSlice).bind(0xc420080240, 0xc420014600, 0x4, 0x4, 0x3, 0xc420088180, 0x0, 0x4, 0x0, 0x0)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/bndStringSlice.go:73 +0xc88
    gopkg.in/rana/ora%2ev3.(*Stmt).bind(0xc420088180, 0xc420049f08, 0x3, 0x3, 0x0, 0xc41ffff777, 0xc420049b18, 0x412cee)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/stmt.go:943 +0xa73
    gopkg.in/rana/ora%2ev3.(*Stmt).exe(0xc420088180, 0xc420049f08, 0x3, 0x3, 0xc420049b00, 0x0, 0x0, 0x0, 0x0)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/stmt.go:204 +0x20e
    gopkg.in/rana/ora%2ev3.(*Stmt).Exe(0xc420088180, 0xc420049f08, 0x3, 0x3, 0xc420011100, 0x0, 0x5)
            /home/DEV/go/src/gopkg.in/rana/ora.v3/stmt.go:162 +0x4e
    main.main()
            /home/DEV/go/src/bitbucket.org/lovromazgon/playground/ranaora/ranaora.go:90 +0xbea

but if you change the 10th line to **`ora.SrvCfg{Dblink: sid}`** it will work.

My (very verbose) example:

    func main() {
     // example usage of the ora package driver
     // connect to a server and open a session
     username, password, sid := ora.SplitDSN("dbadmin/dbadmin@DB1")

     env, err := ora.OpenEnv(nil)
     defer env.Close()
     checkErr(err)

     srvCfg := ora.SrvCfg{Dblink: sid, StmtCfg: &ora.StmtCfg{IsAutoCommitting: false}}
     srv, err := env.OpenSrv(&srvCfg)
     checkErr(err)

     sesCfg := ora.SesCfg{
         Username: username,
         Password: password,
     }
     ses, err := srv.OpenSes(&sesCfg)
     checkErr(err)

     stmtTbl, err := ses.Prep(
         `declare
            l_sql varchar2(32767);
            l_cnt pls_integer;
          begin
            l_sql := 'drop TABLE emp_go purge';
            select count(*) into l_cnt from user_tables where table_name='EMP_GO';
            if l_cnt > 0 then
              execute immediate l_sql;
            end if;
          end;`)
     defer stmtTbl.Close()
     checkErr(err)
     rowsAffected, err := stmtTbl.Exe()
     checkErr(err)
     fmt.Println(rowsAffected, " rows Affected. drop table emp_go if exists.")

     rowsAffected, err = ses.PrepAndExe("CREATE TABLE emp_go (empno number(5,0), ename VARCHAR2(50), enil VARCHAR2(12))")
     checkErr(err)
     fmt.Println("table emp_go created")

     rowsAffected, err = ses.PrepAndExe("ALTER SESSION SET TRACEFILE_IDENTIFIER='go1'")
     checkErr(err)

     rowsAffected, err = ses.PrepAndExe("begin dbms_monitor.session_trace_enable( WAITS=>TRUE, binds=>true); end;")
     checkErr(err)

     tx1, err := ses.StartTx()
     stmt, err := ses.Prep("INSERT INTO emp_go (empno, ename, enil) VALUES (:N1, :C1, :C2)")
     defer stmt.Close()
     checkErr(err)
     fmt.Println("Demo bulk/batch insert. Bulk DML with slice (array in Go)")
     l_no := make([]int64, 4)
     l_name := make([]ora.String, 4)
     l_enil := make([]string, 4)
     for n, _ := range l_no {
         l_no[n] = int64(n)
         l_name[n] = ora.String{Value: fmt.Sprintf("Mr. %v", n)}
         l_enil[n] = ""
         fmt.Println(n)
     }
     rowsAffected, err = stmt.Exe(l_no, l_name, l_enil)
     checkErr(err)
     fmt.Println(rowsAffected, " rows add.")
     tx1.Commit()
     fmt.Println("commit")
    }

**Comment by tgulacsi** [comment]
bndStringSlice.go:73 is something else - on master, it is an "} else {", so please update!
For StmtCfg, try to use `ora.NewStmtCfg()` !

**Comment by tgulacsi** [comment]
For my big disappointment, a nil ora.StmtCfg is not usable in its own - you have to start with ora.NewStmtCfg().
This is non-idiomatic Go, but we have to live with it till someone helps us out with a PR :)
