### ISSUE TITLE
go1.8: support for additional features

### ISSUE THREAD

**Issue by kardianos** [rana/ora#127]
Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by tgulacsi** [comment]
Thanks! I've started working on this. 
PTAL on the "go1.8" branch, when it arrives!

**Comment by tgulacsi** [comment]
(Side question: this GH review flow wants forced updates a'la Gerrit, or should I just push new commits after changes?)

Any idea how to implement multiple resultsets? In what constellation does one need such thing?

**Comment by kardianos** [comment]
I typically like to force push changes to branches when I'm updating the same patch.

Against, oracle C interface? Unsure. Can you point me to the docs? I could take a look.

I often use multiple result sets. For instance, I may do a query with an expensive where clause to get a large set of IDs into a temp table, then join that ID list multiple times to different relevant tables (like select * from Invoice where ..., select * from InvoiceItem where ...). That reduces round trips overall. There are almost always ways to work around NOT having them, like with session scoped temp tables, but, then that is another lifespan I need to manage.

**Comment by tgulacsi** [comment]
With Go1.7, you can have a stored procedure with several OUT parameters, each returning an *ora.Rset, each `Scan`-ed into an interface{}. Or have a `SELECT itemID, CURSOR(SELECT * from itemData) FROM items` - an *ora.Rset, where each row contains another *ora.Rset. This can be used directly or `Scan`ing into an interface{}, and casting it to an *ora.Rset.

The first case MAY allow treatment with NextResultSet, but that stored procedure can modify anything, so Exec is more appropriate for it.

The second, as I understand NextResultSet, is absolutely unfeasible with that.


OCI documentation: http://docs.oracle.com/database/121/LNOCI/toc.htm
But gopkg.in/rana/ora.v3 follows that quite closely.

**Comment by tgulacsi** [comment]
BTW will we have to maintain two separate branches? Pre-1.8 and 1.8?
Or can we use some build tag?

**Comment by kardianos** [comment]
I've added a section in the doc. Will need a build tag. Sorry.

**Comment by tgulacsi** [comment]
@kardianos  I've implemented named args in v4, and found some objective: I don't know what to return in NumInput(): if I return the number of placeholders, then sql may complain if less (named) args are present.
So for now I return -1, but I don't think this is a good decision.

Another solution I see, is to parse the query string and count  the different placeholders, and return that number...

**Comment by kardianos** [comment]
I personally think the numinput is a mistake to have. The db system will tell you if you are missing a parameter just fine and for pl/SQL parsing the SQL is non-trivial.  So I personally think what you have is fine.
