### ISSUE TITLE
CLOB, ora.Lob and multiple lines oracle error

### ISSUE THREAD

**Issue by LaGrandMere** [rana/ora#130]
Hi !

I obtain this Oracle error when I try to query CLOBs in a table :
Env.ociErrorNL ORA-24804: Lob read/write functions called while another OCI LOB read/write streaming is in progress

I may have missed something in how to use the Lobs here.
The fact is that I use the Close() function on ora.Lob, but I had a quick look at how the ora.Lob is created, and there's no Closer set before it's returned to me, so Close is unefficient and I think this is why I get my error.

Here is my code :

	func GetTable(db *sql.DB) (res []string, err error) {

	rs, err := db.Query("select CLOB_VAL from CLOB_TABLE")
	if err != nil {
		logger.Error.Printf("SELECT: %v", err)
		return
	}
	defer rs.Close()

	for rs.Next() {
		var Xml ora.Lob
		err = rs.Scan(&Xml)
		if err != nil {
			logger.Error.Printf("Scan: %v", err)
			continue
		}

		s, err := readLob(&Xml)
		if err != nil {
			logger.Error.Printf("readLob: %v", err)
			continue
		}
		res = append(res, strings.TrimSpace(s))
	}
	if rs.Err() != nil {
		err = rs.Err()
		logger.Error.Println(err.Error())
	}

	return
	}

	func readLob(Xml *ora.Lob) (string, error) {
	defer func() {
		if e := Xml.Close(); e != nil {
			logger.Error.Printf("Xml.Close(): %v", e)
		}
	}()
	b, err := Xml.Bytes()
	if err != nil {
		logger.Error.Printf("readLob: %v", err)
		return "", err
	}
	return string(b), nil
}

I finally only get the first line of the table, not all of them.

**Comment by tgulacsi** [comment]
You're very possibly right, I'll try to fix it - till that Scan into an io.ReadCloser, not an ora.Lob.

**Comment by tgulacsi** [comment]
And please, I want your opinion: would it be better to have LOBs be read as string/[]byte by default, and make the current default (io.ReadCloser) the optional?

**Comment by LaGrandMere** [comment]
I think it would indeed be better that by default we get a []byte/string than a ReadCloser.

Even if LOBs theorically would be better handled with a ReadCloser due to memory issues loading the whole of it at once, in fact in my experience in most cases where I've met CLOBs, they were used because there was a little more data than a VARCHAR could handle.

**Comment by LaGrandMere** [comment]
Thanks for your fix, I pulled it and I made it working.
