### ISSUE TITLE
Can not install gopkg.in/rana/ora.v3 on Windows 10 64x

### ISSUE THREAD

**Issue by tdav** [rana/ora#137]
Hello guys!

I have an issue related go get gopkg.in/rana/ora.v3. It doesn't seem to install orav3 when I do the command go get gopkg.in/rana/ora.v3.

I have configured everything as it shown here: https://gist.github.com/mnadel/8678269 .

I have Oracle Instant Client 12.1 and Oracle Instant Client SDK on my Windows 64x.
I have installed 64-bit tdm-gcc to gcc=c:\\gcc64, as well. And have set all the needed Enviroment Path parameters.

These are the values in file oci8.pc:

ora=d:\\Oracle\\instantclient_12_1
gcc=c:\\gcc64
oralib=${ora}\\sdk\\lib\\msvc
orainclude=${ora}\\sdk\\include
gcclib=${gcc}\\lib
gccinclude=${gcc}\\include
Name: OCI
Description: Oracle database engine
Version: 12.1
Libs: -L${oralib} -L${gcclib} -loci
Libs.private: 
Cflags: -I${orainclude} -I${gccinclude}

When I run **pkg-config --cflags oci8** command, I get the following result:
_-Id:\\Oracle\\instantclient_12_1\\sdk\\include -Ic:\\gcc64\\include_

d:\Work_GoLang>go get -x gopkg.in/rana/ora.v3
WORK=D:\tmp\go-build772101478
mkdir -p $WORK\gopkg.in\rana\ora.v3\_obj\
mkdir -p $WORK\gopkg.in\rana\
cd d:\Work_GoLang\src\gopkg.in\rana\ora.v3
pkg-config --cflags oci8
pkg-config --libs oci8
CGO_LDFLAGS="-g" "-O2" "-Ld:\\\\Oracle\\\\instantclient_12_1\\\\sdk\\\\lib\\\\msvc" "-Lc:\\\\gcc64\\\\lib" "-loci" "c:\\go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\" -importpath gopkg.in/rana/ora.v3 -- "-Id:\\\\Oracle\\\\instantclient_12_1\\\\sdk\\\\include" "-Ic:\\\\gcc64\\\\include" -I "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\" bndBfile.go bndBin.go bndBinSlice.go bndBool.go bndBoolPtr.go bndBoolSlice.go bndDate.go bndDatePtr.go bndDateSlice.go bndFloat32.go 
.........
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd d:\Work_GoLang\src\gopkg.in\rana\ora.v3
gcc -I "d:\\Work_GoLang\\src\\gopkg.in\\rana\\ora.v3" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=D:\\tmp\\go-build772101478=/tmp/go-build" -gno-record-gcc-switches "-Id:\\\\Oracle\\\\instantclient_12_1\\\\sdk\\\\include" "-Ic:\\\\gcc64\\\\include" -I "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\" -g -O2 -o 
............

\\tx.cgo2.o" "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\type.cgo2.o" "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\util_arr.cgo2.o" "D:\\tmp\\go-build772101478\\gopkg.in\\rana\\ora.v3\\_obj\\version.o" -g -O2 "-Ld:\\\\Oracle\\\\instantclient_12_1\\\\sdk\\\\lib\\\\msvc" "-Lc:\\\\gcc64\\\\lib" -loci
# gopkg.in/rana/ora.v3
d:\\Oracle\\instantclient_12_1\\sdk\\lib\\msvc/oci.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

Please, help me with my problem.
Thank you

**Comment by tgulacsi** [comment]
Sorry, I don't have any Windows dev machines at hand, so this is just a blind shoot:
I'd try to follow the error message, which says "d:\Oracle\instantclient_12_1\sdk\lib\msvc/oci.lib" is in wrong format - do you have any other oci.lib under somewhere "d:\Oracle\instantclient_12_1\sdk\lib" ?
I guess tdm-gcc needs some other format than msvc.
Or your tdm-gcc64 is not really 64 bit, or your Oracle InstantClient is not 64bit...

**Comment by tdav** [comment]
Oracle Instantclient-basic-windows.x64-12.1.0.2.0
Basic Package Information 
========================= 
Thu Sep 11 02:53:25 CDT 2014
Client Shared Library 64-bit - 12.1.0.2.0


Oracle Instantclient-sdk-windows.x64-12.1.0.2.0
SDK Package Information 
======================= 
Thu Sep 11 02:54:19 CDT 2014
Client Shared Library 64-bit - 12.1.0.2.0


gcc --version
gcc (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\Work_GoLang
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=D:\tmp\go-build808625662=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

**Comment by tdav** [comment]
I have installed the program

**Comment by tgulacsi** [comment]
Strange, I've downloaded the "instantclient-basiclite-windows.x64-12.1.0.2.0.zip" file, and it has only oci.dll, oci.sym under "instantclient_12_1".

Now I see that you used the sdk - but here we only need the InstantClient!

**Comment by tdav** [comment]
but inside there InstantClient include and Lib folders oci.lib

**Comment by tdav** [comment]
you can give the url for InstantClient windows 10 x64
Thank you

**Comment by tgulacsi** [comment]
http://www.oracle.com/technetwork/topics/winx64soft-089540.html

**Comment by tdav** [comment]
> Now I see that you used the sdk - but here we only need the InstantClient!

If I need only the InstantClient, where do I get lib and include folders? The InstantClient does not contain those folders.

**Comment by tgulacsi** [comment]
You're right, the sdk is needed, too.
As `sdk/demo/make.bat` says, -I`sdk/include/` and -L`sdk/lib/msvc -loci` are needed.

**Comment by tgulacsi** [comment]
I've installed cygwin64 with pkg-config, go1.8beta1, git2.1.0 and started the cygwin terminal, and after editing /usr/local/lib/pkgconfig/oci8.pc to have the base point to f:\instantclient_12_1\sdk (my installed InstantClient), then
```
$ go get -v gopkg.in/rana/ora.v4
gopkg.in/rana/ora.v4
# gopkg.in/rana/ora.v4
F:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -loci
collect2.exe: error: ld returned 1 exit status
```

I don't know why does it use the 32bit version...

**Comment by tgulacsi** [comment]
After fixing  the libdir in oci8.pc, I get the same error as reported: `f:/instantclient_12_1/sdk/lib/msvc/oci.lib: error adding symbols: File in wrong format`

**Comment by tgulacsi** [comment]
Ok, found it: change the libdir to have "-L<your_instantclient>" and NOT "-L<your_instantclient>/sdk/lib/msvc"  - point where your oci.dll is!

**Comment by tgulacsi** [comment]
(If that doesn't work, try https://gist.github.com/mnadel/8678269)

**Comment by tdav** [comment]
> Ok, found it: change the libdir to have "-L<your_instantclient>" and NOT 
> "-L<your_instantclient>/sdk/lib/msvc" - point where your oci.dll is!

Installation was successful. Thank you very much for your help.
