### ISSUE TITLE
RowsAffected bug

### ISSUE THREAD

**Issue by goloveychuk** [rana/ora#139]
```golang
func (self Connection) Update(builder dat.Builder) (int, *DbError) {
	text, args := self.compile(builder)
	res, err := self.Db.Exec(text, args...)
	if err != nil {
		if e := checkDbErrors(err); e != nil {
			return 0, e
		}
		logger.Fatal("error while exec query,", "sql", text, "args", args, "err", err)
	}
	affected, err := res.RowsAffected()
	if err != nil {
		logger.Fatal("error in rows affected", "sql", text, "args", args, "err", err)
	}
	return int(affected), nil
}
```
this code sometimes returns `1099511627776,nil` instead of `0, nil`

**Comment by tgulacsi** [comment]
v3 or v4? What does under  -race ?

goloveychuk <notifications@github.com> ezt írta (időpont: 2016. dec. 19., H
11:48):

**Comment by goloveychuk** [comment]
version: v3.7.3
let me try with -race

**Comment by goloveychuk** [comment]
```
DBUG[12-19|13:34:49] execution sql                            module=db sql="UPDATE user_settings SET user_settings.value = :0 WHERE  ( user_settings.user_id = :1 AND user_settings.name = :2 ) " args="[1 21 confirmation_type]"
WARN[12-19|13:34:49] affected                                 module=storage aff=1099511627776
```
any race warnings

**Comment by goloveychuk** [comment]
interesting, this number is 2^40
Maybe this is max number in oracle

**Comment by tgulacsi** [comment]
Is it possible that you use Oracle 11, and not 12? Or your InstantClient is 11, not 12?
I'm asking this 'cause my main suspect is in stmt.exe, where we retrieve OCI_ATTR_(UB8_)ROW_COUNT, we use a fix 8 byte width destination pointer, which may be just 4 bytes, iff the Oracle version is < 12.

Can you try 650347a (current master)?

**Comment by goloveychuk** [comment]
I'm using both oracle and instanclient version == 11.
Didn't know about this incompatibility. Should I use other branch/version for 11xe?

**Comment by goloveychuk** [comment]
let me try

**Comment by tgulacsi** [comment]
It should work both with 11 and 12 - at least that's the intention, so any incompatibility is an error.
But as I use InstantClient 12, there may be some gap for such errors.

**Comment by goloveychuk** [comment]
now I can't reproduce. Before it reproduced randomly.
And fix looks logical so I guess it's resolved properly. Thanks. Could you tag with new version?

**Comment by tgulacsi** [comment]
Done.
