### ISSUE TITLE
Panic during Pool Put

### ISSUE THREAD

**Issue by omerkirk** [rana/ora#141]
```
panic(0x801440, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/rana/ora%2ev3.(*Ses).Close(0xc421176640, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/ses.go:150 +0xc8
gopkg.in/rana/ora%2ev3.sesSrvPB.Close(0xc421176640, 0xc420134740, 0x43e7f5, 0xc442ea16d8)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:198 +0x42
gopkg.in/rana/ora%2ev3.(*sesSrvPB).Close(0xc450405820, 0xc420c7ec00, 0x0)
        <autogenerated>:66 +0x5b
gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1(0xc420134750, 0xc3e8e0, 0xc450405820)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:476 +0x124
created by gopkg.in/rana/ora%2ev3.(*idlePool).Put
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:478 +0xa6
```

I got the above crash during high load in a notification service. I am using the latest release 3.8 along with go 1.7.3 with the default environment settings.

I was using an earlier version where I didn't get this error, but since I've updated it seems I've received this quite a lot when I checked the logs.

**Comment by tgulacsi** [comment]
That's a strange place to have a panic: ses.srv.openSess.remove(ses)
It means that the ses' srv is already closed...

I've uploaded some patch, hope that helps.

Are you using the Pool directly, or through database/sql? Just've surfaced an idea: databas/sql already pools the sessions, maybe that's an error to use a pool in the driver, too...

**Comment by omerkirk** [comment]
I am using it through the database/sql. You might be right, the driver interface already knows about creating, ending and pooling connections, I don't think using another pool is necessary and it might even cause some unexpected issues. 

The version I was using before didn't have pooling in the driver, when I updated the driver to fix ses open close deadlock, I started seeing this panic.

**Comment by tgulacsi** [comment]
I've re-added the idle pool for connections, as `go run z_race.go` slurped up all available Oracle connections - maybe I'd have to tweak db.SetMaxIdleConns & co, I don't know.

**Comment by omerkirk** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x558fd8]

goroutine 895 [running]:
panic(0x8013e0, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/rana/ora%2ev3.(*Ses).Close(0xc4204bd0e0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/ses.go:150 +0xc8
gopkg.in/rana/ora%2ev3.sesSrvPB.Close(0xc4204bd0e0, 0xc4201347c0, 0x43e7f5, 0xc4a8a476d8)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:198 +0x42
gopkg.in/rana/ora%2ev3.(*sesSrvPB).Close(0xc450be4370, 0xc4b531e720, 0x0)
        <autogenerated>:66 +0x5b
gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1(0xc4201347d0, 0xc3e840, 0xc450be4370)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:476 +0x124
created by gopkg.in/rana/ora%2ev3.(*idlePool).Put
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:478 +0xa6
```

Unfortunately the same panic still exists in the latest release. The latest commit is the following in my git log:

```
commit 11ffe9912b05c73a23fcfe122dd9028fdd2cafe7
Author: Tamás Gulácsi <T.Gulacsi@unosoft.hu>
Date:   Thu Dec 22 13:37:46 2016 +0100

    re-add connection pooling for Con, but per-env and not global (_drv)
```

The driver using all available connections is related to MaxIdleConnections setting. If you set it you really shouldn't need any extra pooling for idle connections.

**Comment by tgulacsi** [comment]
Ok, I've removed that pool (v3.8.2).

**Comment by omerkirk** [comment]
Ok. Published into production, will let you know.

**Comment by omerkirk** [comment]
The issue seems to be resolved, 2 days into production and I didn't see any crashes, closing the issue

**Comment by tgulacsi** [comment]
Thanks for your patience and constructive attitude!

omerkirk <notifications@github.com> ezt írta (időpont: 2016. dec. 28., Sze,
9:07):

**Comment by omerkirk** [comment]
We rely heavily on this driver in many of our products, and you did an incredible job with this driver. Thanks for all the hard work and quick responses.

**Comment by rana** [comment]
Thank you for the positive words. Tamas and I have put a lot of effort into
the driver. It's nice to hear someone is getting real value from it
