### ISSUE TITLE
Insert with Returning statement using (:param) doesn't work

### ISSUE THREAD

**Issue by asaf** [rana/ora#146]
Hey,

this code:
```go
q := INSERT INTO PERSON(NAME) VALUES('hello') RETURNING ID INTO :ID
stmt, err := ses.Prep(q)
var id int64
stmt.Exe(&id)
fmt.Println(id) // returns the correct row identity
```

But if query is changed to (ID is enclosed within parentheses):

```sql
INSERT INTO PERSON(NAME) VALUES('hello') RETURNING ID INTO (:ID)
```

it does not work and `id` equals 0

Any reason? I'm trying to use [MapToSlice](https://godoc.org/github.com/tgulacsi/go/orahlp#MapToSlice) which skips params that are not enclosed with parentheses.

Thanks!

**Comment by tgulacsi** [comment]
MapToSlice seems to have a small error - if you append a space to the query string, `INSERT INTO PERSON(NAME) VALUES('hello') RETURNING ID INTO :ID ` works.
But I've fixed it.

Aree you sure `RETURNING INTO (:ID)` is a correct syntax?

**Comment by asaf** [comment]
Thanks, 

Not sure if syntax is supported by Oracle's specs but because of the MapToSlice bug that's what I came with, Oracle XE accept it :-)

Thanks for the patch
