### ISSUE TITLE
Trying to build on osx fails with 'undefined: Stmt'

### ISSUE THREAD

**Issue by asaf** [rana/ora#151]
Hey,

I'm trying to build on OSX with the following command which fails with `undefined: Stmt`

```bash
GOOS=darwin  GOARCH=amd64 CGO_ENABLED=0 go build -o release/darwin/amd64/myapp  bitbucket.org/org/myapp/main
# bitbucket.org/indexia/crossid/vendor/gopkg.in/rana/ora.v3
vendor/gopkg.in/rana/ora.v3/drvStmt.go:18: undefined: Stmt
```

Any clue?

Thanks.

**Comment by tgulacsi** [comment]
CGO_ENABLED=1

cgo is required, we have to link against Oracle's Instant Client libraries...

**Comment by asaf** [comment]
@tgulacsi oops, my bad,

So, due to native Ora libraries, I cannot use OSX and need some Linux image to run the `go build` command for GOOS=linux  GOARCH=amd64 ?

Thanks.

**Comment by tgulacsi** [comment]
Probably yes.
You could try karalabe/xgo, but adding the Oracle libraries is not trivial...

**Comment by asaf** [comment]
Closing,
Thanks for the quick response @tgulacsi
