### ISSUE TITLE
 How to call a stored procedure with any in  parameters and out parameters  using ora ?

### ISSUE THREAD

**Issue by vamkaxifa** [rana/ora#152]
I'v read samples in README.md : 
A string pointer captures an out parameter from a stored procedure:
// given:
// CREATE OR REPLACE PROCEDURE PROC1 (P1 OUT VARCHAR2) AS BEGIN P1 := 'GO'; END PROC1;
var str string
stmt, err = ses.Prep("CALL # PROC1(:1)")
stmt.Exe(&str)
Also  OUT SYS_REFCURSOR . 

But now I'm wondering  how to pass any of in parameters to a stored procedure with ora ?
Can anyone write me a sample or point me where I can refer ? You'd better show the difference between STRING NUMBER TIMESTAMP  and so on, 'cause I'm a new fish to Go.
Thank you very much !

**Comment by tgulacsi** [comment]
You prepare the statement with stmt, err := ses.Prep("BEGIN :1 := myproc(:2, :3, :4); END;`)
Then you execute the statement, giving all the parameters: err = stmt.Exe(&rc, "a", time.Now(), 3.14)

Out parameters must be pointers (otherwise the receiving end cannot modify it), input parameters can be non-pointers.

**Comment by vamkaxifa** [comment]
Thanks for your help, that helps me a lot !
I worked it out by 
`stmtProcCall, err := ses.Prep("CALL " + ProduceName + "(:1,:2)")  
 var int_ int16  
 stmtProcCall.Exe(3.14, &int_)` 

But here comes another one question :
In my project , I need to write a common method which can handle all kinds of stored  produces having different quantity of in parameters and also out parameters . In this condition , how should I format `ses.Prep()` ?   `Prep`'s parameters seems need to be done in a specific quantity ?

**Comment by tgulacsi** [comment]
As https://godoc.org/gopkg.in/rana/ora.v4#Stmt shows, Stmt.Exe receives
variable number of arguments, so

args := []interface{}{"always needed param"}
args = append(args, -3)

stmt.Exe(args...)

will call the prepared statement with the previously assembled arguments
slice.

(You can use the user_arguments view in the database to select the args for
all the procedures/functions!
I'm using this source of truth in my Oracle Go call generator,
github.com/tgulacsi/oracall for generating a gRPC server to call stored
procedures remotely).

vamkaxifa <notifications@github.com> ezt írta (időpont: 2017. febr. 9., Cs,
3:24):

**Comment by vamkaxifa** [comment]
That's very kind of you! this helps me a lot !
