### ISSUE TITLE
Oracle XMLType

### ISSUE THREAD

**Issue by edsono** [rana/ora#153]
I am trying to UPDATE an XMLType column in Oracle. The problem is:

ORA-01461: can bind a LONG value only for insert into a LONG column

After a research in the Internet, a lot of answers pointed to force parameter to be a CLOB type. Is there any way that I can force my parameter to CLOB instead of LONG in ora package?

Thanks for the good work!

**Comment by tgulacsi** [comment]
Have you tried SELECTing "field.getClobVal"?

Edson César <notifications@github.com> ezt írta (időpont: 2017. febr. 16.,
Cs 14:12):

**Comment by edsono** [comment]
Sorry I didn't understood your suggestion. Let me show some code:

`
    _, err = db.Exec(`
      UPDATE my_table
      SET my_xmltype_field =  :1
      WHERE id = 999     
    `, string(xml))
` 

Where xml is an []byte and the column my_xmltype_field is declared as SYS.XMLType in Oracle. Is there anyway that I can choose the parameter binding as CLOB?

**Comment by tgulacsi** [comment]
Check out ExampleWriteLOB in z_example_test.go

**Comment by edsono** [comment]
Thanks @tgulacsi !
With this example, I solved my issue.
