### ISSUE TITLE
Problems with clob columns that are null

### ISSUE THREAD

**Issue by tkandal** [rana/ora#156]
Does anybody else experience troubles with null in clob-columns?

It seems to me that the driver is working perfectly with all other types and
when there are values in the clobs.
When i hit clob-columns wih null, the drivers seems to hang for å long while and then crash with the error-message "index out of bounds".
I am using ora.OraS in the prepare-statement and ora.String as Go-types, Go v. 1.8 and Oracle Client Shared Library 64-bit - 12.1.0.2.0 on macOS 10.12.3

**Comment by tgulacsi** [comment]
Can you provide a minimal test case? That would help the fix!


Trond Kandal <notifications@github.com> ezt írta (időpont: 2017. febr. 19.,
V, 18:16):

**Comment by tkandal** [comment]
The Go code is no problem, and I can give a description of the database-tables.  The database is a legacy database and protected.  :) Where do You want the Go code?

**Comment by tgulacsi** [comment]
here :)

I need only the CREATE TABLE, the INSERT for one record, and the code of
select which reproduces the problem.

Trond Kandal <notifications@github.com> ezt írta (időpont: 2017. febr. 20.,
H, 12:26):

**Comment by tkandal** [comment]
CREATE TABLE "TIASTAGE"."TIA_EMNEINFO" 
   (	"INSTITUSJONSNR" NUMBER(8,0) NOT NULL ENABLE, 
	"EMNEKODE" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"VERSJONSKODE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"INFOTYPEKODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"SPRAKKODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"TERMINKODE_FRA" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"ARSTALL_FRA" NUMBER(4,0) NOT NULL ENABLE, 
	"TERMINKODE_TIL" VARCHAR2(4 CHAR), 
	"ARSTALL_TIL" NUMBER(4,0), 
	"INFOTEKST" CLOB, 
	"INFOTEKST_ORIGINAL" CLOB, 
	"INSTITUSJONSNR_EIER" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "TIA_EMNEINFO_PK" PRIMARY KEY ("INSTITUSJONSNR", "EMNEKODE", "VERSJONSKODE", "INFOTYPEKODE", "SPRAKKODE", "TERMINKODE_FRA", "ARSTALL_FRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TIASTAGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TIASTAGE" 
 LOB ("INFOTEKST") STORE AS BASICFILE (
  TABLESPACE "TIASTAGE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INFOTEKST_ORIGINAL") STORE AS BASICFILE (
  TABLESPACE "TIASTAGE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

**Comment by tkandal** [comment]
type EmneInfo struct {
	InstitusjonsNr     ora.Int64  `json:"institusjonsnr"`
	EmneKode           ora.String `json:"emnekode"`
	VersjonsKode       ora.String `json:"versjonskode"`
	InfoTypeKode       ora.String `json:"infotypekode"`
	SprakKode          ora.String `json:"sprakkode"`
	TerminKodeFra      ora.String `json:"terminkode_fra"`
	ArstallFra         ora.Int64  `json:"arstall_fra"`
	TerminKodeTil      ora.String `json:"terminkode_til"`
	ArstallTil         ora.Int64  `json:"arstall_til"`
	InfoTekst          ora.String `json:"infotekst"`
	InfoTekstOriginal  ora.String `json:"infotekst_original"`
	InstitusjonsNrEier ora.Int64  `json:"institusjonsnr_eier"`
}

var sqlQuery string = "SELECT * FROM TIA_EMNEINFO"
stmt, err := ses.Prep(sqlQuery, ora.OraI64, ora.OraS, ora.OraS, ora.OraS, ora.OraS, ora.OraS,
		ora.OraI64, ora.OraS, ora.OraI64, ora.OraS, ora.OraS, ora.OraI64)
	defer stmt.Close()
	if err != nil {
		log.Printf("Prepare statement failed; error = %s\n", err.Error())
		w.WriteHeader(500)
		json.NewEncoder(w).Encode(JsonError{"Internal error"})
		return
	}

	rst, err := stmt.Qry()
	if err != nil {
		log.Printf("Execute failed; error = %s\n", err.Error())
		w.WriteHeader(500)
		json.NewEncoder(w).Encode(JsonError{"Internal error"})
		return
	}

	results := make([]EmneInfo, 0)
	for rst.Next() {
		results = append(results, EmneInfo{rst.Row[0].(ora.Int64), rst.Row[1].(ora.String),
			rst.Row[2].(ora.String), rst.Row[3].(ora.String), rst.Row[4].(ora.String),
			rst.Row[5].(ora.String), rst.Row[6].(ora.Int64),
			rst.Row[7].(ora.String), rst.Row[8].(ora.Int64), rst.Row[9].(ora.String),
			rst.Row[10].(ora.String), rst.Row[11].(ora.Int64)})
	}

**Comment by tgulacsi** [comment]
```
index 850d84b..05ad2b8 100644
--- a/defLob.go
+++ b/defLob.go
@@ -242,7 +242,7 @@ func (lr *lobReader) Close() error {

 // Read into p, the next chunk.
 func (lr *lobReader) Read(p []byte) (n int, err error) {
-       if lr.ociLobLocator == nil {
+       if lr.ociLobLocator == nil || lr.Length == 0 {
                return 0, io.EOF
        }
        defer func() {
```

It's on v4.

**Comment by tkandal** [comment]
You have already patched the code? ;)

**Comment by tgulacsi** [comment]
The symptoms said "infinite loop", and you dogged on and presented nice informative description, even provided a test case, so I felt this should be rewarded by an instant fix :)

So I've expanded the already existing TestLOBRead with an empty case, and in the infinite loop hit Ctrl+\ and saw it's stuck in defLob with OCILobRead2. 
So added the length check and this fixed the test case, so profit.

**Comment by tkandal** [comment]
Thank You very much, Sir! :) Very good work!

**Comment by tkandal** [comment]
Excuse me, Sir

Still have the same problem.  Am I doing something wrong?
I have changed the type to:
titusjonsNr ora.Int64 json:"institusjonsnr"
EmneKode ora.String json:"emnekode"
VersjonsKode ora.String json:"versjonskode"
InfoTypeKode ora.String json:"infotypekode"
SprakKode ora.String json:"sprakkode"
TerminKodeFra ora.String json:"terminkode_fra"
ArstallFra ora.Int64 json:"arstall_fra"
TerminKodeTil ora.String json:"terminkode_til"
ArstallTil ora.Int64 json:"arstall_til"
InfoTekst ora.Lob json:"infotekst"
InfoTekstOriginal ora.Lob json:"infotekst_original"
InstitusjonsNrEier ora.Int64 json:"institusjonsnr_eier"
}

Prepare with:
stmt, err := ses.Prep(sqlQuery, ora.OraI64, ora.OraS, ora.OraS, ora.OraS, ora.OraS, ora.OraS,
		ora.OraI64, ora.OraS, ora.OraI64, ora.OraS, ora.OraS, ora.OraI64)

And get with:
rst, err := stmt.Qry()
results := make([]EmneInfo, 0)
	for rst.Next() {
		results = append(results, EmneInfo{rst.Row[0].(ora.Int64), rst.Row[1].(ora.String),
			rst.Row[2].(ora.String), rst.Row[3].(ora.String), rst.Row[4].(ora.String),
			rst.Row[5].(ora.String), rst.Row[6].(ora.Int64),
			rst.Row[7].(ora.String), rst.Row[8].(ora.Int64), rst.Row[9].(ora.Lob),
			rst.Row[10].(ora.Lob), rst.Row[11].(ora.Int64)})
	}

Does the prepare make troubles since I use ora.OraS for clobs?

**Comment by tgulacsi** [comment]
```
cd $GOPATH/src/gopkg.in/rana/ora.v4
git checkout -f master
git pull
```
then please modify TestLobSelectString or add a new test case which reproduces your problem!

I admit I haven't tested your exact case yet, I'll try it later.

**Comment by SamBerk** [comment]
PLEASE DELETE ME FROM THIS THREAD, I AM NOT SURE HOW I GOT HERE

**Comment by tgulacsi** [comment]
The easiest way is clicking on the "mute the thread" link at the bottom of
the email.
Otherwise, click on "unsubscribe" at github.com/rana/ora

SamBerk <notifications@github.com> ezt írta (időpont: 2017. febr. 20., H,
16:14):

**Comment by tgulacsi** [comment]
Check out z_lob_test.go, TestLobIssue156 (v4 branch), and
1. use ora.D in Prep if you want to receive Lob (and ora.S for string),
2. ensure that ses.`Cfg().Clob == ora.D` (use `ses.SetCfg(ses.Cfg().SetClob(ora.D))`)

Sorry for the second point, `D` is the default value, in which case the general config is used.
Maybe if we'd have a L (Lob) type, that'd made things easier, I don't know.

**Comment by tkandal** [comment]
Thank You, Sir!
My program does not crash with the latest fix, if I use ses.SetCfg(ses.Cfg().SetClob(ora.D)), ora.D in Prep and ora.Lob in the type,- but I  cannot marshal my object to JSON and I need that.

If I use ses.SetCfg(ses.Cfg().SetClob(ora.D)), ora.S in the Prep and string in type, the whole program crashes with index out of range.

Have I misunderstood something?

**Comment by tgulacsi** [comment]
I've pushed v4.0.1 with ora.L as a Lob column type.
Check out TestLobIssue156 in z_lob_test.go.

If still panics, please post the code and the full stack trace!

**Comment by tkandal** [comment]
Thank You again, Sir!

I have done as You advised.

I have removed:
ses.SetCfg(ses.Cfg().SetClob(ora.D))

Use ora.L in the Prep and ora.Lob in type

When I marshal to JSON, I get:
...
{
    "institusjonsnr": 194,
    "emnekode": "TBBY3001",
    "versjonskode": "A",
    "infotypekode": "E-URL",
    "sprakkode": "BOKMÅL",
    "terminkode_fra": "HØST",
    "arstall_fra": 2017,
    "terminkode_til": null,
    "arstall_til": null,
    "infotekst": {
      "Reader": {
        "Length": 31
      },
      "Closer": null,
      "C": false
    },
    "infotekst_original": {
      "Reader": null,
      "Closer": null,
      "C": false
    },
    "institusjonsnr_eier": 194
  }
...

What is not quite what I expected.  ;)

**Comment by tgulacsi** [comment]
There is a MarshalJSON/UnmarshalJSON defined on *Lob, but that's not Lob.
Please re-download 4.0.1

Trond Kandal <notifications@github.com> ezt írta (időpont: 2017. febr. 22.,
Sze, 20:43):

**Comment by tkandal** [comment]
Thank You very much, Sir! It works like charm!  I very much appreciate your work and help!
