### ISSUE TITLE
How to build for linux on mac?

### ISSUE THREAD

**Issue by vamkaxifa** [rana/ora#157]
As title says, how to build for linux on mac ?
On my mac , I can built for mac it's self successfully , But when I built for linux on mac , I get errors
as blow :
```
$ go version
go version go1.7.4 darwin/amd64
$ GOOS=linux GOARCH=amd64 go build main.go 
# gopkg.in/rana/ora.v3
../../../gopkg.in/rana/ora.v3/drvStmt.go:18: undefined: Stmt 
$ GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build main.go 
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tgulacsi** [comment]
I think its not possible. Or at least very-very hard: you'd need a cross-compiling gcc toolchain for cgo.

**Comment by vamkaxifa** [comment]
well...
I moved my project to linux together with all dependencies, I got error again:
```
$ go run main.go 
# gopkg.in/rana/ora.v3
../../../gopkg.in/rana/ora.v3/bndBfile.go:9:17: error: oci.h: No such file or directory
In file included from ../../../gopkg.in/rana/ora.v3/bndBfile.go:10:
./version.h:21:2: error: #error Unsupported version of OCI.
```
 Instant Client version is 11.2 (Instant Client Package - Basic: All files required to run OCI, OCCI, and JDBC-OCI applications)

**Comment by tgulacsi** [comment]
It cannot find oci.h.
Copy contrib/oci8.pc under $PKG_CONFIG_DIR and check that "pkg-config --libs --cflags"  finds it.

**Comment by vamkaxifa** [comment]
Well I fixed oci.h problem , then I got this:
```
$ go run main.go 
# gopkg.in/rana/ora.v3
/usr/bin/ld: cannot find -lclntsh
collect2: ld returned 1 exit status
$ gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-48)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

``` 
Is there possible that my gcc version is too low ? I don't understand how this comes out .

**Comment by tgulacsi** [comment]
Modify `oci8.pc` as needed, to force pkg-config to show the right directories!
For me `find /usr/  -name 'libclntsh*.so'` says `/usr/lib/oracle/12.1/client64/lib/libclntsh.so`, 
thus `pkg-config --libs oci8` must say `-L/usr/lib/oracle/12.1/client64/lib -lclntsh`.

`find /usr/  -name 'oci.h'` says `/usr/include/oracle/12.1/client64/oci.h` and
`pkg-config --cflags oci8` must say `-I/usr/include/oracle/12.1/client64`.

**Comment by vamkaxifa** [comment]
I made a simple link ` ln -s libclntsh.so.12.1 libclntsh.so` and this solved that problem.
Here comes this 
```
$ pkg-config --libs oci8
-L/home/was/software/instantclient_12_1 -lclntsh  
$ pkg-config --cflags oci8
-I/home/was/software/instantclient_12_1/sdk/include  
$ go build main.go 
# gopkg.in/rana/ora.v3
/usr/bin/ld: unrecognized option '--build-id=none'
/usr/bin/ld: use the --help option for usage information
collect2: ld returned 1 exit status

```
The `oci.h` is exactly here in `/home/was/software/instantclient_12_1/sdk/include`

My `oci8.pc` comes:
```
prefixdir=/home/was/software/instantclient_12_1
libdir=${prefixdir}
includedir=${prefixdir}/sdk/include

Name: oci8
Description: Oracle database driver
Version: 12.1
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}
```

**Comment by vamkaxifa** [comment]
Hi, It turned out that my gcc version is too low.
