### ISSUE TITLE
sql: Scan error on column index 0: converting driver.Value type float64 to int

### ISSUE THREAD

**Issue by gngon** [rana/ora#158]
Hi,
I have this error when trying to scan a row of my table with v4 branche (**no error with master**) : 
**sql: Scan error on column index 0: converting driver.Value type float64 ("1.9562687e+07") to a int: invalid syntax**

Here is the source code :

`for rows.Next() {
	var pdlid int
	err = rows.Scan(&pdlid)
	if err != nil {
		log.Error(err)
		return
	}`

Here is  my table:

![image](https://cloud.githubusercontent.com/assets/25921979/23155628/c3ef9d4c-f813-11e6-8fa8-eda38ff7e8bc.png)

COLUMN_NAME : PDL_ID  
DATA_TYPE : NUMBER

I do not have this error with other tables having fields of the same type. and i do not have this error with master.

It looks like when the value of the field increases and reaches a certain number, the driver returns this value as float instead of int.

Remain yours for all other precision.

Thanks and regards

**Comment by tgulacsi** [comment]
I assume pdlid is an int var.
A NUMBER column can hold 38 decimals, so even a float64 is limited, but I think the safest choice.
If the column is restricted (NUMBER(18) for example) it will go into an int64 by default.

You can explicitly set the used column type with
`ora.SetCfg(ora.Cfg().SetNumberBigFloat(ora.I64).SetNumberBigInt(ora.I64))`

**Comment by gngon** [comment]
Sorry, I was unavailable for a while. I will try both solutions and keep younposted.
Thank you very much for your quick answer.
Best regards

**Comment by gngon** [comment]
Hi,
ora.SetCfg(ora.Cfg().SetNumberBigFloat(ora.I64).SetNumberBigInt(ora.I64)) not working.

Doing several tests, i see that  only ora.SetCfg(ora.SetCfg(ora.Cfg()..SetNumberFloat(ora.OraI64).SetNumberBigFloat(ora.OraI64))  manage to explicitly set the of a column type float as column type int (sql: Scan error on column index 3: converting driver.Value type ora.Int64 ("16") to a float64: invalid syntax)
But ora.SetCfg(ora.Cfg().SetNumberInt(ora.OraI64).SetNumberBigInt(ora.OraI64)) nor ora.SetCfg(ora.Cfg().SetNumberInt(ora.I64).SetNumberBigInt(ora.I64)) manage to explicitly set the of a column type number as column type int.
Regards.

**Comment by tgulacsi** [comment]
I'd try ora.v4 - the config settings in ora.v3 are quite hectic, that's one of the main refactorings and changes in v4.

If you use ora through database/sql, then the switch to ora.v4 will have no ill effect.
If you use ora directly, then in ses.Prep and Qry you can specify the wanted column types.

**Comment by gngon** [comment]
Thank you.
