### ISSUE TITLE
nullable strings are set to empty string when null

### ISSUE THREAD

**Issue by volkmarbuehringer** [rana/ora#164]
with the postgres driver I can define *string as type in the structure and get a null-pointer,
if the data is null in the database

with the oracle-driver I get an empty string

but for int and float types I get a null pointer if I define *int or *float64 in the structure

is there a way to change this behavior for null values in varchar2 columns ?

**Comment by tgulacsi** [comment]
As Oracle DB does not differentiate '' and NULL, we have to decide how to treat the empty string: as an empty string or a NULL. As nil may need a check, returning an empty string seemed forgivable.
