### ISSUE TITLE
cannot use nil as type ora.DrvCfg in argument to ora.Register

### ISSUE THREAD

**Issue by jeromepeirick** [rana/ora#172]
I see this error when I try "go build" and import gopkg.in/rana/ora.v4.  No error when I do the same with gopkg.in/rana/ora.v3.

ora.Register(nil) has worked without incident using v3 for months.  Any ideas?

**Comment by tgulacsi** [comment]
Yes. ora.v4 is a different version, with a few backward-incompatible changes.
You don't need Register anymore.

**Comment by jeromepeirick** [comment]
Thanks for the help.  All squared away.
