### ISSUE TITLE
Unable to create environment handle (Return code = -1).

### ISSUE THREAD

**Issue by 5k3105** [rana/ora#174]
```panic: OpenEnv: ora.go:164:gopkg.in/rana/ora%2ev4.OpenEnv Unable to create environment handle (Return code = -1).```

Windows 7. Built using MSYS2. 

Here is the code, but it doesn't seem to matter what code I use:
```
package main

import (
	"fmt"
        "database/sql"
	"time"
	"context"
    ora "gopkg.in/rana/ora.v4"
)

const dbc = `usr/pwd@host:port/servicename`

func main() {

    db, err := sql.Open("ora", dbc)
    
    defer db.Close()
	check(err)
	
    // Set timeout (Go 1.8)
    ctx, err := context.WithTimeout(context.Background(), 5*time.Second)
    check(err)
    
    // Set prefetch count (Go 1.8)
    ctx = ora.WithStmtCfg(ctx, ora.Cfg().StmtCfg) //.SetPrefetchCount(50000))
    rows, err := db.QueryContext(ctx, "SELECT * FROM tablename")
    check(err)
    
    defer rows.Close()
    
    col, err := rows.Columns()
    check(err)

    
    fmt.Println(col)

}

func check(err error) {
    if err != nil {
		fmt.Println(err)
		}	
	}
```

**Comment by 5k3105** [comment]
Oh wait:

```
The ora package has been verified to work with:

Oracle Standard 11g (11.2.0.4.0), Linux x86_64 (RHEL6)

Oracle Enterprise 12c (12.1.0.1.0), Windows 8.1 and AMD64.
```

Both of these are 'pay for' versions correct?

**Comment by tgulacsi** [comment]
What do you mean by 'pay for'?
I don't know any free Oracle version - XE is a joke (but I use XE 11.2 it
for testing).

5k3105 <notifications@github.com> ezt írta (időpont: 2017. márc. 16., Cs
19:46):

**Comment by 5k3105** [comment]
Well, I am trying to find a way to connect to an oracle db to write rows. I assumed an odbc library would not require me to pay since odbc means 'Open' database connectivity.

**Comment by tgulacsi** [comment]
You don't have to pay, just download "Oracle Instant Client".

5k3105 <notifications@github.com> ezt írta (időpont: 2017. márc. 16., Cs
20:19):

**Comment by 5k3105** [comment]
Ok. Thanks. That's what I did. I thought I would need the other stuff just to get it to work.

Thanks for clearing that up.

I believe I've installed it correctly, but I get the error mentioned.

**Comment by 5k3105** [comment]
Never worked. Just writing a java app for it.

**Comment by chris-gpc** [comment]
I had the same issue in Linux; found that libociei.so was not in my path; not sure if this helps you or not.
