### ISSUE TITLE
Does ora support DRCP?

### ISSUE THREAD

**Issue by vamkaxifa** [rana/ora#178]
As titled ,does ora support [DRCP(Database Resident Connection Pooling)](http://www.oracle.com/technetwork/articles/oracledrcp11g-1-133381.pdf) ? 
In my project, I need to specify the server type as POOLED via the connect string as shown below:
```
dsn := "my_oracle_host:1521/orcl/POOLED"
#dsn1 := "my_oracle_host:1521/orcl/sales:POOLED"
srvCfg := ora.SrvCfg{Dblink: dsn}
srv, err := env.OpenSrv(srvCfg)
if err != nil {
 log.Fatal("env.OpenSrv(srvCfg) occurs error:", err)
}
sesCfg := ora.SesCfg{Username: av.UserName,Password: av.Password}
sespool := srv.NewSesPool(sesCfg, size)
```
But this doesn't work. I got this error:
```
env.OpenSrv(srvCfg) occurs error:Env.OpenSrv Env.ociError ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
```
No matter use `dsn` or use `dsn1`, the error remains the same.
Someone show me how ?

**Comment by tgulacsi** [comment]
I don't understand this "my_oracle_host:1521/orcl/POOLED" as a connection
string - neither does OCI.

Please use the string returned by "tnsping
your-desired-db-sid-as-your-tnsnames-ora-understands", that lispy thing.



Nancy <notifications@github.com> ezt írta (időpont: 2017. márc. 27., H,
10:16):

**Comment by vamkaxifa** [comment]
Oh no, `my_oracle_host` just a alias for my database ip. 
Actually I used "172.20.5.7:1521/orcl/sales:POOLED" as a connection string. 
In my earlier code, I used "172.20.5.7:1521/orcl/", this works, but when I use the SQL `select username, server from v$session where username is not null;` , I found that my server type is DEDICATED, This is not I wanted, I need to  specify the server type as POOLED . According [DRCP(Database Resident Connection Pooling)](http://www.oracle.com/technetwork/articles/oracledrcp11g-1-133381.pdf),In this article, it shows that I can specify the server type as POOLED via the connect string as "myhost.dom.com:1521/sales:POOLED".  So I came up this  connection string :"172.20.5.7:1521/orcl/sales:POOLED", but is seems not right.

**Comment by tgulacsi** [comment]
That's why I suggest you to use tnsping to get the canonical connection
string, and use that.

Nancy <notifications@github.com> ezt írta (időpont: 2017. márc. 27., H,
10:33):

**Comment by tgulacsi** [comment]
See "Page 4" in the linked article.

**Comment by tgulacsi** [comment]
But we don't have OCISessionPoolCreate yet.
Any suggestion about how to mark that you want such a pooled connection and not a normal?

**Comment by tgulacsi** [comment]
Hmm. I need to OCIConnectionPoolCreate + OCIServerAttach + OCISessionBegin and must propagate the pool name throughout
OR just use OCIConnectionPoolCreate + OCISessionGet.

But the latter skips OCIServer altogether, so we should skip Srv too, merge SrvCfg to SesCfg.
Big undertaking, but maybe simplifies a lot of code, and the usage, too.
But this indicates ora.v5 ...

**Comment by tgulacsi** [comment]
Why do you want DRCPool?
As I understand, that's a DB-side poor man's connection pool - I say it's inferior, because you have to create the TCP connection and authenticate anyway. It may help only for short lived processes - but you use a Go server, don't you?

A client-side connection pool is waaay more effective. And we have one right at hand: ora.Pool.

**Comment by vamkaxifa** [comment]
I know what you mean, and yes we use a Go server. 
In the actual production environment, we have thousands of client-side applications, and the quantity of applications is growing fast. If each client-side application use a connection pool,that would be a disaster because the DB connection resource is limited. However, ora.Pool use default server type DEDICATED, this specify DB sever to run each connection as DEDICATED which is quite a wast of connection resource. To handle thousands of client-side applications cooperating with Oracle DB efficiently, we need to specify the server type as POOLED, this lead DB server allowing for sharing the pooled servers across different instances of the same application,which saves a lot.

**Comment by vamkaxifa** [comment]
Hum, ora doesn't have to provide DRCPool like `SesPool` 、`SrvPool` or `Pool`, just provide a way to let user tell DB Server run each connection as POOLED, this would be fine. I thought, maybe you can start with `ora.SplitDSN(dsn string)`.

**Comment by tgulacsi** [comment]
@Nany, that doesn't that simple: now we use ServerAttach + SessionBegin +
SessionEnd, for DRCPool we need SessionPoolCreate + SessionGet +
SessionRelease, as DRCPool is a hacked seasionpool under the hood.

But the end will be SplitDSN :)

Nancy <notifications@github.com> ezt írta (időpont: 2017. márc. 29., Sze
3:55):

**Comment by tgulacsi** [comment]
@vamkaxifa You could test the "cpool" branch.

And it would be great if I could test some DRCPool, too!
Is it possible with Oracle XE? Can you give me the exact steps needed to create a DRCPool on an XE db?

**Comment by tgulacsi** [comment]
@vamkaxifa Eventually I could test with DRCPool, fixed a few small errors, now all tests pass!

**Comment by vamkaxifa** [comment]
That's fantastic ! Maybe I'll have a try if I got time !
