### ISSUE TITLE
OCINumberToFloat question

### ISSUE THREAD

**Issue by vsdutka** [rana/ora#181]
When i run this code, V0 does not equal V1:

        var v0 float64 = 123456789.0123456789
	var v1 float64
	_, err = ses.PrepAndExe("begin :1 := 123456789.0123456789; end;", &v1)
	if err != nil {
		fmt.Print("1 - ", err)
		return
	}

	fmt.Println("v0 = ", v0)
	fmt.Println("v1 = ", v1)
	fmt.Printf("v0 internal: %064s\n", strconv.FormatUint((*(*uint64)(unsafe.Pointer(&v0))), 2))
	fmt.Printf("v1 internal: %064s\n", strconv.FormatUint((*(*uint64)(unsafe.Pointer(&v1))), 2))

result:

v0 =  1.2345678901234567e+08
v1 =  1.23456789012346e+08
v0 internal: 0100000110011101011011110011010001010100000011001010010001011000
v1 internal: 0100000110011101011011110011010001010100000011001010010001101110

**Comment by tgulacsi** [comment]
float64 cannot represent 123456789.0123456789, see https://play.golang.org/p/CFR3oTP3OA
Use ora.Num if you want bigger precision, to get a string without losses.
Or ora.OCINum, but that may need some coding...

**Comment by vsdutka** [comment]
Thank you fo fast fix.
But how I can use ora.OCINum as output bind param?

**Comment by tgulacsi** [comment]
You can use ora.Num, which is a string. Or you can try the current master (08dd0cd).
