### ISSUE TITLE
panic on interrupt

### ISSUE THREAD

**Issue by pierrec** [rana/ora#189]
Hello,

Following the thread on [golang-nuts:](https://groups.google.com/d/msg/golang-nuts/wyIaW5pcfqY/GXqN2JPRAAAJ)
whenever I send an interrupt signal to a go process running an Oracle query, it panics with either "fatal: morestack on g0" or "fatal error: runtime: stack split at bad time".

A sample code reproducing the issue is [here](https://play.golang.org/p/f-XBPwNlqG).

This is with go version go1.8.1 darwin/amd64.

**Comment by tgulacsi** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/wyIaW5pcfqY

Can you try the suggested solution (
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_ADR_ENABLED=FALSE
DIAG_DDE_ENABLED=FALSE

in tnsnames.ora)

**Comment by tgulacsi** [comment]
See

http://stackoverflow.com/questions/28449276/what-is-the-reason-for-core-dump-stack-shows-from-oracle-lib

https://www.ca.com/us/services-support/ca-support/ca-support-online/knowledge-base-articles.tec555270.html
