### ISSUE TITLE
[Enhancement] for associative arrays parameters in store procedures

### ISSUE THREAD

**Issue by jmptrader** [rana/ora#19]
Dear,

Great and very cool package.

Your library will support Associative Arrays for store procedures. 

In my case, I have many procedures like this:

CREATE OR REPLACE PACKAGE testuser.test_pkg IS

   TYPE assoc_array_varchar2_t IS TABLE OF VARCHAR2(4000) INDEX BY BINARY_INTEGER;

   PROCEDURE your_proc(p_parm IN assoc_array_varchar2_t);

END test_pkg;

CREATE OR REPLACE PACKAGE BODY testuser.test_pkg IS

   PROCEDURE your_proc(p_parm IN assoc_array_varchar2_t) AS
   BEGIN
      FOR i IN p_parm.first .. p_parm.last
      LOOP
         dbms_output.put_line(p_parm(i));
      END LOOP;

   END;

END test_pkg;

**Comment by tgulacsi** [comment]
Ain't this supported by using []string parameters?
```ses.PrepAndExe("BEGIN your_proc(:p_parm); END;", []string{"first", "second"})```

**Comment by rana** [comment]
Yes, would be nice.

Thank you @jmptrader. Will add to the to-do list. As you noted, associative arrays aren't yet supported.

@tgulacsi []string to VARCHAR2 is supported for regular tables but not associative arrays or varrays.

**Comment by jmptrader** [comment]
Thank for your attention. 

An subquestion::The creation of new oratype binding support, What parts are affected in your library ?
+++ the Bnd*.go files the most obvious  .... :) +++

***bold italic***

**Comment by rana** [comment]
Hola Jorge,

bndColl.go might be written to focus on binding go slices to in-bound Oracle associative arrays. There are a couple fun challenges with binding associative arrays.

1. Determine what the associative array definition is at runtime. Each package may have a different associative array type definition. Determine how to lookup the oracle package definition. Parse the oracle package associative array definition. Determine which go-type maps to which oracle associative array type. Start with one working example, VARCHAR2(4000) INDEX BY BINARY_INTEGER.

2. Make a call to the appropriate OCI function to bind the go values. What is the appropriate call? I don't know. You would have to determine this. [OCIColl](http://docs.oracle.com/cd/B28359_01/appdev.111/b28395/oci19map001.htm#CEGGDJBE) might be the appropriate data structure and functions to populate from Go and pass to [OCIBindByPos](https://github.com/rana/ora/blob/master/bndInt64Slice.go#L55). Hopefully, OCIColl works fine. If its not, manually fill a go slice of bytes and pass to bind [OCIBindByPos](https://github.com/rana/ora/blob/master/bndInt64Slice.go#L55) and [OCIBindArrayOfStruct](https://github.com/rana/ora/blob/master/bndInt64Slice.go#L72)? The manual approach would require determining the associative array memory layout. Check forums, documentation, and trial and error. For example, for a TABLE OF VARCHAR2(4000) INDEX BY BINARY_INTEGER,  are two entries structured as:

a. 8 byte for integer, 4000 byte string, 8 byte integer, 4000 byte string 
b. or: 8 byte integer, 8 byte integer, 4000 byte string, 4000 byte string

It would be nice to find some clear OCI documentation example, or OCI forum example showing how to work with associative array before selecting an approach. All this effort will no doubt be appreciated by many people. With that said, it might be less effort to rewrite the stored procs. Your call.

Thank you,

Rana

**Comment by rana** [comment]
Jorge,

I will re-open the issue. 
There is a genuine need for the feature.

**Comment by jmptrader** [comment]
Hi Rana,
Thank's for your attention. 

*Only like anecdote*

  Currently like workaround for this detail , I developed the following:

  layer-1: GO program that bind to C with cgo , libwrapper.so.
  layer-2: libwrapper.so that use the OCILIB for call procedures with associative arrays. 
  layer-3: OCILIB es wrapper de OCI from oracle.

  Note    : between layer-1 and layer-2,  I pass an JSON format string.
  ---+--

Three points:

1. OCILIB its an very weel code & documented library on top of ocilib for ANSI C & C++ (cross platform & oracle version from 8  to 12)

I think that can be source of inspiration. 

@tgulacsi  is author  https://github.com/tgulacsi/gocilib an Go Oracle database driver with OCILIB.

2. I think that "Determine what the associative array definition is at runtime" is an hack. Better is an have an mapping documented. After all, the developer have know the signature of procedures ;-)

3. Is very cool  an GO library that can get  Oracle specific features when are needed. But at the same time compatible con database/sql. In ora package feel this. (see also https://github.com/JackC/pgx)


--- x --

**Comment by tgulacsi** [comment]
Goracle (gopkg.in/goracle.v1) can bind associative arrays. So no magic is
needed, simple OCI bound []"OCIType" works, with two support arrays: one
for NULLs, and the other for lengths.

2015-06-06 19:23 GMT+02:00 Jorge <notifications@github.com>:

**Comment by jmptrader** [comment]
Tamás; Thanks, i will check this.

**Comment by tgulacsi** [comment]
Hi,

I've started something in the "slice" branch. At the moment only for []Float32/[]Float64 and []float32/[]float64, but it binds as PL/SQL TABLE (i.e. TYPE num_tab_typ IS TABLE OF NUMBER INDEX BY PLS_INTEGER).

Maybe this change kills the ExecuteMany functionality (bind an array with some SQL statement, and execute that statement for each element of the array), I don't know - that's why its in a separate branch.

If you could test it, that'd be grateful!

Thanks,
Tamás Gulácsi

**Comment by tgulacsi** [comment]
@jmptrader see the slice branch (https://github.com/rana/ora/tree/slice), it now has PL/SQL Table support for NUMBER ([]Int32, []Int64, []Float32, []Float64), VARCHAR2 ([]String) and DATE ([]Date).

For example, see z_plsarr_session_test.go


Regarding OCILIB: first, I've ported cx_Oracle (which I use with Python), but that (Variable for everything) was very non-idiomatic Go; then tried OCILIB, but that just didn't worth the extra work for compile & distribute & run (libocilib.so).
OCILIB is really nice, but if you use it  from non-C, you have to write the wrappers, anyway. So why not use only one lib, libclntsh.so? (OCILIB depends on it, anyway).

**Comment by jmptrader** [comment]
Tamás; Thanks, 

I have an real case in production (go+libwrapper_specific+ocilib+libclntsh). That I wish avoid.

I will test this.
