### ISSUE TITLE
How to distinguish null and zero value for out parameters of stored procedure

### ISSUE THREAD

**Issue by vamkaxifa** [rana/ora#190]
As titled, how to distinguish _null_ and _zero value_ for out parameters of stored procedure?

I wrote a common method to call stored procedure, this method can handle all kinds of out parameters's type including STRING NUMBER CURSOR...
Everything got be ok until recently, I found that ora doesn't seem to be able to  distinguish _null_ and _zero value_ for out parameters of stored procedure. 
Take STRING for example, no matter my stored procedure returns _null_ or _""_ , ora returns _""_, this causes me trouble: my users feel confused which leads some bad result. 
The same problem to NUMBER.

Pseudo code:
```
type T1 struct {X interface{}  `json:"x"`
                Y interface{}  `json:"y"` }

interfaceOutArr := make([]interface{}, 2) 
var a string
interfaceOutArr = append(interfaceOutArr, &a)
var b float64
interfaceOutArr = append(interfaceOutArr, &b)

stmtProcCall, err := ses.Prep("CALL Produce1(:1,:2)")
stmtProcCall.Exe(interfaceOutArr...)

t := T1{X= interfaceOutArr[0], Y= interfaceOutArr[1]}

jsonByte, err2 := json.Marshal(t)
result := string(jsonByte)
return result
```
1. Produce1 returns _null_ _null_:
   result = {"x":"","y":0}
2. Produce1 returns _""_ _0_:
   result = {"x":"","y":0}

Here comes the problem, I can't figure out what on earth does Produce1 return, _null_ or _""(0)_ ? 
So, How can I work this out in this common method ?
Actually, when Produce1 returns _null_ _null_, I want _result = {"x":null,"y":null}_

**Comment by tgulacsi** [comment]
Use ora.Num, ora.String & co.
Btw neither Oracle distinguish the empty string and null.

Nancy <notifications@github.com> ezt írta (időpont: 2017. ápr. 27., Cs
9:12):

**Comment by vamkaxifa** [comment]
Hum... I tried, but I failed. 
```
interfaceOutArr := make([]interface{}, 2) 
var str_ ora.String   # also tried:   str_ := ora.String{}
interfaceOutArr = append(interfaceOutArr, &str_)
var float_ ora.Num  #also tried:   float_ :=ora.Float64{}
interfaceOutArr = append(interfaceOutArr, &float_)

stmtProcCall, err := ses.Prep("CALL Produce1(:1,:2)")
stmtProcCall.Exe(interfaceOutArr...)
```

 stored procedure:
```
CREATE OR REPLACE PROCEDURE Produce1
(
   res out varchar,
   res2 out number
)
IS
BEGIN
 res :=1;
 res2 := 'this is a string';
END Produce1;
```

I got error:
```
Stmt.exeC Stmt.bind Invalid bind parameter () (*ora.String:).
Stmt.exeC Stmt.bind Invalid bind parameter () (*ora.Num:0xc420070b50).

# Stmt.exeC Stmt.bind Invalid bind parameter () (*ora.String:).
# Stmt.exeC Stmt.bind Invalid bind parameter () (*ora.Float64:&{false 0})


```

**Comment by vamkaxifa** [comment]
@tgulacsi According to README [Working With The Oracle Package Directly](https://github.com/rana/ora#working-with-the-oracle-package-directly) , it mentioned that Oracle types NUMBER° NUMBER¹ should map Go types int64, int32, int16, int8...float64, float32...except ora.Num  ora.Float64... , and it also mentioned that "_Pointers may be used to capture out-bound values from a SQL statement such as an insert or stored procedure call_".  I already have gave a pointer , So I think is this  why I got `Stmt.exeC Stmt.bind Invalid bind parameter ()` error ? If so, how to fix  _when Produce1 returns null null, I want result = {"x":null,"y":null}_ problem. 
You said
> Use ora.Num, ora.String & co.

to capture out-bound values from stored procedure call, can you give me an example based on _Produce1_ I mentioned above since I do can't  figure out this problem  in you way.

**Comment by vamkaxifa** [comment]
@tgulacsi I update ora ,use *ora.OCINum to map Oracle types NUMBER,  and It works. when _Produce1_ returns a NUMBER null, I can get _result = {"x":"null"} _  not  _result = {"x":null}_ ,but this maybe enough. 
But Oracle types VARCHAR still not work. I used *ora.String to  capture out-bound values from stored procedure call, but I still got  `Stmt.exeC Stmt.bind Invalid bind parameter () (*ora.String:)` error.
 I looked into `stmt.go`, in method `stmt.bind`, it does't handle  *ora.String type, that's why I got this error.

**Comment by tgulacsi** [comment]
I don't have time right now, will try to look into it later - but you can
try to extend that big switch with the new pointer types.
Take a look at other pointer types, copy from there.

Nancy <notifications@github.com> ezt írta (időpont: 2017. máj. 3., Sze,
10:47):

**Comment by vamkaxifa** [comment]
@tgulacsi  I made it !! As you said, I extended that big switch with the new pointer type and I succeeded !
This is what I add:
```
case *String:
			bnd := stmt.getBnd(bndIdxStringPtr).(*bndStringPtr)
			bnds[n] = bnd
			spbs := stmt.stringPtrBufferSize
			if spbs == 0 {
				spbs = stmt.Cfg().stringPtrBufferSize
			}
			str := &(value.Value)
			err = bnd.bind(str, pos, spbs, stmt)
			if err != nil {
				return iterations, err
			}
			stmt.hasPtrBind = true
```

**Comment by vamkaxifa** [comment]
@tgulacsi I'm sorry that I mislead you. The code I comment before:
```
case *String:
			bnd := stmt.getBnd(bndIdxStringPtr).(*bndStringPtr)
			bnds[n] = bnd
			spbs := stmt.stringPtrBufferSize
			if spbs == 0 {
				spbs = stmt.Cfg().stringPtrBufferSize
			}
			str := &(value.Value)
			err = bnd.bind(str, pos, spbs, stmt)
			if err != nil {
				return iterations, err
			}
			stmt.hasPtrBind = true
```
is not  right.  In fact, this `case *String:` is `case *string:` because it uses `bndStringPtr `. As a result, `Produce1` returning a varchar `null` has no difference to returning a archer `""`. This is not right. 
So I delete that comment, thinking about maybe we need to add a `bndOraStringPtr.go `, although I'm tying , but I haven't understood the whole code environment, thus, I haven't succeed. 
I'm so sorry!!

**Comment by tgulacsi** [comment]
Ok, I've got lost.
Oracle *does not* distinguish between the empty string ('') and the NULL value. 
So neither can we.
