### ISSUE TITLE
can not build cross-platform with gox

### ISSUE THREAD

**Issue by JackFong** [rana/ora#193]
got error

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # gopkg.in/rana/ora.v4
../../gopkg.in/rana/ora.v4/drvStmt.go:18: undefined: Stmt

**Comment by tgulacsi** [comment]
Sorry, but what is "fox" ?

**Comment by tgulacsi** [comment]
BTW cgo is needed, so cross-compilation is not easy!

**Comment by JackFong** [comment]
yes, i thought too simple
