### ISSUE TITLE
Installing form gopkg.in/rana/ora.v4

### ISSUE THREAD

**Issue by jmptrader** [rana/ora#199]
Hi,

In Linux CentOS 7  kernel  4.9.15  arch x86_64.

When I intented install the package with:

                go get gopkg.in/rana/ora.v4 

The output is:

```
# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
pkg-config: exit status 1
```

 

What is wrong?

**Comment by tgulacsi** [comment]
See https://github.com/rana/ora/issues/157 for example.

Copy contrib/oci8.pc to /usr/local/share/pkgconfig/oci8.pc or wherever `man pkg-config` suggests.

Then modify the contents of that oci8.pc to make it point to wherever your Oracle Instant Client or DB dev files are installed.

**Comment by jmptrader** [comment]
Hi,

Thank's, perfect. 

In my case, for Oracle Instant Client 11.2:

```

#first intent
go get gopkg.in/rana/ora.v4 

# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
pkg-config: exit status 1

```

then 

```

# workarround

mkdir /usr/local/share/pkgconfig
cp contrib/oci8_linux_amd64.pc /usr/local/share/pkgconfig/oci8_linux_amd64.pc
cd /usr/local/share/pkgconfig
ln -s oci8.pc oci8_linux_amd64.pc

export PKG_CONFIG_PATH=/usr/local/share/pkgconfig
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:/usr/local/lib:/usr/lib64
export OCI_HOME=/usr/lib/oracle/11.2/client64/lib
export OCI_LIB_DIR=/usr/lib/oracle/11.2/client64/lib
export OCI_INC_DIR=/usr/include/oracle/11.2/client64
export OCI_INCLUDE_DIR=/usr/include/oracle/11.2/client64
export OCI_VERSION=11
export C_INCLUDE_PATH=/usr/include:/usr/include/oracle/11.2/client64:/usr/local/include

cd $HOME

go get -u -v gopkg.in/rana/ora.v4 

```

ok.

**Comment by swizzley** [comment]
gopkg.in/rana/ora.v4
# gopkg.in/rana/ora.v4
/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status

**Comment by tgulacsi** [comment]
Which os?
What does `pkg-config --libs --cflags oci8` say?
Maybe there's a type in the used oci8.pc?

**Comment by swizzley** [comment]
The issue was resolved by installing the oracle instant client 12.2 devel rpm and changing the include path's to  /usr/include path created by the rpm

**Comment by vijayks040** [comment]
i have the same problem in windows machine,
when i tried go get gopkg.in/rana/ora.v4
it says 
# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
pkg-config: exit status 1
i am using latest go version go version go1.8.1 windows/amd64

**Comment by tgulacsi** [comment]
You have to install Oracle Instant Client, then put an oci8.pc into the pkg-config search path.
For such oci8.pc, look around in the contrib directory, choose some good starting base and modify it to your config.
You can check the result with "pkg-config --cflags --libs oci8", that should output the proper libs.

**Comment by vijayks040** [comment]
yes i have installed oracle instant client and oci8 also created and Added to path
now i got # pkg-config --cflags oci8
pkg-config: exec: "pkg-config": executable file not found in %PATH%

**Comment by russellfei** [comment]
Just solve this problem by edit `oci8.pc` file.
You should change the params in original `oci8_darwin.pc`('cause I'm installing it on my OSX 10.12) to your own library paths.
Good luck for the following guys who check this issue.
