### ISSUE TITLE
Why the transfer from ranaian to rana?

### ISSUE THREAD

**Issue by tgulacsi** [rana/ora#20]
f71fd9151c6910ffcd85beb164997378bbaf3481 - without announcement, this is a very rude step: all import statements became stale!

If you move, I'd suggest move under a gopkg.in: create a go-ora organisation, and transfer github.com/rana/ora under github.com/go-ora/ora, and use the v1 branch as the main branch. This would allow to use gopkg.in/ora.v1 as a canonical import path.

**Comment by rana** [comment]
Apologies for no previous notice. Good point to adjust with gopkg.in. a one time occurrence
