### ISSUE TITLE
oci* types to go types, when reading unknown table

### ISSUE THREAD

**Issue by mseshachalam** [rana/ora#202]
I am using github.com/rana/ora to fetch records from any table and schema is  unknown. Since I dont know the column types, i wont be having a predefined struct to scan a row into. I am using https://godoc.org/github.com/jmoiron/sqlx#Rows.MapScan to scan a row into map.
 
If the type of column is `NUMBER` in oracle table the row scan is giving float, if column type is `FLOAT` I am getting OCINum type. I guess it is the same for many other column types.
I want all these types to be converted to golang types. Any pointers on how to do this ?
I will be converting each of these scanned map to json and consume. When I json marshall the scanned row and if the row has ocinum, the json has ocinum marshalled. How do i get the go type here ?

One more thing, are the prepared select statements faster than normal select queries ?

Any help is much appreciated. Thanks.

**Comment by tgulacsi** [comment]
OCINum has String method, and then you can convert from the string.
Or override the default config, like `stmt.SetCfg(stmt.Cfg().SetNumberFloat(ora.F64))` to set it to float64.
