### ISSUE TITLE
Scan gbk content in clob column failed.

### ISSUE THREAD

**Issue by tianlin** [rana/ora#204]
NLS_CHARACTERSET is 'ZHS16GBK',  when I query clob column which contains gbk will return \ufffd, but if I use select to_char(xx) to query the result is right.

And I found SELECT TO_NCLOB(xx) will return right result too.

**Comment by tgulacsi** [comment]
Please send your client & server NLS settings and take a look at
https://stevecao.wordpress.com/2016/01/11/understanding-character-set/

The Go client lib sets AL32UTF8 to communicate withe the server, and
assumes everything is utf8. Maybe some other encoding (for nchars, nclobs)
should be set, too.

tianlin <notifications@github.com> ezt írta (időpont: 2017. jún. 19., H
6:50):

**Comment by tianlin** [comment]
In client:
NLS_LANG is not set
In server:
select * from v$nls_parameters;

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_LANGUAGE                                                                    
SIMPLIFIED CHINESE                                                              
                                                                                
NLS_TERRITORY                                                                   
CHINA                                                                           
                                                                                
NLS_CURRENCY                                                                    
￥                                                                              
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_ISO_CURRENCY                                                                
CHINA                                                                           
                                                                                
NLS_NUMERIC_CHARACTERS                                                          
.,                                                                              
                                                                                
NLS_CALENDAR                                                                    
GREGORIAN                                                                       
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_DATE_FORMAT                                                                 
DD-MON-RR                                                                       
                                                                                
NLS_DATE_LANGUAGE                                                               
SIMPLIFIED CHINESE                                                              
                                                                                
NLS_CHARACTERSET                                                                
ZHS16GBK                                                                        
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_SORT                                                                        
BINARY                                                                          
                                                                                
NLS_TIME_FORMAT                                                                 
HH.MI.SSXFF AM                                                                  
                                                                                
NLS_TIMESTAMP_FORMAT                                                            
DD-MON-RR HH.MI.SSXFF AM                                                        
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_TIME_TZ_FORMAT                                                              
HH.MI.SSXFF AM TZR                                                              
                                                                                
NLS_TIMESTAMP_TZ_FORMAT                                                         
DD-MON-RR HH.MI.SSXFF AM TZR                                                    
                                                                                
NLS_DUAL_CURRENCY                                                               
￥                                                                              
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_NCHAR_CHARACTERSET                                                          
AL16UTF16                                                                       
                                                                                
NLS_COMP                                                                        
BINARY                                                                          
                                                                                
NLS_LENGTH_SEMANTICS                                                            
BYTE                                                                            
                                                                                

PARAMETER                                                                       
----------------------------------------------------------------                
VALUE                                                                           
----------------------------------------------------------------                
NLS_NCHAR_CONV_EXCP                                                             
FALSE

**Comment by tianlin** [comment]
When I set NLS_LANG=AMERICAN_AMERICA.AL32UTF8, I get right result with sqlplus

**Comment by tgulacsi** [comment]
Ok, right now I cannot find the NLS setting code - maybe my memory fails me.
What if you set `export NLS_LANG=AMERICAN_AMERICA.AL32UTF8` environment
variable before calling your go program?


tianlin <notifications@github.com> ezt írta (időpont: 2017. jún. 19., H,
9:28):

**Comment by tianlin** [comment]
I try export NLS_LANG=AMERICAN_AMERICA.AL32UTF8, the result is still wrong.

**Comment by tgulacsi** [comment]
Ok, found it: ora.go#L182 - both charset and ncharset is set to AL32UTF8 at
the creation of the Env in OpenEnv.

Gulácsi Tamás <tgulacsi78@gmail.com> ezt írta (időpont: 2017. jún. 20., K,
6:03):

**Comment by tianlin** [comment]
Hi, I found the reason.
In defLob.go, call C.OCILobRead2, code use csid of server side, so it return gbk charset buffer.I set csid=873(AL32UTF8), it will return utf8 charset buffer(which is right).

**Comment by tgulacsi** [comment]
Wow, nice catch, thanks!

tianlin <notifications@github.com> ezt írta (időpont: 2017. jún. 22., Cs
2:46):

**Comment by tgulacsi** [comment]
Pleas try 5848925 (current master)!

**Comment by tgulacsi** [comment]
Ok, try 760571c - this fixes the infinite loop.

**Comment by tianlin** [comment]
it work when read clob, but not work when read nclob, may be you should pass right charsetform of lob (C.SQLCS_IMPLICIT for lob, C.SQLCS_NCHAR for nlob)
