### ISSUE TITLE
 ORA-03113 err

### ISSUE THREAD

**Issue by dfy167** [rana/ora#206]
i have a small web project just query data from database .
most time it just have one connection
i just use query to query data

r, err :=db.Query(query, args...)
when  kill session in oracle . then  ORA-03113 at first time .and when send  second post 

i think query -->QueryContext
func (db *DB) QueryContext(ctx context.Context, query string, args ...interface{}) (*Rows, error) {
	var rows *Rows
	var err error
	for i := 0; i < maxBadConnRetries; i++ {
		rows, err = db.query(ctx, query, args, cachedOrNewConn)
		if err != driver.ErrBadConn {
			break
		}
	}
	if err == driver.ErrBadConn {
		return db.query(ctx, query, args, alwaysNewConn)
	}
	return rows, err

**Comment by tgulacsi** [comment]
The strange thing is that conn.go already treats ORA-03113 as driver.ErrBadConn, so database/sql should treat it as a request to a new conn.

Is the posted code from database/sql?
