### ISSUE TITLE
Unable to pass a string array to a procedure (PLS-00306)

### ISSUE THREAD

**Issue by phito** [rana/ora#209]
Here's my function, which is stored in a package named `app`

```sql
type array_s is table of varchar2(100 char);
function search(title_regex in varchar2, actors in array_s, directors in array_s) return sys_refcursor;
```
and my call to it
```go
var actors = make([]string, 1)
var title = "interstellar"
actors[0] = "Matthew McConaughey"

rset := &ora.Rset{}
stmt, err := conn.ses.Prep("begin :1 := app.search(:2, :3, app.array_s()); end;")
_, err = stmt.ExeP(rset, title, actors)
```

gives
```
execution failed: Stmt.exeC Env.ociError ORA-06550: line 1, column 13:
PLS-00306: wrong number or types of arguments in call to 'SEARCH'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
```

It works if I replace the 3rd parameter with `app.array_s()`, so I guess that the type of the array doesn't match?

By the way, the README is broken on master

**Comment by tgulacsi** [comment]
What's the error???

Romain Quinet <notifications@github.com> ezt írta (időpont: 2017. júl. 24.,
H 14:14):

**Comment by phito** [comment]
It's the 3rd code block on my post

**Comment by tgulacsi** [comment]
Sorry, haven't seen in the mail.
VARRAYS and NESTED TABLEs are not supported, only PL/SQL ASSOCIATIVE ARRAYs - `type array_s is table of varchar2(100 char) INDEX BY PLS_INTEGER;` is ok, `type array_s is table of varchar2(100 char);` is not.

**Comment by phito** [comment]
Oh alright, that is unfortunate.

Thanks
