### ISSUE TITLE
 fatal error: oci.h: No such file or directory

### ISSUE THREAD

**Issue by vijayks040** [rana/ora#214]
i am trying to go get  gopkg.in/rana/ora.v4
and the output is 
gopkg.in\rana\ora.v4\bndBfile.go:9:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.and i am currently using 
go version go1.8.1 windows/amd64
please help me to resolve this

**Comment by rahul-chowdhary** [comment]
Facing same issue in linux.Any solution?

**Comment by tgulacsi** [comment]
As the README says, this project is unmaintained. Use gopkg.in/goracle.v2!
