### ISSUE TITLE
Stmt.exeC Stmt.checkClosed Stmt is closed

### ISSUE THREAD

**Issue by vamkaxifa** [rana/ora#218]
Hey guys, I got this err `Stmt.exeC Stmt.checkClosed Stmt is closed` when I called stored procedure form Oracle .  I guess this may associate with `commit` in stored  procedure, but after I removed `commit` , I still got this error . I can't figure out where does the bug lie. Does anybody know?

**Comment by vamkaxifa** [comment]
```
rowsAffected, err := stmtProcCall.Exe(interfaceInArr...)
	if err != nil {
		log.Error("stmtProcCall.Exe occurs error:", err.Error())
		return
	}
```
This pice of code got err: stmtProcCall.Exe occurs error:Stmt.exeC Stmt.checkClosed Stmt is closed.

**Comment by tgulacsi** [comment]
Are you sure that stmt is not closed, and prepared properly?

**Comment by vamkaxifa** [comment]
Thank you very much! It turns out that I miss `defer` in front of `stmtProcCall.Close()`, which result in that err ... my mistake ...

**Comment by vamkaxifa** [comment]
Thank you very much! It turns out that I miss `defer` in front of `stmtProcCall.Close()`, which result in that err ... my mistake ...
