### ISSUE TITLE
Stmt.Close()  causes panic 

### ISSUE THREAD

**Issue by kogan69** [rana/ora#229]
Hi, I'm getting panic when calling the Stmt.Close()
I'm calling a stored procedure that returns 4 cursors. 
If I'm calling the Close without calling NextRow() on all result sets I'm getting the following panic:
GOROOT=/home/kogan/devtools/go #gosetup
GOPATH=/home/kogan/go #gosetup
/home/kogan/devtools/go/bin/go test -c -i -o /tmp/___TestCloseStatement_in_close_test_go lobtest #gosetup
/tmp/___TestCloseStatement_in_close_test_go -test.v -test.run ^TestCloseStatement$ #gosetup
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7ff601010121 pc=0x7ff68e2ba78b]

runtime stack:
runtime.throw(0x66ce00, 0x2a)
	/home/kogan/devtools/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/home/kogan/devtools/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x5eed10, 0xc420ebb7a8, 0x66c921)
	/home/kogan/devtools/go/src/runtime/cgocall.go:132 +0x82 fp=0xc420ebb768 sp=0xc420ebb730 pc=0x405522
gopkg.in/rana/ora%2ev4._Cfunc_OCIDescriptorFree(0x7ff601010101, 0x7ff600000045, 0x0)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:626 +0x4d fp=0xc420ebb7a8 sp=0xc420ebb768 pc=0x55ef9d
gopkg.in/rana/ora%2ev4.(*defTime).free.func1(0x7ff601010101, 0x45, 0xfffffffe)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/defTime.go:75 +0x68 fp=0xc420ebb7e0 sp=0xc420ebb7a8 pc=0x5ddbd8
gopkg.in/rana/ora%2ev4.(*defTime).free(0xc420f26000)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/defTime.go:76 +0xa5 fp=0xc420ebb828 sp=0xc420ebb7e0 pc=0x596bd5
gopkg.in/rana/ora%2ev4.(*defTime).close(0xc420f26000, 0x0, 0x0)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/defTime.go:89 +0x6b fp=0xc420ebb868 sp=0xc420ebb828 pc=0x596c9b
gopkg.in/rana/ora%2ev4.(*Rset).close(0xc4200ec0e0, 0x0, 0x0)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/rset.go:175 +0x1e0 fp=0xc420ebbb28 sp=0xc420ebb868 pc=0x5a2ae0
gopkg.in/rana/ora%2ev4.(*rsetList).closeAll(0xc4200ac1c0, 0xc4200b6060)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/list.go:366 +0xb0 fp=0xc420ebbb78 sp=0xc420ebbb28 pc=0x556410
gopkg.in/rana/ora%2ev4.(*Stmt).close(0xc4200b4360, 0x0, 0x0)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/stmt.go:212 +0x2c5 fp=0xc420ebbe20 sp=0xc420ebbb78 pc=0x5aeee5
gopkg.in/rana/ora%2ev4.(*Stmt).closeWithRemove(0xc4200b4360, 0x0, 0x0)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/stmt.go:130 +0x70 fp=0xc420ebbe50 sp=0xc420ebbe20 pc=0x5aeba0
gopkg.in/rana/ora%2ev4.(*Stmt).Close(0xc4200b4360, 0xc4200e7f48, 0x5)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/stmt.go:115 +0x2b fp=0xc420ebbe78 sp=0xc420ebbe50 pc=0x5aeb0b
lobtest.TestCloseStatement(0xc4200d80f0)
	/home/kogan/go/src/lobtest/close_test.go:62 +0x423 fp=0xc420ebbfa8 sp=0xc420ebbe78 pc=0x5edf03
testing.tRunner(0xc4200d80f0, 0x66fae0)
	/home/kogan/devtools/go/src/testing/testing.go:746 +0xd0 fp=0xc420ebbfd0 sp=0xc420ebbfa8 pc=0x4f8450
runtime.goexit()
	/home/kogan/devtools/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420ebbfd8 sp=0xc420ebbfd0 pc=0x4636c1
created by testing.(*T).Run
	/home/kogan/devtools/go/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200d8000, 0x666dd9, 0x12, 0x66fae0, 0x983b60)
	/home/kogan/devtools/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200d8000)
	/home/kogan/devtools/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200d8000, 0xc420055de8)
	/home/kogan/devtools/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4200ac040, 0x96efa0, 0x3, 0x3, 0x0)
	/home/kogan/devtools/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42003ff20, 0xc420078058)
	/home/kogan/devtools/go/src/testing/testing.go:921 +0x111
main.main()
	lobtest/_test/_testmain.go:48 +0xdb

goroutine 19 [select]:
gopkg.in/rana/ora%2ev4.(*poolEvictor).SetEvictDuration.func1(0xc4200ac0e0, 0xc4200d2420)
	/home/kogan/go/src/gopkg.in/rana/ora.v4/pool.go:357 +0x10e
created by gopkg.in/rana/ora%2ev4.(*poolEvictor).SetEvictDuration
	/home/kogan/go/src/gopkg.in/rana/ora.v4/pool.go:354 +0xff

Process finished with exit code 2

Here's the test code:

```
package lobtest

import (
	"testing"
	"gopkg.in/rana/ora.v4"
)

func TestCloseStatement(t *testing.T) {

	SessionPool, err := ora.NewPool(dbConnectionString, 32)
	if err != nil {
		t.Error(err)
	}
	session, err := SessionPool.Get()
	if err != nil {
		t.Error(err)
	}
	defer SessionPool.Put(session)

	stmt, err := session.Prep("call sp_get_user_state(:i_user_guid, :o_cur_users,:o_cur_auth_users,:o_cur_acct_accounts,:o_cur_settings)")
	if err != nil {
		t.Error(err)
	}

	usersCur := &ora.Rset{}
	authUsersCur := &ora.Rset{}
	accountsCur := &ora.Rset{}
	settingsCur := &ora.Rset{}

	guid := "005305894BFA62CBE050CB0A336D76E5"
	_, err = stmt.Exe(guid, usersCur, authUsersCur, settingsCur, accountsCur)

	if err != nil {
		t.Error(err)

	}
	/* Uncommenting this block will eliminate the panic
		row := usersCur.NextRow()
		if row != nil {
			fmt.Println(row)
		}
		row = authUsersCur.NextRow()
		if row != nil {
			fmt.Println(row)
		}
		row = accountsCur.NextRow()
		if row != nil {
			fmt.Println(row)
		}
	*/
	stmt.Close()
}
```
Thanks in advance!
LK

**Comment by tgulacsi** [comment]
Can't reproduce it. Can you tweak TestLOBCloseStatement in z_lob_test.go till it happens again?

**Comment by kogan69** [comment]
Here's the self contained test that fails, unless you'll uncomment the //c2.NextRow
```
func TestCloseStatementWithLobResultSet(t *testing.T) {

	var qry string = `
declare
c1 SYS_REFCURSOR;
c2 SYS_REFCURSOR;
begin
  begin
    execute immediate 'drop table lob_test';
  exception
    when others then
      null;
  end;
  execute immediate 'create table lob_test (c clob)';
  execute immediate 'insert into lob_test values (''Hello'')';
  execute immediate 'insert into lob_test values (''world!'')';
  commit;
  open c1 for 'select sysdate from dual';
  :1:= c1;
  open c2 for 'select * from lob_test';
  :2:= c2;
exception
  when others then
    null;
end;`

	SessionPool, err := ora.NewPool(dbConnectionString, 32)

	if err != nil {
		t.Error(err)
	}

	session, err := SessionPool.Get()
	if err != nil {
		t.Error(err)
	}
	defer SessionPool.Put(session)

	stmt, err := session.Prep(qry)
	if err != nil {
		t.Error(err)

	}

	c1 := &ora.Rset{}
	c2 := &ora.Rset{}

	_, err = stmt.Exe(c1, c2)

	if err != nil {
		t.Error(err)

	}

	c1.NextRow()
	//c2.NextRow()

	stmt.Close()
}
```

**Comment by kogan69** [comment]
BTW, your tests passes in my environment always, despite all of my efforts to screw it :)))
The only difference between yours and mine test is the existence of CLOB column in the result set - IMHO.
Cheers!

**Comment by kogan69** [comment]
Hey, I think that the problem is that the lobClose is called on unallocated def.lobs
Do you think it would be nicer to add a flag that indicates that the lobs are allocated and then use it in the close code to prevent this erroneous unallocation?

**Comment by tgulacsi** [comment]
Yup, but couldn't find out the proper places to register those allocations.

kogan69 <notifications@github.com> ezt írta (időpont: 2017. nov. 8., Sze,
15:40):

**Comment by kogan69** [comment]
A Boolean array aside of def.lobs to register the allocations, perhaps ?
AFAIK wrapping def.lobs into some struct would break too much code...


Cheers,
LK

**Comment by tgulacsi** [comment]
I've tried exactly that, but couldn't find the proper places where should I
set the defs.opened[i] to true.
What does beginRow that lets us avoid the panic on lobClose? It doesn't
call lobOpen. But it calls defLob.alloc - maybe that's enough?

kogan69 <notifications@github.com> ezt írta (időpont: 2017. nov. 9., Cs,
0:06):

**Comment by kogan69** [comment]
Well, my naive understanding is that we could have something like defs.allocated[i] set  true in the alloc() code and then to check them in the lobClose, to avoid calling OCILobCLose

Cheers,
LK

**Comment by kogan69** [comment]
Hi!
Unfortunately, this issue repeats itself for defTime as well.
My guess it's also sits everywhere OCIDescriptorFree is called :(((((
Sadly, it looks like the fix you've done for the defLob shall be replicated all over the place :)

With kind regards,
LK

**Comment by kogan69** [comment]
Totally cool!!!
Bravo!
