### ISSUE TITLE
Support for sql.Out

### ISSUE THREAD

**Issue by veqryn** [rana/ora#231]
Does or can this library support sql.Out (new in golang 1.9)?

The example usage would be:
```go
  var outArg string
  _, err := db.ExecContext(ctx, "ProcName", sql.Named("Arg1", Out{Dest: &outArg}))
```

There could of course be multiple out and inout variables, and the destination could be an RSET or something else.

**Comment by tgulacsi** [comment]
No, and I don't plan to add it - but PRs are welcome!
With Go 1.9, everything can be done with database/sql, so a lot of code is surplus.

A rewrite from scratch (with a nice C helper lib) is at gopkg.in/goracle.v2 (github.com/go-goracle/goracle).

**Comment by veqryn** [comment]
I actually just found that a few hours ago and was giving it a try, but was unable to get it to work for an rset out variable: https://github.com/go-goracle/goracle/issues/27

**Comment by veqryn** [comment]
Thanks for helping me over there!
Closing this...
