### ISSUE TITLE
Panic with invalid memory address

### ISSUE THREAD

**Issue by veqryn** [rana/ora#234]
I was running some load testing comparisons between the different golang oracle drivers (rana/ora, mattn/oci8, and goracle), and the rana/ora driver gave the following panic multiple times.

I have not had time to isolate which query/update/insert was causing this.

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x56280f]
goroutine 8954 [running]:
github.com/xxx/vendor/gopkg.in/rana/ora%2ev4.(*Ses).Break(0xc4203e82c0, 0x0, 0x0)
	/go/src/github.com/xxx/vendor/gopkg.in/rana/ora.v4/ses.go:809 +0x1af
github.com/xxx/vendor/gopkg.in/rana/ora%2ev4.(*DrvStmt).ExecContext.func1(0xc420024a80, 0xc7eee0, 0xc421034a20, 0xc42000fa18)
	/go/src/github.com/xxx/vendor/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:39 +0x1a7
created by github.com/xxx/vendor/gopkg.in/rana/ora%2ev4.(*DrvStmt).ExecContext
	/go/src/github.com/xxx/vendor/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:30 +0x2b8
```

**Comment by tgulacsi** [comment]
That's the Break after context cancelation.

Chris Duncan <notifications@github.com> ezt írta (időpont: 2017. nov. 20.,
H, 18:18):

**Comment by veqryn** [comment]
Shouldn't a break just return an error, not panic?

Also, I'm not cancelling any contexts until after the queries return (with defer).  Most likely there is a race condition just like the other 2 drivers had.

**Comment by veqryn** [comment]
PR above to solve the race condition: https://github.com/rana/ora/pull/235

**Comment by tgulacsi** [comment]
Thanks!
