### ISSUE TITLE
Memory leaks in Rowset-Fetching

### ISSUE THREAD

**Issue by osammler** [rana/ora#238]
Hi,

using the ora.v4-driver i found 2 memory leaks with the go profiler.
1. In the DrvQueryResult.Next function in the case of err != nil (including the case of  eof of rowset) you call the qr.rset.close function, but this removes not the rset from the list of open rset and gc not frees the memory. So many Querys of the same statement with different parameters eat more and more memory.
2. You wrote, that rsets opening and closing is managed internally. But in the case, that a rset is not fetched until eof, the rset will never closed until the statement is closed, and the resources of rset are not freed. So many Queries of the same statement with different parameters and Next-Calls not until eof eat more and more memory. Why is the driver.Rows Close()-function empty?

**Comment by tgulacsi** [comment]
Thanks!

Can you try 48b93e7 ?

**Comment by osammler** [comment]
Hi,

this seems to solve the memory problems. Thanks for speedy help.
