### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by YaProof** [rana/ora#239]
Hi.

I'm use Windows 10, x64.

When I try to install a package, I get an error

\# gopkg.in/rana/ora.v4
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -loci
**collect2.exe: error: ld returned 1 exit status**

go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoPath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\PAVEL~1.VAS\AppData\Local\Temp\go-build605204955=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

Please, tell me, what could be the problem?

**Comment by tgulacsi** [comment]
Do you have oci.dll somewhere? Where have you installed InstantClient?
(BTW gopkg.in/goracle.v2 doesn't need Oracle for compilation, only for running).

**Comment by YaProof** [comment]
OracleClient is installed, there is also oci.dll. The path in the environment variable. To the connection there is, checked PL/SQL developer.

**Comment by tgulacsi** [comment]
ora.v4 uses pkg-config.
What does `pkg-config --libs oci8` print out? It should `-LD:\app\ora12\product\12.1.0\client_1 -loci`.
If not, modify oci8.pc with the correct path.

**Comment by tgulacsi** [comment]
#221 helps?

**Comment by YaProof** [comment]
Thanks, I changed the paths in the oci8.pc file, for variables libdir and includedir.
