### ISSUE TITLE
go get gopkg.in/rana/ora.v2 failing

### ISSUE THREAD

**Issue by Opposition** [rana/ora#24]
Hello

I encountered some issue, while following the installation guide.

I started with setting my environment variables.
CGO_CFLAGS and CGO_LDFLAGS to correct paths within my oracle installation.

I then continued by executing the <b>go get github.com/rana/ora</b>
However, I got a warning that I need to get gopkg.in/rana/ora.v2 
So I executed the command <b>go get gopkg.in/rana/ora.v2</b>
After a little while, I got an error (I guess it is the compilation error)

![image](https://cloud.githubusercontent.com/assets/9334433/8901342/65897f06-3448-11e5-8678-454d69a0e5b5.png)

I am not sure what to make of this.

OS: Windows 7 64 bit.
Go version: go1.4.2 windows/amd64
Gcc version: (tdm64-1) 4.9.2
Oracle version: 11.2.0 client

**Comment by tgulacsi** [comment]
I haven't seen such errors before...

Could you try with the master branch? .v2 is a little bit outdated AFAIK...
(cd %GOPATH%\src\gopkg.in\rana\ora.v2; git checkout -b master origin/master)

2015-07-27 10:21 GMT+02:00 Opposition <notifications@github.com>:

**Comment by Opposition** [comment]
Thanks for your fast reply.

Hmm, I tried what you wrote, but it did not help.
Should I perhaps change my gcc vendor to something else than tdm?

**Comment by tgulacsi** [comment]
Maybe yes, I'm not on Windows...
Just guessing that you could try newer tdm-gcc, or mingw-w64, or even newer
go (tip is very nice).

Sorry, this is not a real help...

2015-07-27 12:53 GMT+02:00 Opposition <notifications@github.com>:

**Comment by rana** [comment]
The solution is to only import the gopkg.in address:

go get gopkg.in/rana/ora.v3

and from your source code only import "gopkg.in/rana/ora.v3".

If you really want to get the source from github.com/rana/ora you will need to edit the ora/doc.go file by removing the // import "gopkg.in/rana/ora.v3" statement. That would involve downloading the source directly from GitHub without "go get".

The ora/doc.go file sets up a circular reference at the line:

 package ora // import "gopkg.in/rana/ora.v3" 

If you have another solution, please share :)

**Comment by crisarceramos** [comment]
Hi Opposition, I wonder if you are able to build in windows?
I cannot build my project because whenever go tried to build ora.v3 lib it fails.

**Comment by rana** [comment]
@crisarceramos 

I build on Windows with:
* TDM GCC 64
* Go 1.4 or 1.5
* Oracle 12c
* ora driver v2 or v3

Would you test removing the import statement in [doc.go](https://github.com/rana/ora/blob/master/doc.go#L1136) and see if that makes a difference?

**Comment by wuzhaohui** [comment]
I built the driver with TDM GCC 64, Go 1.5, Oracle 12c client, ora driver v3 on Windows 7.  However, I got the following error when try to test the connection:
2016/01/12 19:49:48 GetConnection dsn=testuser/testpwd@dbhost:15000/testinstance
2016/01/12 19:49:48 sql: unknown driver "ora" (forgotten import?)

Here is my code:

package main

import (
	"database/sql"
	_ "gopkg.in/rana/ora.v3"
	"log"
	"errors"
)

func GetConnection(dsn string) (*sql.DB, error) {
	if dsn == "" {
		return nil, errors.New("empty DSN")
	}
	log.Printf("GetConnection dsn=%v", dsn)
	conn, err := sql.Open("ora", dsn)
	if err != nil {
		return nil, err
	}
	return conn, nil
}

func main() {

	dsn := "testuser/testpwd@dbhost:15000/testinstance"
	conn, err := GetConnection(dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
}


Please help.  
Thanks
Steven

**Comment by tgulacsi** [comment]
The master branch has rolled away from the official v3 tag very much - for
example v3 still needs a ora.Register(nil) call.

So I've created a v3.1 tag from the current master. Please "go get -u
gopkg.in/rana/ora.v3", and try again!

Tamás Gulácsi

wuzhaohui <notifications@github.com> ezt írta (időpont: 2016. jan. 13.,
Sze, 4:59):

**Comment by wuzhaohui** [comment]
Hi Tamás,

Thanks for the quick reply. I got some issues when running "go get -u gopkg.in/rana/ora.v3" again.

C:\gowork>go get -u gopkg.in/rana/ora.v3
# cd C:\gowork\src\gopkg.in\rana\ora.v3; git pull --ff-only
Updating c6ba8c3..5c69183
error: Your local changes to the following files would be overwritten by merge:
        doc.go
Please, commit your changes or stash them before you can merge.
Aborting
package gopkg.in/rana/ora.v3: exit status 1

Please advise.
Thanks
Steven

**Comment by wuzhaohui** [comment]
Hi Tamás,

@tgulacsi After the old codebase for v3 got cleaned, I run "go get ..." again and everything works fine.  Thanks for your help.

Cheers
Steven

**Comment by tgulacsi** [comment]
Glad you've sorted it out.
