### ISSUE TITLE
are there any plan to implement bulk

### ISSUE THREAD

**Issue by dfy167** [rana/ora#243]
I use sqlx to insert a slice .about 3W data but get 5min to finised .
are there any plan to implement bulk
`tx, err := db.Beginx()
	if err != nil {
		return
	}

	stmt, err := tx.Preparex(sqlStr)
	defer stmt.Close()
	if err != nil {
		return
	}

	t := time.Now()
	fmt.Println(t)

	for _, kpi := range *kpis {
		_, err := stmt.Exec(kpi.Pst, kpi.Enodebid, kpi.Eci, kpi.K10001, kpi.K10002, kpi.K10003)
		if err != nil {
			tx.Rollback()
			return err
		}
	}

	err = tx.Commit()
	fmt.Println(time.Since(t))`

**Comment by tgulacsi** [comment]
It IS implemented!

You have to provide slices for your stmt.Exec.

**Comment by dfy167** [comment]
`	func bulkInsert(db *sqlx.DB, kpis *[]kpi) (err error) {
	sqlStr := "INSERT INTO K_LTE_CELL_H(PST, ENODEBID, ECI, K10001, K10002, K10003) VALUES (:PST, :ENODEBID, :ECI, :K10001, :K10002, :K10003)"

	psts := make([]time.Time, len(*kpis))
	bids := make([]string, len(*kpis))
	ecis := make([]string, len(*kpis))
	k1s := make([]string, len(*kpis))
	k2s := make([]string, len(*kpis))
	k3s := make([]string, len(*kpis))
	for i, kpi := range *kpis {
		psts[i] = kpi.Pst
		bids[i] = kpi.Enodebid
		ecis[i] = kpi.Eci
		k1s[i] = kpi.K10001
		k2s[i] = kpi.K10002
		k3s[i] = kpi.K10003
	}
	_, err = db.Exec(sqlStr, psts, bids, ecis, k1s, k2s, k3s)
	if err != nil {
		return err
	}

	return
}
sql: converting argument $1 type: unsupported type []time.Time, a slice of struct
`

**Comment by tgulacsi** [comment]
Then use goracle.v2.

**Comment by dfy167** [comment]
yes ,and it's very fast
