### ISSUE TITLE
How to get the result of a function

### ISSUE THREAD

**Issue by Entrio** [rana/ora#251]
I have a function that returns a number
`declare V NUMBER; begin V:=supscr.SUPSCR$DECREASE_WITH_ID_PKG.f_decrease_id_trc(2643208543386167522,1000,'M000','STA00000000000000774','T743881'); DBMS_OUTPUT.put_line(V); end;`

How can I fetch V?

Thank you

**Comment by tgulacsi** [comment]
I'd use `gopkg.in/goracle.v2`, but maybe the same works with `rana/ora.v4`:

    db, err := sql.Open("goracle", "user/passw@host")
    defer db.Close()
    ctx := context.WithTimeout(context.Background(), 3*time.Second())
    var num string
    _, err := db.ExecContext(ctx, 
        "BEGIN :1 := supscr.SUPSCR$DECREASE_WITH_ID_PKG.f_decrease_id_trc(2643208543386167522,1000,'M000','STA00000000000000774','T743881'); END;", 
        sql.Out{Dest: &num},
    )
    fmt.Println(num)

**Comment by Entrio** [comment]
Hi!
Thanks for replying so fast

Unfortunately I cant get `gopkg.in/goracle.v2` installed as i get a fatal error ` dpiImpl.h: No such file or directory` 

If i use sql.Out I get the following error: `sql: converting argument $1 type: unsupported type sql.Out, a struct`

**Comment by tgulacsi** [comment]
What does

    go get -u -x gopkg.in/goracle.v2

print?

Alex <notifications@github.com> ezt írta (időpont: 2018. júl. 24., K, 7:39):

**Comment by Entrio** [comment]
Thank you for your help, was an issue with dep, solved it thanks to [golang/dep#1731](https://github.com/golang/dep/issues/1731)

**Comment by tgulacsi** [comment]
https://github.com/go-goracle/goracle/issues/80 is the same, I think.

Alex <notifications@github.com> ezt írta (időpont: 2018. júl. 24., K, 7:47):
