### ISSUE TITLE
Package 'oci8' has no Name: field 

### ISSUE THREAD

**Issue by chakrapani123** [rana/ora#252]
Hello ,

I am trying to set- up on my mac os x and have the following error:
Package 'oci8' has no Name: field

i have installed oracle client , and also have the following oci8.pc file 

prefix=/Users/xxxxOracle/instantclient_12_2

version=12.2
build=client64

libdir=${prefix}
includedir=${prefix}/sdk/include

Name: oci8
Description: Oracle database engine
Version: ${version}
Libs: -L${libdir} -lclntsh
Libs.private:
Cflags: -I${includedir}
here is the verbose output:

Fetching https://gopkg.in/rana/ora.v4?go-get=1
Parsing meta tags from https://gopkg.in/rana/ora.v4?go-get=1 (status code 200)
get "gopkg.in/rana/ora.v4": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v4", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v4"} at https://gopkg.in/rana/ora.v4?go-get=1
gopkg.in/rana/ora.v4 (download)
Fetching https://golang.org/x/sync/errgroup?go-get=1
Parsing meta tags from https://golang.org/x/sync/errgroup?go-get=1 (status code 200)
get "golang.org/x/sync/errgroup": found meta tag main.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync/errgroup?go-get=1
get "golang.org/x/sync/errgroup": verifying non-authoritative meta tag
Fetching https://golang.org/x/sync?go-get=1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
golang.org/x/sync (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://gopkg.in/rana/ora.v4/date?go-get=1
Parsing meta tags from https://gopkg.in/rana/ora.v4/date?go-get=1 (status code 200)
get "gopkg.in/rana/ora.v4/date": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v4", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v4"} at https://gopkg.in/rana/ora.v4/date?go-get=1
get "gopkg.in/rana/ora.v4/date": verifying non-authoritative meta tag
Fetching https://gopkg.in/rana/ora.v4?go-get=1
Parsing meta tags from https://gopkg.in/rana/ora.v4?go-get=1 (status code 200)
Fetching https://gopkg.in/rana/ora.v4/num?go-get=1
Parsing meta tags from https://gopkg.in/rana/ora.v4/num?go-get=1 (status code 200)
get "gopkg.in/rana/ora.v4/num": found meta tag main.metaImport{Prefix:"gopkg.in/rana/ora.v4", VCS:"git", RepoRoot:"https://gopkg.in/rana/ora.v4"} at https://gopkg.in/rana/ora.v4/num?go-get=1
get "gopkg.in/rana/ora.v4/num": verifying non-authoritative meta tag
github.com/pkg/errors (download)
golang.org/x/net/context
github.com/pkg/errors
golang.org/x/sync/errgroup
gopkg.in/rana/ora.v4/num
gopkg.in/rana/ora.v4
# pkg-config --cflags oci8
Package 'oci8' has no Name: field
pkg-config: exit status 1

thanks
Chakri

**Comment by tgulacsi** [comment]
Are you sure the capitalized fields in oci8.pc is correct?

BTW installation of gopkg.in/goracle.v2 is easier.

**Comment by chakrapani123** [comment]
its my local location of installation directory .

**Comment by chakrapani123** [comment]
here is the exact error message:

gopkg.in/rana/ora.v4
# pkg-config --cflags oci8
Package 'oci8' has no Name: field
pkg-config: exit status 1

**Comment by chakrapani123** [comment]
i fixed it by changing oci8.pc location to installation directory and setting LD_LIBRARY_PATH & PKG_CONFIG_PATH to oracle_home directory and updating oci8.pc for mac os x to 

prefixdir=/Users/<xxx>/Oracle/instantclient_12_2/
libdir=${prefixdir}
includedir=${prefixdir}/sdk/include

Name: OCI
Description: Oracle database driver
Version: 12.2
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}
