### ISSUE TITLE
Build in Bitbucket Pipelines

### ISSUE THREAD

**Issue by testdevmm** [rana/ora#261]
Hi, Tamás
I try to build CI in Bitbucket for my API service with Bitbucket Pipelines bitbucket-pipelines.yml file
Getting error on "go get -v" step
```
go get -v
...
gopkg.in/rana/ora.v4
../gopkg.in/rana/ora.v4/bndBfile.go:9:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
```

Well, I understand that i need to provide oracle libraries. 
But the question is, what is a minimal list of oracle files I can include to my project to run tree commands (in docker):

> go get -v
> go build -v
> go test -v

Most probably will be nice to use whole Oracle Client, but i want to find a suitable solution

Thank you!
PS
In  _bitbucket-pipelines.yml_ I use image **golang:1.11**

**Comment by tgulacsi** [comment]
Use gopkg.in/goracle.v2, that's self-contained, does not need Oracle Client (only at runtime).

**Comment by testdevmm** [comment]
thank you!
Actually already make it work with external libraries.
But will add task to refactor with gopkg.in/goracle.v2
