### ISSUE TITLE
Data Cartridge Development support

### ISSUE THREAD

**Issue by leoberteck** [rana/ora#265]
Hello I would like to know how I would use your library to develop a shared library to load inside the oracle database and call my go functions from inside PLSQL just like in this example:

Static  OCIEnv   *envhp;
Static  OCISvcCtx  *svchp;
Static OCIError   *errhp;
Int   c_findmin (OCIExtProcContext *ctx, OCILobLocator  *lobl) {
sword  retval;
retval = OCIExtProcGetEnv (ctx, &envhp, &svchp, &errhp);
if ((retval != OCI_SUCCESS) && (retval !=  OCI_SUCCESS_WITH_INFO))
   exit(-1);
   /* Use lobl to read the CLOB, compute the minimum, and store the value
       in retval. */
return retval;
}

https://docs.oracle.com/cd/B28359_01/appdev.111/b28425/c_cpp_java.htm

Have you ever done this? Do you any examples of how I can do this?

**Comment by tgulacsi** [comment]
rana/ora is unaintained ATM, I'm developing goracle.v2 (github.com/go-goracle/goracle).

But that's based on ODPI-C (https://github.com/oracle/odpi), which eases the usage, compilation (only needs the Oracle Client libraries at runtime), and though it says it can be extended with OCI functions easily, I don't see that at first glance.
`DPI_OCI_LOAD_SYMBOL("OCIExtProcGetEnv", ...)` may be used to load the OCIExtProcGetEnv function, as that's not used in ODPI-C now - or maybe you could ask @anthony-tuininga to include it.
That would be the easiest way.

If you need it fast, and know a little C, and you can write the required functionality (get the env, svc, err, lob handlers; read the lob chunks), then it's easy to embed it in Go (with cgo).

**Comment by leoberteck** [comment]
Thanks :)

**Comment by cjbj** [comment]
@leoberteck keep an eye on https://www.oracle.com/technetwork/database/multilingual-engine/overview/index.html
