### ISSUE TITLE
error when building a windows executable

### ISSUE THREAD

**Issue by crisarceramos** [rana/ora#27]
Hi Dev team,
I've been developing my Go application using below setup. I use Linux for dev\testing without any build\compile issue, but I need to build a windows executable for production. When I perform "env GOOS=windows GOARCH=386 go build" under the project directory I get this error message:
   gopkg.in/rana/ora.v2
../gopkg.in/rana/ora.v2/conn.go:52: undefined: Env
../gopkg.in/rana/ora.v2/conn.go:53: undefined: Srv
../gopkg.in/rana/ora.v2/conn.go:54: undefined: Ses

OS: Linux Mint
GO env:
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/myHome/Projects/goWorkspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by crisarceramos** [comment]
Could it be that when compiling\building a windows exe i need to set the below env var and point it to correct window file so that I can build a windows exe?

CGO_CFLAGS=-Ic:/oracle/home/OCI/include/
CGO_LDFLAGS=c:/oracle/home/BIN/oci.dll

**Comment by tgulacsi** [comment]
absolutely. But I'm not sure about the CGO_LDFLAGS (some flag may be needed
there, too).

---
https://onename.com/tgulacsi

2015-08-26 3:40 GMT+02:00 crisarceramos <notifications@github.com>:

**Comment by crisarceramos** [comment]
tried again cross compiling. using linux env, i tried to build a windows executable and I still got above errors even if I set the oracle instant client (header, dlls) env variable. I tried to compile ora.v3 as windows and got same error: 

/goWorkspace/src/gopkg.in/rana/ora.v3$ env GOOS=windows GOARCH=amd64 CGO_CFLAGS=-I/myhome/oracle/instantclient_12_1_win/sdk/include CGO_LDFLAGS=-L/myhome/oracle/instantclient_12_1_win go build -v -x
WORK=/tmp/go-build885933467
gopkg.in/rana/ora.v3
mkdir -p $WORK/gopkg.in/rana/ora.v3/_obj/
mkdir -p $WORK/gopkg.in/rana/
cd /goWorkspace/src/gopkg.in/rana/ora.v3
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/gopkg.in/rana/ora.v3.a -trimpath $WORK -p gopkg.in/rana/ora.v3 -complete -buildid a3bb14d0afcfa81af021b33cf613285a3308e338 -D _/goWorkspace/src/gopkg.in/rana/ora.v3 -I $WORK -pack ./conn.go ./const.go ./doc.go ./drvExecResult.go ./drvQueryResult.go ./drvStmt.go ./logger.go ./orm.go ./rsetCfg.go ./stmtCfg.go ./util.go
# gopkg.in/rana/ora.v3
./conn.go:51: undefined: Env
./conn.go:52: undefined: Srv
./conn.go:53: undefined: Ses
user@host:/goWorkspace/src/gopkg.in/rana/ora.v3$

**Comment by rana** [comment]
Hi,

Would you try removing the import statement in the ora

**Comment by crisarceramos** [comment]
good news, i was able to cross-build windows exe from linux with below link. anyways thanks dev team for helping me out!
https://groups.google.com/forum/#!msg/golang-nuts/AlQvxD7wv30/dNNDUuSyTgoJ
