### ISSUE TITLE
error building on ubuntu

### ISSUE THREAD

**Issue by anuragsoni** [rana/ora#28]
I was following the installation instructions for the package. I installed the oracle instant client and the sdk and then used the env script to verify that I had set the correct environment variables. When i try to go get the package I'm getting an error 
warning: libnnz11.so, needed by /usr/lib/oracle/11.2/client64/lib/libclntsh.so, not found

I'm working on Ubuntu 14.04 and with instant client version 11.2.0.4

**Comment by tgulacsi** [comment]
What does ldd /usr/lib/oracle/11.2/client64/lib/libclntsh.so missing?

Add /usr/lib/oracle/11.2/client64/lib to /etc/ld.so.conf and run export
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/oracle/11.2/client64/lib
2015. aug. 14. 23:01 ezt írta ("Anurag" <notifications@github.com>):

**Comment by anuragsoni** [comment]
Your comment on the goracle issue helped. I'll close this issue now.
