### ISSUE TITLE
Underflow error

### ISSUE THREAD

**Issue by fils** [rana/ora#33]
The following works well with goracle, but I compiled successfully ora and dropped it in:

	conn, err := sql.Open("ora", "USERNAME/PASSWORD@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xx.xx.xx.xx)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=orcl.xxx.xxx.org)))")

but with ora there and 

func init() {
	ora.Register(nil)
}

added I get

2015/09/03 15:29:50 Ready to connect
2015/09/03 15:29:52 Env.ociError OCI-22054: underflow error
exit status 1

ideas?

**Comment by tgulacsi** [comment]
What's the client library's version, and which commit do you use from rana/ora?

**Comment by fils** [comment]
I did a go get gopkg.in/rana/ora.v2

**Comment by fils** [comment]
I am one version back on go, but I assume there is no issue there.  go version go1.4.2 darwin/amd64

**Comment by rana** [comment]
Would you try gopkg.in/rana/ora.v3 and see if you get the same results?

**Comment by fils** [comment]
This is a reference to my code:  https://gist.github.com/fils/ffb99e48bc3e994d54f1
I've tried to remove IP's and user/pass stuff

Please forgive the sloppy all over the place testing...  :)  

I'll try the newer v3 version you reference.

**Comment by fils** [comment]
I compiled the v3 code and substituted it into the code.  Still get:

Doug-Fils-MBP:ocdJanus dfils$ go run main.go
2015/09/03 19:01:07 Ready to connect
2015/09/03 19:01:16 Env.ociError OCI-22054: underflow error
exit status 1

**Comment by tgulacsi** [comment]
Sorry, but which line produces that error?
2015. szept. 4. de. 2:02 ezt írta ("Douglas Fils" <notifications@github.com

**Comment by fils** [comment]
It seems to be coming right at the 

	for rows.Next() {

line 105 in the janus.go in the gist.   

If I do nothing more than replace "ora" with "goracle" (and comment out the init and import of course) then the code runs fine other than, goracle is giving me {0 true} for items that return nil in Oracle GUI client used for testing.  I am using the sql.NullFloat64 there.   (the issue is over in goracle us you know)

thanks....  appreciate everyones time

**Comment by tgulacsi** [comment]
Please instrument
https://github.com/rana/ora/blob/issue33/z_oracle_test.go#L2671 with the
data from your record(s) and fix the table creation code at line 2650, to
mirror your case, and reproduces the issue!

---
https://onename.com/tgulacsi

2015-09-04 15:01 GMT+02:00 Douglas Fils <notifications@github.com>:

**Comment by fils** [comment]
@tgulacsi  are there some steps you need me to take on my end with this?  If I pull the code down via git is there some go test I can do that will help you?   Just wanted to know if there was something you were needing from me.

**Comment by tgulacsi** [comment]
@fils I want you to
1. check that the "CREATE TABLE test_janus ..." creates a table as close to yours as possible,
2. instrument that file / write here the records that reproduces the problem.
For this, you may want to first count & log the records, then in a second select&iterate check which exact record produces the error, then inject that into the issue33's "INSERT ..." part, and check that it reproduces the problem.

Maybe this is too much to ask, decide yourself what is possible. Any information along that (2.) road will help us, though.

**Comment by fils** [comment]
not too much to ask at all...   my partner on this project is the Oracle DBA of the two of us though, so it will be Tuesday (Sept 8th) before we can try.   We will do all we can and get back to you.   Really appreciate the help.

**Comment by fils** [comment]
We created a test code and have been playing with it quite a bit today.   The code we used is at:  https://gist.github.com/fils/b7ffd6c2763a47ba908b 

I am able to reproduce our error.  I will will try and bullet out the items

* if at line 82, I define a value below 1 for what is defined as a NUMBER I will get the underflow error  (all this is oracle 12c).  Here I used 0.8.
* However, if we go to the database and inspect the stored number via sqlplus, we see 0.8 stored.
* Also, we can use a python driver (cx_Oracle) and get back that 0.8 value with no issue
* If I change that to something above 1 I can get it.  However, all floats like the 9.99,  that is also in that record, also come back at ints.  floored down, so in this case 9.   
* Again, via sqlplus, 9.99 is in fact stored  and can be accessed by other drivers and means.  

I hope this helps....

**Comment by tgulacsi** [comment]
Thanks!

With this, it is easy to reproduce. Now I see that the problem is that for NUMBER columns, Int64 is used for SELECTs. I need some more time to find out why and how to fix it, though.

**Comment by tgulacsi** [comment]
Hi, can you test the issue33 branch? (cd $GOPATH/src/gopkg/rana/ora.v3 && git fetch origin && git checkout -f master && git checkout -b issue33 origin/issue33)

**Comment by fils** [comment]
will, do..  I will be away from my computer for 24 hours though, so  will get back to this when I return

**Comment by rana** [comment]
Thank you Tamás.
Nice work

**Comment by fils** [comment]
Tamás,  I got to this today and I was able to pull, build and test the new version.  Looks good!

Thanks SO much for tracking this down!

**Comment by tgulacsi** [comment]
Glad I could help - our common goal is to provide Go with a usable Oracle
client, as a few of us has to use it...
2015. szept. 10. du. 4:27 ezt írta ("Douglas Fils" <notifications@github.com
