### ISSUE TITLE
Please add some examples or docs for how to use ora

### ISSUE THREAD

**Issue by yourchanges** [rana/ora#34]
Please add some examples or docs for how to use ora

**Comment by rana** [comment]
Are you looking for installation instructions or coding instructions? If you can be more specific i will put something together for you.

**Comment by yourchanges** [comment]
The  coding instructions, see :
https://github.com/go-goracle/goracle/tree/v1/examples

2015-09-10 2:48 GMT+08:00 Rana Ian <notifications@github.com>:

**Comment by tgulacsi** [comment]
Shall I port them to ora, will it help?

---
https://onename.com/tgulacsi

2015-09-10 14:27 GMT+02:00 yourchanges <notifications@github.com>:

**Comment by rana** [comment]
Tamás,

Yes, please. I think that would help.

**Comment by tgulacsi** [comment]
See https://github.com/rana/ora/commit/515ecbd2f3b670d13cc6ab060893bebac2fbdce1
