### ISSUE TITLE
inexplicit memory error in ora.Register() when oracle client is not confgured properly

### ISSUE THREAD

**Issue by evgenybf** [rana/ora#35]
OS: Win7x64, Go1.5x64, Msys64, oci.dll from instantclient-basiclite-windows.x64-12.1.0.2.0.zip

Remove oci.dll and its stuff from PATH, put only oci.dll into a folder where your application is, call ora.Register(nil). It will panic with the following message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4bf7dc]

goroutine 1 [running]:
gopkg.in/rana/ora%2ev3.Register(0xc082008340)
        C:/Develop/Go/gopath/src/gopkg.in/rana/ora.v3/ora.go:144 +0xbc
main.init.1()
        C:/Develop/Go/gopath/src/db2cvs/db2cvs.go:15 +0x10f
main.init()
        C:/Develop/Go/gopath/src/db2cvs/db2cvs.go:54 +0x51

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1696 +0x1
```

Investigation results:
OpenEnv() returns an error, but its value is ignored, then it's trying to set a value to env.cfg.StmtCfg, but it hasn't been initialized property and we have that memory error...

```
		env, err := OpenEnv(nil)
		if err != nil {
			errE(err)   <-- I guess that it should be panic(errE(err)) or return err or so
		}
		// database/sql/driver expects binaryFloat to return float64 (not the Rset default of float32)
		env.cfg.StmtCfg.Rset.binaryFloat = F64  <---- error: assignment to a nil pointer
```

OpenEnv error:
```
OpenEnv Unable to create environment handle (Return code = -1).
```

**Comment by crisarceramos** [comment]
i don't use ora.register(nil) but my code works. try to remove it. 
also put the below dlls on your exe path.
oci.dll
oraociicus12.dll
oraons.dll

**Comment by evgenybf** [comment]
crisarceramos, sorry, it seems we are not on the same page. I know how to fix it, thanks. I just noticed that ora.register() falls because of null pointer error when it should just pass error message occured in OpenEnv to the higher level.

**Comment by rana** [comment]
Thanks for pointing that out. Will try to reproduce and fix.

**Comment by tgulacsi** [comment]
Easy to reproduce, just "go test" with empty ORA env vars.
2015. szept. 10. du. 6:19 ezt írta ("Rana Ian" <notifications@github.com>):

> Thanks for pointing that out. Will try to reproduce and fix.
>
