### ISSUE TITLE
working with Lob

### ISSUE THREAD

**Issue by anuragsoni** [rana/ora#37]
I'm using the package to read content from a table where one column is a Blob. According to the documentation I thought i need to use a Lob. 

I prepare my query like this
```go
stmtQry, err := ses.Prep(
		"SELECT CONTENT FROM TABLENAME WHERE",  ora.Bin)
```

while reading the content if i use ```fmt.Println(rset.Row[3])``` i can print it out. But I wanted to encode the response to Json. I tried to store the value in an ora.Lob field but i'm getting an error:
 interface is *ora.lobReader, not ora.String.

It'd be nice to have an example of how to read blobs or handle Lob fields.

**Comment by tgulacsi** [comment]
See https://github.com/rana/ora/blob/master/z_oracle_test.go TesLobSelect for an example.

The trick is to select into an interface{} and type assert it into an io.Rerader.

**Comment by anuragsoni** [comment]
Thank you!
