### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by wahmedswl** [rana/ora#39]
Hi, 
   getting following error in go get

```
C:/Go/bin/go.exe get -v . [D:/Workspace/Go-Ide/GOPATH/src/tutorial]
gopkg.in/rana/ora.v3
# gopkg.in/rana/ora.v3
cc1.exe: fatal error: C:/instantclient-sdk-win64-10.2.0.5/instantclient_10_2/sdk/include/: Permission denied
compilation terminated.
..\gopkg.in\rana\ora.v3\bndBfile.go:8:17: fatal error: oci.h: No such file or directory
compilation terminated.
```

Here is my machine information

```
TDM-GCC-64
Windows Server 2208 R2-SP1
go version go1.3.1 windows/amd64
```

Any help would be appreciated.

**Comment by rana** [comment]
Hi,

Was your instantclient-sdk installed under a different account than what you are compiling under? 
Can you grant read/write permission to the C:/instantclient-sdk-win64-10.2.0.5/instantclient_10_2/sdk/include/ directory for your account?

**Comment by wahmedswl** [comment]
Hi,
   Basically, i have installed full client than instant client. I have downloaded the instantclient-sdk-win64-10.2.0.5.zip from oracle website and extracted it.

I have given Everyone read/write permissions to the folder, so it shouldn't give up this error. There is a strange thing though, instant client folder is read-only and when i change that it again set as read-only. Will try to install Instant Client on separate machine and will again update the ticket.

Thanks for your feedback
