### ISSUE TITLE
Help request: Building on Windows 10 64 bit with MinGW-W64 getting undefined reference

### ISSUE THREAD

**Issue by MichaelS11** [rana/ora#40]
Greetings,

Was wondering if I could get some help building on Windows 10 64 bit with MinGW-W64? Getting undefined reference. Not sure where the issue is, maybe something because of Windows 10?

versions:
go version go1.5.1 windows/amd64
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.2.0
instant client 11.2.0.4 64 bit

Path has C:\app\instantclient_11_2_64\;C:\app\Go\bin;C:\app\mingw64\bin

Flags:
CGO_CFLAGS=-IC:\app\instantclient_11_2_64\sdk\include\
CGO_LDFLAG=-LC:\app\instantclient_11_2_64\sdk\lib\msvc\ -lstdc++ -loci

go install -v test

```
test/_third_party/github.com/rana/ora
# test/_third_party/github.com/rana/ora
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndBfile.cgo2.o:bndBfile.cgo2.c:(.text+0xc9): undefined reference to `OCIBindByPos'
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndBfile.cgo2.o:bndBfile.cgo2.c:(.text+0x150): undefined reference to `OCIDescriptorAlloc'
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndBfile.cgo2.o:bndBfile.cgo2.c:(.text+0x1ad): undefined reference to `OCIDescriptorFree'
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndBfile.cgo2.o:bndBfile.cgo2.c:(.text+0x24e): undefined reference to `OCILobFileSetName'
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndBinSlice.cgo2.o:bndBinSlice.cgo2.c:(.text+0x5b): undefined reference to `OCIBindArrayOfStruct'
C:\Users\myuser\AppData\Local\Temp\go-build291446222\test\_third_party\github.com\rana\ora\_obj\bndFloat32.cgo2.o:bndFloat32.cgo2.c:(.text+0x45): undefined reference to `OCINumberFromReal'
...
```

Any thoughts?

Appreciate any help provided.

**Comment by tgulacsi** [comment]
Just a half-blind shot in the gray: OCIBindByPos2 is missing (which shall be used with 11.2).
These are defined for ora in version.h. Maybe the version macro defined there is bad or something?

**Comment by rana** [comment]
Michael,

Would you try downloading and compiling with http://gopkg.in/rana/ora.v3
and see if there is a difference?

**Comment by MichaelS11** [comment]
Thank you @rana for your help.

I tried with version 3 or ora and had the same issue. I also tried ora with the instant client 12.1.0.2 and same errors. I do not think it is an issue with the code. I also tried the go Oracle driver that is a translation of the Python cx_Oracle and it gave very similar errors.

**Comment by rana** [comment]
Michael,

Would you uninstall mingw64, install (TDM GCC)[http://tdm-gcc.tdragon.net/download] and test?

**Comment by MichaelS11** [comment]
Thought the same thing, same errors :/

**Comment by ricsmania** [comment]
Hello @MichaelS11, I think you might have misspelled your CGO_LDFLAGS variable, it should have a S in the end. I'm using a similar setup and everything works:

Windows 10
Go 1.5.1 64
Mingw64
Oracle instant client 12.1

CGO_CFLAGS=-Ic:\oracle\instantclient_12_1_64\sdk\include
CGO_LDFLAGS=-LC:\Oracle\instantclient_12_1_64\sdk\lib\msvc -loci
PATH=/c/go/bin:/c/projetos/go/bin:/c/MinGW_64/mingw64/bin:/c/oracle/instantclient_12_1_64

**Comment by MichaelS11** [comment]
Oh my goodness! Fail on my part. Thank you very much!
