### ISSUE TITLE
Possible issue with result.LastInsertId() for Exec query

### ISSUE THREAD

**Issue by MichaelS11** [rana/ora#43]
The below Oracle sql is just to show that the returning statement for a insert can be just about any type. The below example is using a varchar.

create table TEST1
  (
  DATA1 number(20) not null,
  DATA2 varchar2(50) not null
  )
  tablespace USERS pctfree 10 nologging;

declare
  l_char varchar2(512);
begin

insert into TEST1 (DATA1, DATA2) values (1, 'test1') returning DATA2 into l_char;
commit;

DBMS_OUTPUT.PUT_LINE(l_char);

end;
/

When looking at the Go code, can do the following:

var myId string = "default"

result, err := db.Exec("insert into TEST1 (DATA1, DATA2) values (:1, :2) returning DATA2 into :3", 2, "test2", myId)
if err != nil {
  fmt.Println(err)
}
fmt.Println(result2)

And get the error:

DrvStmt.Exec Stmt.exe Env.ociError ORA-01722: invalid number

I am not exactly sure what the goal is of lastInsertId since it is set to be an int64 but seems like the below code in stmt.go is not doing want is wanted:

if strings.Contains(sqlEnd, "RETURNING") {
  params[len(params)-1] = &lastInsertId
}

Also to note, if you do set your returning variable to a int64 instead of say a string, the lastInsertId gets changed from a default 0 to a 1 from when the below line is called:

err = stmt.setBindPtrs()

Was not sure exactly why, but I figured it would be easier for you to figure it out if needed.

Could you look into the result.LastInsertId() and see if it doing what is wanted?

**Comment by tgulacsi** [comment]
I think LastInsertID is just undefined for Oracle, so the existing code is just a hack.
I'd delete it and document the undefinedness of LastInsertID and the usage of the "RETURNING" statement.

**Comment by MichaelS11** [comment]
Cool, thank you :)

**Comment by tgulacsi** [comment]
I'll wait for an amen from Rana Ian...

**Comment by rana** [comment]
Hi Michael, Tamás, 

The design of the [&lastInsertId](https://github.com/rana/ora/blob/master/stmt.go#L174) is to intentionally support the Go [Result interface](https://golang.org/pkg/database/sql/#Result) method LastInsertId() in the [database/sql](https://golang.org/pkg/database/sql) package.

The LastInsertId() (int64, error) method returns an int64. So the driver supports the interface with [&lastInsertId](https://github.com/rana/ora/blob/master/stmt.go#L174). Some compromises needed to be made to bridge the Oracle database and Go libraries. This was one such compromise. 

You are correct that Oracle SQL syntax allows returning multiple variables of any type and that the current driver doesn't support it. It wasn't clear to me that anyone uses that feature. I think the majority of use cases is to support a numeric identity column updated with an Oracle sequence. The driver does have Oracle-only features in the driver which are not accessible from the database/sql package. I'm fine with adding this feature while still supporting the existing functionality. 

What do you think?

Thank you,

Rana

**Comment by MichaelS11** [comment]
Sounds good to me. I am not using it at the moment, just thought you should know. Thank you for your help. :)

Just to note it does not seem like the LastInsertId is working as of now.

**Comment by tgulacsi** [comment]
@rana see https://github.com/mattn/go-oci8/blob/master/oci8.go#L1103 and https://github.com/go-goracle/goracle/blob/v1/driver.go#L198 : they're just return an error for LastInsertID, as it is impossible to implement it without severe flaws.

I'm suggesting you to do the same, and remove this functionality - add some documentation and return an errors.New("not implemented - use RETURNING statement") or sth like that.

**Comment by C-Pro** [comment]
@tgulacsi please, leave it as it is :)
We can not use returning statement through database/sql, and as far as I know, this hack is the only way to get last inserted Id now! (except not using database/sql)

**Comment by tgulacsi** [comment]
Maybe some clarification in the docs, and marking the value for LastInsertID as such:

if strings.Contains(sqlEnd, "RETURNING") && strings.Contains(sqlEnd, "lastInsertID") {
  params[len(params)-1] = &lastInsertId
}

So iff "RETURNING xx lastInsertID" will treat the last param as the lastInsertId.

This way if you want lastInsertID, you can have it, but this won't interfere with other RETURNING use cases.
?

**Comment by rana** [comment]
Go for it, if you can reach the functionality in an improved way, or
document it that's fine
