### ISSUE TITLE
Return nil pointer for null date when using *time.Time

### ISSUE THREAD

**Issue by ricsmania** [rana/ora#45]
When using a *time.Time variable to scan a date column, and the value is null on the database, the result is something like this: "-0001-11-30 00:00:00 +0000 +00:00"

I think it would make much more sense if it just returned a nil pointer for null values. Would that be a viable change?

**Comment by tgulacsi** [comment]
I'd use something that can be nullable (ora.Time, for example) - but tweaked the code to use time.Time{} for nulls - see "issue45" branch.

**Comment by ricsmania** [comment]
Thanks for the suggestions @tgulacsi.

I tried your branch. The problem with time.Time{} is that it is serialized as "0001-01-01T00:00:00Z", I need something that can be serialized as null.

I also had tried ora.Time, but it doesn't seem to work with the database/sql package.

I made a very crude test to return nil and it worked. To test I set nil to the value if the year is < 0. I did that because getTime doesn't return a pointer, so I can't return nil from there.

```go
func (def *defTime) value() (value interface{}, err error) {
	if def.isNullable {

		oraTimeValue := Time{IsNull: def.null < C.sb2(0)}
		if !oraTimeValue.IsNull {
			oraTimeValue.Value, err = getTime(def.rset.stmt.ses.srv.env, def.ociDateTime)
		}
		value = oraTimeValue

	} else {
		
		date, err := getTime(def.rset.stmt.ses.srv.env, def.ociDateTime)
		if date.Year() < 0 {
			value = nil
		} else {
			value, err = date, err
		}

	}
	return value, err
}
```

I could create a custom type to do that, but it would be much better to stick to *time.Time if possible.

What do you think?

**Comment by tgulacsi** [comment]
Can you try dfe714e ?

To be honest, I don't really know what can/shall be returned to database/sql from its Driver interface, that's allowed and works. Now it seems that a nil is allowed and database/sql does the right thing, by setting a *time.Time to nil, and a time.Time to its zero value.

**Comment by ricsmania** [comment]
Awesome @tgulacsi, it seems to be working now, thanks! I'll test it for a few days, and if everything works I'll close the issue, ok?
