### ISSUE TITLE
getting 'exit status 3221225595' when trying to run a simple connect test

### ISSUE THREAD

**Issue by klauern** [rana/ora#47]
I seem to be getting an error when importing the package:

```powershell
C:\dev\golang\src\github.com\klauern\ora-things
λ $env:CGO_CFLAGS
-IC:\instantclient_12_1\sdk\include
C:\dev\golang\src\github.com\klauern\ora-things
λ $env:CGO_LDFLAGS
C:\instantclient_12_1\oci.dll
C:\dev\golang\src\github.com\klauern\ora-things
λ go get -u gopkg.in/rana/ora.v3
```

I'm trying to use this package, but I don't know how to debug this issue I'm seeing.  I've tried to simplify this to as small as possible.

```go
package main

import (
	_ "gopkg.in/rana/ora.v3"

	"fmt"
)

func main() {
	fmt.Println("Hi")
}
```

```powershell
C:\dev\golang\src\github.com\klauern\ora-things
λ go run .\simple.go
exit status 3221225595
C:\dev\golang\src\github.com\klauern\ora-things
λ go version
go version go1.5.1 windows/amd64
```

Are there any ways to figure out what could be causing the issue, or even what this exit status means?  I'm really confused.

**Comment by rana** [comment]
Hi Nick,

Can you try resetting your env variables using forward slashes? I think Go is used to unix format only. For example, for your installation:

CGO_CFLAGS=-IC:/instantclient_12_1/sdk/include/
CGO_LDFLAGS=C:/instantclient_12_1/oci.dll

If that doesn't work I would try the [TDM GCC](http://tdm-gcc.tdragon.net/download) compiler if you aren't already.

Let me know how it goes.

Thank you,

Rana

**Comment by ricsmania** [comment]
@klauern do you have msvcr100.dll (64 bit) somewhere in your PATH? If not, try installing this: http://www.microsoft.com/en-us/download/details.aspx?id=14632

**Comment by tgulacsi** [comment]
Maybe this is 'cause we now (since 954d56e7189eefb8826663fcaec1d450ba44e42e) automatically call ora.Register, and if the DLL is not loadable, then it panics.

The cause is the missing/misconfigured DLL, but the symptom (error on import) is 'cause the automatic import calls OpenEnv right on import.

**Comment by klauern** [comment]
@rana I changed it to forward slashes (/), but the same result came back

@ricsmania I tried downloading that, but I got an error 
![image](https://cloud.githubusercontent.com/assets/4735/10787899/f21aee18-7d41-11e5-9d70-a249ad684934.png)

**Comment by klauern** [comment]
As for what I *do* have installed, here's the list of Visual C++ things:

![image](https://cloud.githubusercontent.com/assets/4735/10787967/43ebff66-7d42-11e5-9940-773cd9409312.png)

**Comment by ricsmania** [comment]
@klauern ok, it seems that a lack of VC++ won't be a problem lol. Can you please check that:

1. Your Oracle client is 64 bit
2. C:\instantclient_12_1 is in your PATH

I managed to reproduce the exact same error (exit status 3221225595) by putting only the 32 bit version in my PATH and trying to run with 64 bit Go. When I removed it from PATH I got error 3221225781 instead.

**Comment by klauern** [comment]
Ah, that did it.  I didn't have `c:\instantclient_12_1` in my path, and--because it was pushed to my machine from IT-upon-high--I had a much older (and probably 32-bit) `c:\ORACLE\ora102` in my path as well.

**Comment by klauern** [comment]
The fix for me was just ensuring that the `C:\instantclient_12_1` preceded other things in my path and the import worked.  I still have some issues with my code, but I don't get the error anymore.

**Comment by klauern** [comment]
I don't see anything in the [installation instructions](https://github.com/rana/ora#installation) about putting that in my path, so that could be why things didn't work.  I simply downloaded and unzipped the instant client on my computer and set those two `CGO_` flags.

**Comment by ricsmania** [comment]
Glad to hear it worked @klauern. Maybe it's not in the installation instructions because this is not required to build the application, only to run it. But a reminder there would definitely help.
