### ISSUE TITLE
Connection Pooling in Ora driver ?

### ISSUE THREAD

**Issue by jmptrader** [rana/ora#50]
Please considered in your roadmap the support of Connection Pooling  in Ora driver.

The "database/sql"  works but in real cases for applications 7x24, I have random behavior for keep connections alive.

I refer to Oracle Connection Pooling done by OCI.

Thank's,
JM

###### Connection pools 

Connection pooling is the use of a group (the pool) of reusable physical connections by several sessions, in order to balance loads. The management of the pool is done by OCI, not the application. Applications that can use connection pooling include middle-tier applications for Web application servers and e-mail servers.

###### Session Pools 

Session pooling means that the application will create and maintain a group of stateless sessions to the database. These sessions will be handed over to thin clients as requested. If no sessions are available, a new one may be created. When the client is done with the session, the client will release it to the pool. Thus, the number of sessions in the pool can increase dynamically.

**Comment by rana** [comment]
Hi JM,

Will consider it. I did look into OCI connection pooling when initially designing the driver but considered too much effort for a first version for a feature which might not be used and already has support in database/sql.  

What sort of behavior are you seeing Oracle connections using database/sql? 

Aside from database/sql, my understanding is that Oracle will itself close connections within a connection pool after a period of inactivity.

Thank you,

Rana

**Comment by tgulacsi** [comment]
Session pooling is nice, but I couldn't make it work with our external authentication (Oracle Wallet) in cx_Oracle.

Also, expermients shows that to use n processors, you have to use n separate Srvs.

But against frequent session reopening, some pooling should be used. A general IdlePool is at github.com/tgulacsi/go/pool, and a WIP connection (Srv/Ses) pool is in the "pool" branch here.

**Comment by jmptrader** [comment]
It's  cool. Thank's.

**Comment by tgulacsi** [comment]
I've split the pooling into Env.NewSrvPool + Srv.NewSesPool, as I couldn't make the srv+ses pooling leak free: you can open any number of sessions on a connection, but can only close/release that connection back to its pool when all sessions are closed on it. And closed, not just released to the pool...
