### ISSUE TITLE
first call to ora.Rset.Next() is slow

### ISSUE THREAD

**Issue by crisarceramos** [rana/ora#51]
Hi Dev team,
I developed a golang middle app to call an Oracle SP and generate XML from an ora,Rset returned.
So far the app is running fine. One thing I noticed is that the first call to Rset.Next() is taking too long and is the only part of the process that is causing the application to not return fast. Example code below. Please advise. Thanks.

	for refCursor.Next() {
		res := &result{}
		res.EChannel, _ = refCursor.Row[0].(string)
                .........

**Comment by tgulacsi** [comment]
Check your SQL's execution plan, as this means the SQL (query) is slow.

**Comment by crisarceramos** [comment]
Hi tgulacsi thanks for your advice. i tested the same SP in production and it runs in just 25secs while the QA runs at over a minute, sometimes 2. Seems oracle environment\config issue. Closing this for now. Thanks!
