### ISSUE TITLE
Rset.Columns contains incorrect column names

### ISSUE THREAD

**Issue by maliutin** [rana/ora#52]
Hi

I am using:

    $ go version
> go version go1.5.1 windows/amd64

and "gopkg.in/rana/ora.v3"

I need to call following procedure:

    PROCEDURE get_customer(p_result     OUT SYS_REFCURSOR,
                           p_customer_id    NUMBER)
    AS
    BEGIN
        OPEN p_result FOR
        SELECT FIRST_NAME, LAST_NAME, AGE
        FROM customer
        WHERE customer_id=p_customer_id;
    END get_customer;

I used following go code:

    procRset := &ora.Rset{}
    stmt, _ := ses.Prep(commandText)
    stmt.Exe(procRset, customerID)
    fmt.Println(procRset.ColumnNames)

And, in result, we see that procRset.ColumnNames contains following array:  
>[FIRST_NAMELAST_NAMEAGE LAST_NAMEAGE AGE]  

I suppose that this is incorrect array and it should be:  
[FIRST_NAME LAST_NAME AGE]

**Comment by tgulacsi** [comment]
Can you try with the latest?
(cd $GOPATH/src/gopkg.in/rana/ora.v3 && git remote add upstream https://github.com/rana/ora.git && git fetch upstream && git checkout -b M upstream/master)

I think I've fixed just this error in https://github.com/rana/ora/commit/5cb40ba17f774d38b58ac95bc313f114a01d1d8e .

**Comment by it-proposition** [comment]
Hi.

Now it works correct. procRset.ColumnNames contains [FIRST_NAME LAST_NAME AGE] array.

When will it be in gopkg.in/rana/ora.v3?

**Comment by tgulacsi** [comment]
I'd delegate this question to @rana

**Comment by rana** [comment]
@tgulacsi What do i need to do to have your changes visible in the gopkg.in release?

**Comment by tgulacsi** [comment]
Just merge into the v3 branch.

Rana Ian <notifications@github.com> ezt írta (időpont: 2015. nov. 8., V,
22:29):

**Comment by C-Pro** [comment]
I have got into field name concatenation problem too. Please push this fix to gopkg.in release :)

**Comment by gabriellett** [comment]
Please push this fix to gopkg :D

**Comment by tgulacsi** [comment]
It should be at tag v3. (commit 5cb40ba17f774d38b58a)
