### ISSUE TITLE
How not trailling rigth space in VARCHAR2 field ...

### ISSUE THREAD

**Issue by jmptrader** [rana/ora#53]
Dear,

I have an table with field of varchar2(1024) , with valid  spaces ASCII 32 to rigth.

When I fetch records , the field value has loss trailing spaces?

Exists an option for disable this one?

Thanks,
JM

fragment code:
```
   stmtQry, err := testSes.Prep("SELECT field1 FROM table", ora.OraS )
    stmtQry.Cfg().Rset.SetVarchar(ora.OraS)
   ...
    rset, err := stmtQry.Qry()
   ......
    for rset.Next() {
        
        fmt.Println( len(rset.Row[0].(ora.String).Value) )
        msgStream <- rset.Row[0].(ora.String).Value
    }
```

**Comment by tgulacsi** [comment]
Please try the master branch, it has some changes which may help.

j <notifications@github.com> ezt írta (időpont: 2015. nov. 27., P 1:32):

**Comment by jmptrader** [comment]
Yesterday, before of test my code, I do :

go get -u -v gopkg.in/rana/ora.v3

It's fine?

Enviado desde mi BlackBerry de Movistar

-----Original Message-----

**Comment by tgulacsi** [comment]
That pulls the "v3" branch, you need the "master":
cd $GOPATH/src/gopkg.in/rana/ora.v3 && git branch -m master v3 && git
checkout -b master origin/master && git pull

j <notifications@github.com> ezt írta (időpont: 2015. nov. 27., P, 14:39):

**Comment by jmptrader** [comment]
OK.

I've followed these steps, one by one. But I'm still with the problem.

My field1 is varchar2 (1024), it contains text of the form:

"XXXXXXXXXXXXXX <S> <S> <S> <S>"

where <X> is any character and <S> are spaces.

I can not anticipate the effective length of the field.

Thank you.

**Comment by tgulacsi** [comment]
Ok, I have a reproduction: 314b3f295effa1a4b7525e8940b55b60297fae3c

**Comment by tgulacsi** [comment]
Wow, quite strange.
"SELECT 'spaces   ' FROM DUAL" works (see TestSpacesDual)!

BUT
"INSERT 'spaces   ' INTO tbl" binds the unaltered value (see TestSpacesTbl) but the value in the table is without spaces (the "only space" case errs out as cannot insert NULL into the field)!

**Comment by jmptrader** [comment]
It's great, thank's you.
