### ISSUE TITLE
Oracle DSN

### ISSUE THREAD

**Issue by jpillan** [rana/ora#54]
Trying to just connect to an Oracle db. Nothing fancy.  Can you all give and example of a DSN for the ora driver?

Here is what I'm using:

sql.Open("ora",
		"user/password@esdbd34.uits.xxxxxxx.xxx:1521/SID")

Just seems to terminate without doing anything. Not even an error message.

I use _"gopkg.in/rana/ora.v3" to import the package.

**Comment by tgulacsi** [comment]
Use tnsping to discover the Oracle-specific connection string, or assemble yours using this template:
"user/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP) (HOST=your.host.or.ip) (PORT=1521)) (CONNECT_DATA=(SERVICE_NAME=sid)))"
