### ISSUE TITLE
Failing to write large blob

### ISSUE THREAD

**Issue by C-Pro** [rana/ora#55]
I need to write jpeg files to blob field through stored procedure.
When I try to insert more then 32767 bytes I get "DrvStmt.Exec Stmt.exe Env.ociError ORA-01460: unimplemented or unreasonable conversion requested" as if my []byte is converted into varchar2 somewhere.

Schema and plsql function:

    create table "INTEGR"."PHOTO"
    (
              "PHOTO_ID" number(11,0) not null enable,
              "VEHICLE_UUID" NVARCHAR2(50) not null enable,
              "PHOTO" BLOB,
              "DHMS_MESSAGE" date not null enable,
              "TO_TREAT"     number(2,0) default 1 not null enable,
              constraint "PHOTO_ID_PK" primary key ("PHOTO_ID")
    );

    create sequence "INTEGR"."PHOTO_SEQ";

    create or replace function integr.add_photo(p_vehicle_uuid photo.vehicle_uuid%type,
                                                p_photo         photo.photo%type,
                                                p_dhms_message  photo.dhms_message%type,
                                                p_to_treat      photo.to_treat%type)
    return photo.photo_id%type as
      v_id   photo.photo_id%type;
    begin
        if nvl(dbms_lob.getlength(p_photo),0) = 0 then
            return null;
        end if;
        insert into integr.photo(photo_id,
                                 vehicle_uuid,
                                 photo,
                                 dhms_message,
                                 to_treat)
        values(0,
               p_vehicle_uuid,
               p_photo,
               p_dhms_message,
               p_to_treat)
        returning photo_id into v_id;
        return v_id;
    end;

Code:

    package main

    import(
        "fmt"
        "database/sql"
        "gopkg.in/rana/ora.v3"
    )

    func main(){
        ora.Register(nil);
        db, err := sql.Open("ora", "integr/integr@localhost:49161/xe")
        if err != nil {
           fmt.Println(err)
        }
        
        a := make([]byte,32767+1)
        
        //This inserts succsessfuly:
        //sql := "insert into photo values(photo_seq.nextval,'asdas',:1,sysdate,1)"

        //And this fails with "DrvStmt.Exec Stmt.exe Env.ociError ORA-01460: unimplemented or unreasonable conversion requested"
        sql := "declare v integer; begin  v:=integr.add_photo('asdas',:1,sysdate,1); end;"

        r, err := db.Exec(sql, a)
        if err != nil {
           fmt.Println(err)
        }
    }

**Comment by tgulacsi** [comment]
Search for clob ecamples, but you have to create the blob handle in the databas, retrieve it, write it as an io.Writer,and commit.

**Comment by tgulacsi** [comment]
See #37

**Comment by C-Pro** [comment]
Sorry, I could not find any examples writing blobs with this library. Only PHP Oci8 examples here: http://php.net/manual/ru/function.oci-new-descriptor.php
I tried like this, but failed miserably. And I suspect that it will not work anyway, because of the way database/sql treats out parameters (it does not return them).
I tried interface{}, byte[], bytes.Buffer, *bytes.Buffer as third parameter to
`tx.Exec("insert into photo values(photo_seq.nextval,'asdas',empty_blob(),sysdate,1) returning photo_id into :1", b, HERE)` but it all failed. Each time I have empty blob in database.

    package main

    import(
        "fmt"
        "database/sql"
        "gopkg.in/rana/ora.v3"
        "io"
        "bytes"
    )

    func main(){
        ora.Register(nil);
        db, err := sql.Open("ora", "integr/integr@localhost:49161/xe")
        if err != nil {
           fmt.Println(err)
        }

        lob_len := 32767+1
        a := make([]byte, lob_len)

        var buf bytes.Buffer
        var b int64
        //var i interface{}
        tx, _ := db.Begin()

        m, err := buf.Write(a)
        if err!= nil || m < lob_len {
            fmt.Errorf("Failed to write buf: %v\n", err)
            return
        }

        sql := "insert into photo values(photo_seq.nextval,'asdas',empty_blob(),sysdate,1) returning photo_id into :1"

        r, err := tx.Exec(sql, b)
        if err != nil {
           fmt.Println(err)
        }
        b, err = r.LastInsertId()
        fmt.Println(b)

        sql = "update photo set photo=empty_blob() where photo_id = :1 returning photo into :2"

        r, err = tx.Exec(sql, b, &buf)
        if err != nil {
           fmt.Println(err)
        }
        n, err := io.Copy(&buf,bytes.NewReader(a))
        if err != nil {
			    fmt.Errorf("Write err: %v", err)
	    }
	    fmt.Printf("n=%d\n", n)
        tx.Commit()
    }

**Comment by tgulacsi** [comment]
I didn't have time to try it, but something like below should work:

```
package main

import(
    "fmt"
    "database/sql"
    "gopkg.in/rana/ora.v3"
    "io"
    "bytes"
)

func main(){
    ora.Register(nil);
    db, err := sql.Open("ora", "integr/integr@localhost:49161/xe")
    if err != nil {
       fmt.Println(err)
    }

    tx, _ := db.Begin()

    sql := "insert into photo values(photo_seq.nextval,'asdas',empty_blob(),sysdate,1) returning photo_blob into :1"

    var blob *ora.Lob
    r, err := tx.Exec(sql, &blob)
    if err != nil {
       fmt.Println(err)
    }
    n, err := io.Copy(blob, bytes.NewReader(make([]byte, 32767+1)))
    if err != nil {
            fmt.Printf("Write err: %v", err)
    }
    fmt.Printf("n=%d\n", n)
    if err := tx.Commit(); err != nil {
        fmt.Printf("Commit err: %v", err)
    }
}
```

**Comment by C-Pro** [comment]
I looks like we could not write to ora.Lob:

     cannot use *blob (type ora.Lob) as type io.Writer in argument to io.Copy:
	    ora.Lob does not implement io.Writer (missing Write method)

**Comment by tgulacsi** [comment]
Now I don't know a way to write using database/sql, but I've added an example how to do it, into z_example_test.go, line 1532.

**Comment by C-Pro** [comment]
Thanks, but insert worked ok in my first example. Stored proc did not.
