### ISSUE TITLE
 cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by akarmakar** [rana/ora#61]
getting and error while Get / Exec Issue.
"Ses.Prep.func1 recovered: runtime error: cgo argument has Go pointer to Go pointer"
Not sure what i am doing wrong  :(

**Comment by tgulacsi** [comment]
Nothing wrong; are you using Go1.6 ?
Then try the go1.6 branch!

**Comment by akarmakar** [comment]
Thx for the reply .Yes I am on Go 1.6.
Let me give it a try. Thx again.

**Comment by akarmakar** [comment]
When i am doing go get " go get github.com/rana/ora" its give me error "expects import "gopkg.in/rana/ora.v3" . even if i had gopkg.in/rana/ora.v3.

**Comment by tgulacsi** [comment]
cd $GOPATH/src/gopkg.in/rana/ora.v3
git fetch origin
git checkout -b go1.6 origin/go1.6
go install

**Comment by akarmakar** [comment]
awesome !!! thx a lot it worked.
