### ISSUE TITLE
Is it possible to support sql.QueryRow function. 

### ISSUE THREAD

**Issue by omerkirk** [rana/ora#63]
This is only a feature request and not an issue, since QueryRow can be implemented as the first row of Query. However this causes very ugly code while using database/sql.

I would be glad to work on it if there is no reason this is not implemented.

**Comment by tgulacsi** [comment]
stmt.QryRow, stmt.PrepAndQryRow, returning the rset.Row ([]interface{}) and error?

Please create a PR!

**Comment by omerkirk** [comment]
@tgulacsi I assumed that QueryRow wasn't working since it was written as such in the README. But while I was checking the database/sql code it seems that QueryRow isn't a function dependent on the driver. Please correct me if I am wrong. This is the implementation: 

```
func (db *DB) QueryRow(query string, args ...interface{}) *Row {
        rows, err := db.Query(query, args...)
  	return &Row{rows: rows, err: err}
}
```

And the statement code is similar. So this looks like a utility function around Query. Am I missing something ?

**Comment by tgulacsi** [comment]
No, this is a general function - just as everything in database/sql.
I've thought you want a similar utility funtion for the ora-specific
ora.Stmt type.

Be warned though that QueryRow closes the query on return - usually not a
problem, except when it is: when you want to use the returned handler, such
asa LOB handler - in that case, use Query, and close by han d.


omerkirk <notifications@github.com> ezt írta (időpont: 2016. febr. 23., K,
17:07):

**Comment by omerkirk** [comment]
I assumed QueryRow is an optional interface function that the drivers can choose to implement since it is allowed to not support it. Sorry for that. I'll close this issue.
