### ISSUE TITLE
Nested rsets from procedure call

### ISSUE THREAD

**Issue by snop-snov** [rana/ora#66]
Hi!
I need to get cursor with nested cursor from procedure call. Now rset does not support attrs with oci type C.SQLT_RSET. Do you consider the ability to add processing data of this type?
Just in case, here's an example procedure:
```sql
create or replace procedure example_proc(p_out_cur out sys_refcursor) is
begin
    open p_out_cur for
      select m.id,
             m.name,
             cursor (select a.internal_file_name, q.name
                     from media_assets a, asset_file_types_dict q
                     where a.media_id = m.id
                     and q.id = a.file_type_id)               assets_cursor

      from media m;
end example_proc;
```

**Comment by tgulacsi** [comment]
I've started stg, see issue66 branch.
Needs tests, and not tested yet at all, just compiles!

**Comment by snop-snov** [comment]
Thank you! I'll try to add some tests if you don't do it faster =)

**Comment by tgulacsi** [comment]
Thanks!

Does it still work after my small change (pull from the pool)?

**Comment by snop-snov** [comment]
Yes, it works fine too!
