### ISSUE TITLE
How can we use the latest version of ora

### ISSUE THREAD

**Issue by omerkirk** [rana/ora#67]
I needed to refresh my go packages and when I refreshed ora, I lost the commits related to the numstring changes recently made by @tgulacsi. I see the code in master branch on github however the version I get from 
`go get gopkg.in/rana/ora.v3 ` 
is older of course. I couldn't manage to get the master branch and I see that the feature branches got cleaned up.

**Comment by tgulacsi** [comment]
cd $GOPATH/src/gopkg/rana/ora.v3 && git fetch origin && git checkout -b master origin/master

But I'm inclined to close #57 and tag it as v3.3 - if nobody yells against it.

**Comment by omerkirk** [comment]
I tried that but it doesn't work. 
`git checkout -b master origin/master`
this returns an error a branch called master already exists. 
`git checkout -b latest origin/master`
and this doesn't get the latest code somehow. 

Am I doing something wrong.

**Comment by omerkirk** [comment]
On a side not I think @maliutin is ok with the final state of the issue since he didn't give any negative feedback. And every case on my side was working correctly.

**Comment by tgulacsi** [comment]
Thanks, I've tagged the current master as v3.3. If you do an
rm -rf $GOPATH/src/gopkg.in/rana/ora.v3; go get gopkg.in/rana/ora.v3
it should be ok.

But maybe you're missing something from master which realy isn't there?

omerkirk <notifications@github.com> ezt írta (időpont: 2016. márc. 8., K,
16:02):

**Comment by omerkirk** [comment]
Working great now. I was checking the const.go file before, looking for ora.N constant. Anyway it is fixed now closing the issue.
