### ISSUE TITLE
[ora v3.3 - Golang 1.6] runtime error: cgo argument has Go pointer to Go pointer goroutine 1 

### ISSUE THREAD

**Issue by yourchanges** [rana/ora#75]
panic: error getting description for "SELECT * FROM STG_PERFECTCOMP.REWARD WHERE  rownum<1": Ses.Prep.func1 recovered: runtime error: cgo argument has Go pointer to Go pointer
goroutine 1 [running]:
gopkg.in/rana/ora%2ev3.errR(0xc08202b1a8, 0x1, 0x1, 0x0, 0x0)
	D:/goworkspace/src/gopkg.in/rana/ora.v3/util.go:231 +0x9e
gopkg.in/rana/ora%2ev3.(*Ses).Prep.func1(0xc08202b650)
	D:/goworkspace/src/gopkg.in/rana/ora.v3/ses.go:245 +0xa9
panic(0x671960, 0xc082005440)
	D:/go1.6/src/runtime/panic.go:426 +0x4f7
gopkg.in/rana/ora%2ev3._cgoCheckPointer0(0x611540, 0xc0820a8368, 0x0, 0x0, 0x0, 0x3547510)
	??:0 +0x54
gopkg.in/rana/ora%2ev3.(*Stmt).attr(0xc0820a8280, 0xc0820a8368, 0x1800000004, 0x0, 0x0)
	D:/goworkspace/src/gopkg.in/rana/ora.v3/stmt.go:1152 +0xcb
gopkg.in/rana/ora%2ev3.(*Ses).Prep(0xc08202ca80, 0x737cc0, 0x34b, 0x0, 0x0, 0x0, 0xc0820a8280, 0x0, 0x0)
	D:/goworkspace/src/gopkg.in/rana/ora.v3/ses.go:291 +0x90b
gopkg.in/rana/ora%2ev3.(*Con).Prepare(0xc0820bb480, 0x737cc0, 0x34b, 0x0, 0x0, 0x0, 0x0)
	D:/goworkspace/src/gopkg.in/rana/ora.v3/conn.go:117 +0x106
database/sql.(*DB).exec(0xc08208b290, 0x737cc0, 0x34b, 0xc0820bb360, 0x2, 0x2, 0xc082004d01, 0x0, 0x0, 0x0, ...)
	D:/go1.6/src/database/sql/sql.go:1046 +0x3dd
database/sql.(*DB).Exec(0xc08208b290, 0x737cc0, 0x34b, 0xc0820bb360, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	D:/go1.6/src/database/sql/sql.go:1009 +0xc5
github.com/tgulacsi/go/orahlp.DescribeQuery(0x11744d0, 0xc08208b290, 0xc082008ec0, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/goworkspace/src/github.com/tgulacsi/go/orahlp/orahlp.go:74 +0x24e
main.GetColumns(0xc08208b290, 0xc082008ec0, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:243 +0xb5
main.generate(0x6bebf0, 0x6)
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:226 +0x174
main.main()
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:323 +0x253

goroutine 1 [running]:
panic(0x6a02e0, 0xc08200ddb0)
	D:/go1.6/src/runtime/panic.go:464 +0x3f4
main.checkErr(0x1174250, 0xc08200ddb0)
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:79 +0x52
main.generate(0x6bebf0, 0x6)
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:227 +0x1c3
main.main()
	C:/Users/your_/IdeaProjects/dataCleaner/main.go:323 +0x253

**Comment by tgulacsi** [comment]
Sorry, what is your git revision? v3.3 is 3b4c86d, and stmt.go line 1152 is an empty line.

**Comment by yourchanges** [comment]
seems not the latest version：

your_@leewin10 MINGW64 /d/goworkspace/src/gopkg.in/rana/ora.v3 (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

your_@leewin10 MINGW64 /d/goworkspace/src/gopkg.in/rana/ora.v3 (master)
$ git log

commit c6ba8c31ca98b09dc9193339fe5a7ecd4c2b75e2
Merge: 7098e19 ea0ccce
Author: Rana Ian <rana@users.noreply.github.com>
Date:   Sun Aug 30 13:57:05 2015 -0700

    Merge pull request #32 from rana/Fix-ORA-24435-OCISvcCtx-in-multi-threaded-scenario

    removed gopkg.in reference

commit ea0cccecb73962137062addffdba0d95ca143c5d
Author: rana <rana_ian@gmail.com>
Date:   Sun Aug 30 13:56:19 2015 -0700

    removed gopkg.in reference

    causes build failures on windows

**Comment by yourchanges** [comment]
thanks, it works
