### ISSUE TITLE
Failing: go get -u gopkg.in/rana/ora.v3 (after upgrade to go v1.6)

### ISSUE THREAD

**Issue by crisarceramos** [rana/ora#79]
Hi guys need your help. I update to go 1.6 and i cannot update ora.v3 due to below failures. 
Thanks.

`user@hostname:/usr/local/share/pkgconfig$ go get -u gopkg.in/rana/ora.v3
# gopkg.in/rana/ora.v3
/goWorkspace/src/gopkg.in/rana/ora.v3/bndBfile.go:9:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
`

**Comment by tgulacsi** [comment]
Either set CGO_CFALGS or copy contribute/oci8.PC to a pk-config lib (see
readme or man pkgconfig).

cacr <notifications@github.com> ezt írta (időpont: 2016. ápr. 5., K 8:05):

**Comment by crisarceramos** [comment]
i have this configured but not working. Am i missing something?

`user@hostname:/usr/local/share/pkgconfig$ pkg-config --list-all |grep oci
oci8_windows_amd64             oci8 - Oracle database engine
oci8_linux_amd64               oci8 - Oracle database engine
oci8                           oci8 - Oracle database engine

user@hostname:/usr/local/share/pkgconfig$ cat oci8.pc 
prefix=/home/user/Apps/oracle/instantclient_12_1

version=12.1
build=client64

libdir=${prefix}/lib/oracle/${version}/${build}/lib
includedir=${prefix}/include/oracle/${version}/${build}

Name: oci8
Description: Oracle database engine
Version: ${version}
Libs: -L${libdir} -lclntsh
Libs.private:
Cflags: -I${includedir}
 
`

**Comment by crisarceramos** [comment]
thanks! set CGO_CFLAGS and CGO_LDFLAGS and it works!

**Comment by tgulacsi** [comment]
"pkg-config oci8 --cflags" should return the proper CFLAGS.
Only one oci8.pc should be at
/usr/local/share/pkgconfig !

cacr <notifications@github.com> ezt írta (időpont: 2016. ápr. 6., Sze,
3:17):
