### ISSUE TITLE
Connect with sysdba privilege

### ISSUE THREAD

**Issue by benbve** [rana/ora#81]
There does not appear to be a way to connect with the sysdba privilege (which is available in oci8)

**Comment by tgulacsi** [comment]
Sorry, but I cannot find how go-oci8 does it.

**Comment by tgulacsi** [comment]
Can you try the "sysdba" branch?

**Comment by benbve** [comment]
Sorry I wasn't referring to go-oci8 - was referring to the oci.dll (windows) in oci.h the following exists:
/*--------------------------- OCISessionGet Modes ---------------------------*/

#define OCI_SESSGET_SPOOL      0x0001     /* SessionGet called in SPOOL mode */
#define OCI_SESSGET_CPOOL      OCI_CPOOL  /* SessionGet called in CPOOL mode */
#define OCI_SESSGET_STMTCACHE  0x0004                 /* Use statement cache */
#define OCI_SESSGET_CREDPROXY  0x0008     /* SessionGet called in proxy mode */
#define OCI_SESSGET_CREDEXT    0x0010     
#define OCI_SESSGET_SPOOL_MATCHANY 0x0020
#define OCI_SESSGET_PURITY_NEW     0x0040 
#define OCI_SESSGET_PURITY_SELF    0x0080 
#define OCI_SESSGET_SYSDBA    0x0100    /* SessionGet with SYSDBA privileges */

However, on further review I cannot find any OCI programs that enable connection using this flag (but many asking for it) and it does appear to be there.  Such privilege is possible is JDBC using the "internal_logon" property.  I was hoping you might know more?

And what is the "sysdba" branch?

**Comment by benbve** [comment]
Ah I see you updated the sysdba branch not long ago - will give that a try, thx

**Comment by benbve** [comment]
Thanks for the very quick response, btw.
OK have tried that. Didn't work :(
I used: 
db, err := sql.Open("ora", "sys/xxxxxxx@127.0.0.1/XE AS SYSDBA") to attempt to connect to a standby database (which will only allow a SYSDBA connection - same as with a database in mount state) and it failed the same way as it does with a normal user connection.
SQLPlus with same string works.

**Comment by tgulacsi** [comment]
What is that "same way"? Connecting with SYSDBA privilege is not the same as connecting to a standby db...
Please check with a normal DB first, then we can try to work out the standby state.

I've added TestSysdba into z_db_test.go; you can set the username/password with GO_ORA_DRV_TEST_SYSDBA_USERNAME/GO_ORA_DRV_TEST_SYSDBA_PASSWORD env vars.
For me now it says "
        z_db_test.go:323: "test/test@oracle.gthomas.eu:49161 AS SYSDBA": Drv.Open Env.OpenCon Srv.OpenSes Env.ociError ORA-01031: insufficient privileges
"
when I do a `go test -run=Sysdba -v`.

**Comment by benbve** [comment]
if I change lines 203-209 approx to be:
/*
	mode := C.ub4(C.OCI_DEFAULT)
	switch cfg.Mode {
	case SysDba:
		mode |= C.OCI_SYSDBA
	case SysOper:
		mode |= C.OCI_SYSOPER
	}
    */
    mode := C.ub4(C.OCI_SYSDBA)
then it works. (ie. just set the mode directly
Which implies that the "SysDba" is not being picked up

**Comment by benbve** [comment]
Ah In src.go that is

**Comment by benbve** [comment]
OK Please ignore previous. My setup was not right.  Have retested.  All good now. :) :+1: 
Thank you very much.
