### ISSUE TITLE
Does it have a method like 'executemany'

### ISSUE THREAD

**Issue by yourchanges** [rana/ora#90]
For speedup insert/update/merge, we use executemany(http://cx-oracle.readthedocs.io/en/latest/cursor.html#Cursor.executemany) in python, does ora.v3 have this method or similar?

And how to use it?

**Comment by tgulacsi** [comment]
Just use Exe and PrepAndExe with slice arguments.

yourchanges <notifications@github.com> ezt írta (időpont: 2016. máj. 30., H
12:24):

**Comment by yourchanges** [comment]
But  one more question: the element of slice will be the same type(not like python list), so how I handle the different type arguments(using struct in slice?)?

Could you give a sample?

**Comment by tgulacsi** [comment]
```
_, err := ses.PrepAndExe(`INSERT INTO table (c1, c2) VALUES (:1, :2)`, []int64{1,2}, []string{"a", "b"})
```

**Comment by yourchanges** [comment]
Well, it's totally different from python and hard to use.

For example, if we fetch rows from one table, and then I need re-factory the rows into above several slice, and then insert/update into another table.

**Comment by yourchanges** [comment]
whatever, I'll try to test it firstly to make sure it works

**Comment by tgulacsi** [comment]
Yes, Oracle needs to get the bind parameters as slices. Python hides this complexity, ora does not.
But it is a trivial for cycle to rearrange as you need.
