### ISSUE TITLE
CLOB as out parameter

### ISSUE THREAD

**Issue by maliutin** [rana/ora#91]
Hello

I have the procedure:
`PROCEDURE get_json(p_statement_id NUMBER, p_json OUT CLOB)`

Please, show how can I correctly call this procedure?

**Comment by tgulacsi** [comment]
As ExampleWriteBLOB  (z_example_test.go)
```
var clob lobReader
stmt, err := ses.Prep("BEGIN get_json(:1, :2); END;", ora.I64, ora.OraBin)
var lob ora.Lob
_, err := stmt.Exe(1, &lob)
ioutil.ReadAll(lob)
```
(not tested)

**Comment by maliutin** [comment]
What is `lobReader`?

**Comment by tgulacsi** [comment]
It is an io.Reader. Can you share what you got?

**Comment by maliutin** [comment]
Hi, @tgulacsi 

Thank you for your answer.
Now, I use following scenario:

```GO
var jsonValue string
stmt, err := ses.Prep("CALL get_json(:1, :2)")
_, err := stmt.Exe(1, &jsonValue)
```
I think how to read the data in the stream that would not allocate additional memory for buffering values.

**Comment by tgulacsi** [comment]
If get_json has `OUT CLOB` in its second parameter, you'll have to use an &ora.Lob.

Ah, now I see the reason for your question. That lobReader is a left-off, it is only ora-internal.

**Comment by maliutin** [comment]
Hi
I try to run following code:

```go
var jsonValue string
stmt, err := ses.Prep("CALL get_json(:1, :2)")
_, err := stmt.Exe(1, &jsonValue)
```

but I found that jsonValue can not have value more than 1000. And also I do not receive any error about this.
In result I get incorrect value.

About 

```go
stmt, err := ses.Prep("CALL get_json(:1, :2)", ora.I64, ora.OraBin)
var lob ora.Lob
_, err := stmt.Exe(1, &lob)
ioutil.ReadAll(lob)
```

It does not work. There is error:

> Stmt.exe Env.ociErrorNL ORA-06553: PLS-306: wrong number or types of arguments in call to 'GET_JSON'

**Comment by tgulacsi** [comment]
The problem here is that we bind as `C.SQLT_BLOB` by default.
I've added a `C` field to `Lob`, to allow bind as CLOB. 
See `TestLOBReader` in `z_oracle_test.go` for usage. (Simply use `lob := &ora.Lob{C:true}` instead of `var lob ora.Lob`.)
