### ISSUE TITLE
Slow fetch of date fields

### ISSUE THREAD

**Issue by sergeilem** [rana/ora#93]
Fetching of oracle date field is significantly slower than fetching of another fileds of ~same size (7 bytes).

Example: i have table with 3 millions of rows and 10 columns. There are "mydate" column, typed as date (7 bytes oracle date).

Speed test results:
select mydate from mytable - fetches **4000** rows per second;
select to_char(mydate,'DD.MM.YYYY') - fetches **100000** rows per second;
select mydate-date'2000-01-01' from mytable - fetches **100000** rows per second.

Golang code is:
  d, err := sql.Open("ora", mydsn)
  c, err := d.Query(`select mydate from mytable`)
  var cnt int = 0
  for c.Next() {
    if(cnt%1000==0){ fmt.Print(".") }
    cnt ++
  }

Speed tested with issue86 version (https://github.com/rana/ora/issues/86).

p.s: SQL Navigator fetches 100000 rows per second for any of 3 variants of my query.

**Comment by tgulacsi** [comment]
See BenchmarkSelectDate in z_benchmem_test.go.

That slowness is relative... It's just 'cause we need to call OCIDateTimeGetDate and OCIDateTimeGetTimeZoneName for each date - for numbers, I've reimplemented the C logic in go, to decode the number form Oracle's packed bytes; for strings, no decoding is needed at all.

```
! go tool pprof ora.v3.test /tmp/cpu.prof
Entering interactive mode (type "help" for commands)
(pprof) cum
(pprof) top20
100ms of 150ms total (66.67%)
Showing top 20 nodes out of 55 (cum >= 10ms)
      flat  flat%   sum%        cum   cum%
         0     0%     0%      120ms 80.00%  gopkg.in/rana/ora%2ev3_test.BenchmarkSelectDate
         0     0%     0%      120ms 80.00%  runtime.goexit
         0     0%     0%      120ms 80.00%  testing.(*B).runN
      80ms 53.33% 53.33%      100ms 66.67%  runtime.cgocall
         0     0% 53.33%      100ms 66.67%  testing.(*B).launch
         0     0% 53.33%       90ms 60.00%  database/sql.(*Rows).Next
         0     0% 53.33%       90ms 60.00%  gopkg.in/rana/ora%2ev3.(*DrvQueryResult).Next
         0     0% 53.33%       60ms 40.00%  gopkg.in/rana/ora%2ev3.(*defTime).value
         0     0% 53.33%       60ms 40.00%  gopkg.in/rana/ora%2ev3.getTime
         0     0% 53.33%       30ms 20.00%  gopkg.in/rana/ora%2ev3.(*Rset).beginRow
         0     0% 53.33%       20ms 13.33%  database/sql.(*DB).Query
         0     0% 53.33%       20ms 13.33%  database/sql.(*DB).query
         0     0% 53.33%       20ms 13.33%  gopkg.in/rana/ora%2ev3._Cfunc_OCIDateTimeGetDate
         0     0% 53.33%       20ms 13.33%  gopkg.in/rana/ora%2ev3._Cfunc_OCIDateTimeGetTimeZoneName
         0     0% 53.33%       20ms 13.33%  runtime.mstart
         0     0% 53.33%       20ms 13.33%  runtime.mstart1
      10ms  6.67% 60.00%       20ms 13.33%  runtime.sysmon
      10ms  6.67% 66.67%       20ms 13.33%  runtime.systemstack
         0     0% 66.67%       20ms 13.33%  testing.(*B).run1.func1
         0     0% 66.67%       10ms  6.67%  database/sql.(*DB).conn
```

**Comment by tgulacsi** [comment]
Ok, we have other reasons for the slowness, too: the SQLT_DAT route goes to the same high precision defTime functions, as does timestamps. But we already have the second-precision defDate functions, so should use that.

Also added a Go-only encode/decode of that [7]byte of what Oracle calls DATE (SQLT_DAT), into date subfolder.

Please test the "date" branch!

**Comment by sergeilem** [comment]
Tested 'date' branch, test results:

select mydate from mytable - fetches **100000** rows per second;
select mydate-date'2000-01-01' from mytable - fetches **100000** rows per second.

Nice!

And more good news, memory usage in 'date' branch is stable, for my test app is ~45 Mb. 
In main branch, it grows while fetching from ~45Mb to ~90 Mb for 'select date', and it was constant 45 Mb for 'select int'. So there may be leaks in 'select date' fetch in main branch.

**Comment by tgulacsi** [comment]
Thanks for the tests, I've merged the "date" branch into "master".
